//! The [`ConfigStore`] the Settings app and the [`ConfStore`] the Config app
//! use over `confd` (`os.lazy.confd.v1`).
//!
//! Bodies come from the generated `messenger-generated` stubs; only the
//! wire-`Value` <-> `confd::Value` glue lives here. `sys/**` is writable only
//! by uid 0, which is what every desktop app runs as today. The two traits
//! differ in error handling: Settings ignores failures (`Option`/`String`),
//! while Config maps the `CONFD_*` codes onto [`ConfStoreError`] so it can tell
//! `DENIED` from `NOT_FOUND`.

use messenger_generated::os_lazy_confd_v1 as wire;
use messenger_generated::os_lazy_init_v1 as init_wire;
use xui_confd_editor::store::{ConfStore, StoreError as ConfStoreError, StoreInfo};
use xui_settings::store::{AppChoice, ConfigStore, StoreError as SettingsError, Value};

use super::messenger::Service;

/// The registered service name (not the interface name).
const NAME: &str = "os.lazy.confd";
/// `init`'s registered service name (owner of the app registry).
const INIT_NAME: &str = "os.lazy.init";
/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;

const KIND_BOOL: u32 = 0;
const KIND_I64: u32 = 1;
const KIND_U64: u32 = 2;
const KIND_STR: u32 = 3;
const KIND_BYTES: u32 = 4;

/// Reads and writes settings through `confd`.
#[derive(Clone, Copy, Debug, Default)]
pub struct ConfdStore;

impl ConfdStore {
    pub const fn new() -> ConfdStore {
        ConfdStore
    }

    fn call(&self, method: u32, body: Vec<u8>) -> Result<libmessenger::Parcel, SettingsError> {
        let service =
            Service::connect(NAME).map_err(|code| format!("confd unavailable ({code})"))?;
        service
            .call(wire::INTERFACE_ID, method, ERROR_FIELD, body)
            .map_err(|code| format!("confd error {code}"))
    }

    /// The same call with the raw code kept, so the Config app can map the
    /// `CONFD_*` codes onto [`ConfStoreError`] instead of a display string.
    fn call_raw(&self, method: u32, body: Vec<u8>) -> Result<libmessenger::Parcel, i64> {
        let service = Service::connect(NAME)?;
        service.call(wire::INTERFACE_ID, method, ERROR_FIELD, body)
    }
}

/// `confd::Value` -> the generated wire value.
pub fn to_wire(value: &Value) -> wire::Value {
    let mut out = wire::Value::default();
    match value {
        Value::Bool(flag) => {
            out.kind = KIND_BOOL;
            out.bool_value = Some(*flag);
        }
        Value::I64(number) => {
            out.kind = KIND_I64;
            out.i64_value = Some(*number);
        }
        Value::U64(number) => {
            out.kind = KIND_U64;
            out.u64_value = Some(*number);
        }
        Value::Str(text) => {
            out.kind = KIND_STR;
            out.str_value = Some(text.clone());
        }
        Value::Bytes(bytes) => {
            out.kind = KIND_BYTES;
            out.bytes_value = Some(bytes.clone());
        }
    }
    out
}

/// The generated wire value -> `confd::Value`; a kind without its payload is
/// rejected rather than turned into an empty value.
pub fn from_wire(value: &wire::Value) -> Option<Value> {
    match value.kind {
        KIND_BOOL => value.bool_value.map(Value::Bool),
        KIND_I64 => value.i64_value.map(Value::I64),
        KIND_U64 => value.u64_value.map(Value::U64),
        KIND_STR => value.str_value.clone().map(Value::Str),
        KIND_BYTES => value.bytes_value.clone().map(Value::Bytes),
        _ => None,
    }
}

impl ConfigStore for ConfdStore {
    fn get(&self, key: &str) -> Option<Value> {
        let body = wire::encode_get_args(&wire::GetArgs {
            path: key.to_owned(),
        })
        .ok()?;
        let reply = self.call(wire::METHOD_GET, body).ok()?;
        let decoded = wire::decode_get_reply(&reply.body).ok()?;
        from_wire(&decoded.value?)
    }

    fn set(&self, key: &str, value: Value) -> Result<(), SettingsError> {
        let body = wire::encode_set_args(&wire::SetArgs {
            path: key.to_owned(),
            value: to_wire(&value),
        })
        .map_err(|_| String::from("value too large"))?;
        self.call(wire::METHOD_SET, body).map(|_| ())
    }

    fn delete(&self, key: &str) -> Result<(), SettingsError> {
        let body = wire::encode_delete_args(&wire::DeleteArgs {
            path: key.to_owned(),
        })
        .map_err(|_| String::from("path too long"))?;
        self.call(wire::METHOD_DELETE, body).map(|_| ())
    }

    /// The paths under `prefix` this task may read; empty on any failure.
    fn list(&self, prefix: &str) -> Vec<String> {
        let Ok(body) = wire::encode_list_args(&wire::ListArgs {
            prefix: prefix.to_owned(),
        }) else {
            return Vec::new();
        };
        self.call(wire::METHOD_LIST, body)
            .ok()
            .and_then(|reply| wire::decode_list_reply(&reply.body).ok())
            .map(|reply| reply.paths)
            .unwrap_or_default()
    }

    /// This task's kernel-stamped uid: confd checks `user/<uid>/**` writes
    /// against the same one.
    fn uid(&self) -> Option<u32> {
        crate::sys::cred_get(None).ok().map(|cred| cred.uid)
    }

    /// The apps `init` can launch (its registry); empty when `init` cannot be
    /// reached, in which case the menu editor only reorders and renames.
    fn apps(&self) -> Vec<AppChoice> {
        let Ok(service) = Service::connect(INIT_NAME) else {
            return Vec::new();
        };
        let Ok(reply) = service.call(
            init_wire::INTERFACE_ID,
            init_wire::METHOD_LISTAPPS,
            ERROR_FIELD,
            Vec::new(),
        ) else {
            return Vec::new();
        };
        init_wire::decode_list_apps_reply(&reply.body)
            .map(|list| {
                list.apps
                    .into_iter()
                    .map(|app| AppChoice {
                        desktop: app.installed || !app.category.is_empty(),
                        id: app.id,
                        name: app.name,
                    })
                    .collect()
            })
            .unwrap_or_default()
    }

    /// Whether confd chose a persistent directory, as it reports itself: it
    /// falls back to the ramfs `/tmp/confd` when a persistent one is missing,
    /// read-only or fails its probe write, which a directory check cannot see.
    /// An unreachable confd counts as not persistent (writes fail anyway).
    fn persistent(&self) -> bool {
        self.call(wire::METHOD_INFO, Vec::new())
            .ok()
            .and_then(|reply| wire::decode_info_reply(&reply.body).ok())
            .is_some_and(|info| info.persistent)
    }
}

/// The Config app's richer view of the same service: `List`/`Info` and the
/// `CONFD_*` error codes preserved, so the editor can tell `DENIED` from an
/// absent key and show a read-only state instead of a crash.
impl ConfStore for ConfdStore {
    fn list(&self, prefix: &str) -> Result<Vec<String>, ConfStoreError> {
        let body = wire::encode_list_args(&wire::ListArgs {
            prefix: prefix.to_owned(),
        })
        .map_err(|_| ConfStoreError::BadValue)?;
        let reply = self
            .call_raw(wire::METHOD_LIST, body)
            .map_err(ConfStoreError::from_confd_code)?;
        wire::decode_list_reply(&reply.body)
            .map(|reply| reply.paths)
            .map_err(|_| ConfStoreError::BadValue)
    }

    fn get(&self, path: &str) -> Result<Option<Value>, ConfStoreError> {
        let body = wire::encode_get_args(&wire::GetArgs {
            path: path.to_owned(),
        })
        .map_err(|_| ConfStoreError::BadValue)?;
        let reply = self
            .call_raw(wire::METHOD_GET, body)
            .map_err(ConfStoreError::from_confd_code)?;
        let decoded = wire::decode_get_reply(&reply.body).map_err(|_| ConfStoreError::BadValue)?;
        Ok(decoded.value.as_ref().and_then(from_wire))
    }

    fn set(&self, path: &str, value: Value) -> Result<(), ConfStoreError> {
        let body = wire::encode_set_args(&wire::SetArgs {
            path: path.to_owned(),
            value: to_wire(&value),
        })
        .map_err(|_| ConfStoreError::TooLarge)?;
        self.call_raw(wire::METHOD_SET, body)
            .map_err(ConfStoreError::from_confd_code)
            .map(|_| ())
    }

    fn delete(&self, path: &str) -> Result<(), ConfStoreError> {
        let body = wire::encode_delete_args(&wire::DeleteArgs {
            path: path.to_owned(),
        })
        .map_err(|_| ConfStoreError::BadPath)?;
        self.call_raw(wire::METHOD_DELETE, body)
            .map_err(ConfStoreError::from_confd_code)
            .map(|_| ())
    }

    fn info(&self) -> Result<StoreInfo, ConfStoreError> {
        let reply = self
            .call_raw(wire::METHOD_INFO, Vec::new())
            .map_err(ConfStoreError::from_confd_code)?;
        let info = wire::decode_info_reply(&reply.body).map_err(|_| ConfStoreError::BadValue)?;
        Ok(StoreInfo {
            store_dir: info.store_dir,
            persistent: info.persistent,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_value_kind_round_trips() {
        for value in [
            Value::Bool(true),
            Value::I64(-5),
            Value::U64(0xFF00FF),
            Value::Str("light".into()),
            Value::Bytes(vec![1, 2, 3]),
        ] {
            assert_eq!(from_wire(&to_wire(&value)), Some(value));
        }
    }

    #[test]
    fn the_info_reply_round_trips() {
        for persistent in [true, false] {
            let body = wire::encode_info_reply(&wire::InfoReply {
                store_dir: "/conf".to_owned(),
                persistent,
            })
            .unwrap();
            let info = wire::decode_info_reply(&body).unwrap();
            assert_eq!(info.store_dir, "/conf");
            assert_eq!(info.persistent, persistent);
        }
    }

    #[test]
    fn a_kind_without_its_payload_is_rejected() {
        let mut v = wire::Value {
            kind: KIND_STR,
            ..wire::Value::default()
        };
        assert_eq!(from_wire(&v), None);
        v.kind = 99;
        assert_eq!(from_wire(&v), None);
    }
}
