//! The Settings app's [`System`] on LazyOS: the clock and zone through `timed`
//! (`os.lazy.timed.v1`), the store location through `confd`'s `Info`, uptime
//! from the kernel `sysinfo` block and the version from `uname`.
//!
//! Bodies come from the generated `messenger-generated` stubs; a failure is
//! reported as text for the status line.

use messenger_generated::os_lazy_timed_v1 as wire;
use xui_confd_editor::store::ConfStore;
use xui_settings::system::{Now, StoreStatus, System};

use super::confd_store::ConfdStore;
use super::messenger::Service;
use crate::sys::errno;

/// `timed`'s registered service name.
const NAME: &str = "os.lazy.timed";
/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;
/// PIT ticks per second.
const HZ: u64 = 100;
/// How often, and how far apart, a zone change is checked for: two seconds.
const ZONE_POLLS: u32 = 40;
const ZONE_POLL_MS: u64 = 50;

/// The live system.
#[derive(Clone, Copy, Debug, Default)]
pub struct OsSystem;

impl OsSystem {
    pub const fn new() -> OsSystem {
        OsSystem
    }

    /// Wait (briefly, bounded) until `timed` reports `zone`: it follows the
    /// confd key `elevd` wrote on its own change notification, so the page
    /// that re-reads the time right after would otherwise show the old zone.
    /// False when `timed` has not switched within the bound.
    fn await_zone(&self, zone: &str) -> bool {
        for _ in 0..ZONE_POLLS {
            if self.now().is_some_and(|now| now.zone == zone) {
                return true;
            }
            std::thread::sleep(std::time::Duration::from_millis(ZONE_POLL_MS));
        }
        false
    }

    fn call(&self, method: u32, body: Vec<u8>) -> Result<libmessenger::Parcel, String> {
        let service =
            Service::connect(NAME).map_err(|_| String::from("time service unavailable"))?;
        service
            .call(wire::INTERFACE_ID, method, ERROR_FIELD, body)
            .map_err(describe)
    }
}

/// A `timed` error code as status-line text.
fn describe(code: i64) -> String {
    match -code {
        errno::EPERM => String::from("permission denied (needs CAP_SYS_TIME)"),
        errno::EINVAL => String::from("value refused"),
        _ => format!("time service error {code}"),
    }
}

/// `sysname release (machine)` from `uname`, e.g. `LazyOS 0.1.0 (x86_64)`.
#[cfg(target_os = "linux")]
fn uname() -> Option<String> {
    // SAFETY: `utsname` is plain bytes, so all-zero is a valid value, and
    // `uname` only writes into the struct it is handed.
    let mut info: libc::utsname = unsafe { std::mem::zeroed() };
    // SAFETY: `info` is a valid, writable `utsname` for the duration of the call.
    if unsafe { libc::uname(&mut info) } != 0 {
        return None;
    }
    let field = |raw: &[libc::c_char]| -> String {
        let bytes: Vec<u8> = raw
            .iter()
            .take_while(|c| **c != 0)
            .map(|c| *c as u8)
            .collect();
        String::from_utf8_lossy(&bytes).into_owned()
    };
    Some(format!(
        "{} {} ({})",
        field(&info.sysname),
        field(&info.release),
        field(&info.machine)
    ))
}

/// Host builds (tests) have no LazyOS kernel to ask.
#[cfg(not(target_os = "linux"))]
fn uname() -> Option<String> {
    None
}

/// The picture files in `dir` (PNG and JPEG, by extension), sorted by path.
fn pictures_in(dir: &str) -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut pictures: Vec<String> = entries
        .flatten()
        .filter_map(|entry| entry.file_name().into_string().ok())
        .filter(|name| {
            let lower = name.to_ascii_lowercase();
            [".png", ".jpg", ".jpeg"]
                .iter()
                .any(|ext| lower.ends_with(ext))
        })
        .map(|name| format!("{dir}/{name}"))
        .collect();
    pictures.sort();
    pictures
}

impl System for OsSystem {
    fn wallpapers(&self) -> Vec<String> {
        pictures_in(fhs::share::WALLPAPERS)
    }

    fn now(&self) -> Option<Now> {
        let reply = self.call(wire::METHOD_NOW, Vec::new()).ok()?;
        let now = wire::decode_now_reply(&reply.body).ok()?;
        Some(Now {
            unix: now.unix_ms.div_euclid(1000),
            offset: now.tz_offset_s,
            zone: now.tz_name,
        })
    }

    /// Setting the clock is a system change (docs/accounts-plan.md U2): a
    /// session never holds `CAP_SYS_TIME`, so a refusal is asked again
    /// through `elevd`, where an administrator approves.
    fn set_time(&self, unix: i64) -> Result<(), String> {
        let body = wire::encode_set_time_args(&wire::SetTimeArgs { unix_secs: unix })
            .map_err(|_| String::from("bad time"))?;
        let service =
            Service::connect(NAME).map_err(|_| String::from("time service unavailable"))?;
        match service.call(wire::INTERFACE_ID, wire::METHOD_SETTIME, ERROR_FIELD, body) {
            Ok(_) => Ok(()),
            Err(code) if -code == errno::EPERM => {
                super::elevd::request("time.set", &[&unix.to_string()])
                    .map(|_| ())
                    .map_err(|error| super::elevd::describe(&error))
            }
            Err(code) => Err(describe(code)),
        }
    }

    fn set_zone(&self, zone: &str) -> Result<(), String> {
        let body = wire::encode_set_zone_args(&wire::SetZoneArgs {
            name: zone.to_owned(),
        })
        .map_err(|_| String::from("bad zone name"))?;
        let service =
            Service::connect(NAME).map_err(|_| String::from("time service unavailable"))?;
        match service.call(wire::INTERFACE_ID, wire::METHOD_SETZONE, ERROR_FIELD, body) {
            Ok(_) => Ok(()),
            // A machine setting, like the clock: a session asks an
            // administrator, and `timed` follows the confd key `elevd` writes.
            Err(code) if -code == errno::EPERM => {
                super::elevd::request("conf.set", &[timezone::ZONE_KEY, "str", zone])
                    .map_err(|error| super::elevd::describe(&error))?;
                if self.await_zone(zone) {
                    Ok(())
                } else {
                    Err(String::from(
                        "approved, but the time service has not switched to it yet",
                    ))
                }
            }
            Err(code) => Err(describe(code)),
        }
    }

    fn os_version(&self) -> String {
        uname().unwrap_or_else(|| String::from("LazyOS"))
    }

    fn uptime_secs(&self) -> Option<u64> {
        crate::sysinfo::snapshot()
            .ok()
            .map(|snapshot| snapshot.ticks / HZ)
    }

    fn store_status(&self) -> Option<StoreStatus> {
        ConfStore::info(&ConfdStore::new())
            .ok()
            .map(|info| StoreStatus {
                dir: info.store_dir,
                persistent: info.persistent,
            })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn errors_read_as_text() {
        assert!(describe(-errno::EPERM).contains("CAP_SYS_TIME"));
        assert!(describe(-errno::EINVAL).contains("refused"));
        assert!(describe(-99).contains("-99"));
    }

    #[test]
    fn the_now_reply_round_trips() {
        let body = wire::encode_now_reply(&wire::NowReply {
            unix_ms: 1_790_715_899_500,
            tz_offset_s: 7200,
            tz_name: "Europe/Paris".into(),
            dst: true,
        })
        .unwrap();
        let now = wire::decode_now_reply(&body).unwrap();
        assert_eq!(now.unix_ms.div_euclid(1000), 1_790_715_899);
        assert_eq!(now.tz_name, "Europe/Paris");
    }
}
