//! Sources and their work: `msg::on(filter, |event| ...)`, `msg::serve(...)`
//! and the blocking `msg::run()`.
//!
//! Rhai is single-threaded, so a script that reacts to the fabric registers
//! *sources* (topic subscriptions with a handler, served endpoints with a
//! handler per method). Something then waits on them and runs the handlers:
//! `msg::run()` in the `rhai` command, which blocks until `msg::stop()` or its
//! time budget, or a LazyRAD form's window timer (`super::events`), which
//! takes only what is ready so the window keeps painting. Both go through
//! [`poll`] and [`handle`], so they answer services, ack reliable topics and
//! turn thrown values into structured errors the same way.
//!
//! Every source has an *owner*: the form whose script registered it (empty
//! for the `rhai` command). A window pumps only its own form's sources and
//! releases them when it closes.
//!
//! Serving: `msg::serve(name, interface, #{ Echo: |text, count| ... })`
//! registers `name` with the kernel and answers each call by running the
//! method's handler with the decoded arguments (in IDL order). The handler's
//! value is the reply (one return value, or a map for several). A handler that
//! throws answers with a structured error the caller sees as a catchable
//! error: the thrown text with `EIO`, or `#{ code: 13, message: "..." }` for a
//! specific errno. One-way methods run their handler and send nothing back.

use alloc::boxed::Box;
use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::cell::Cell;

use libmessenger::Encoder;
use rhai::{Dynamic, EvalAltResult, FnPtr, Map, NativeCallContext, INT};

use super::bus::{Incoming, Wait};
use super::codec;
use super::schema::{self, Interface, Method};
use super::service::{script_error, Fabric, Fallible};
use super::topics::Subscription;

/// Runs a handler: `FnPtr::call_within_context` inside `msg::run`, the form's
/// engine and AST when a window pumps.
pub type Call<'a> = dyn FnMut(&FnPtr, Vec<Dynamic>) -> Result<Dynamic, Box<EvalAltResult>> + 'a;

/// Longest single wait when only one source is registered, so `run(ms)`
/// still notices its own deadline promptly.
const SLICE_MS: u64 = 250;
/// Per-source wait when several are registered: one PIT tick each.
const POLL_MS: u64 = 10;
/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;
const EIO: u32 = 5;
const ENOSYS: u32 = 38;

/// Something a handler waits on.
pub enum SourceKind {
    Topic {
        subscription: Subscription,
        handler: FnPtr,
    },
    Service {
        name: String,
        endpoint: u64,
        interface: &'static Interface,
        handlers: Vec<(&'static Method, FnPtr)>,
    },
}

/// A registered source and the script that registered it.
pub struct Source {
    pub(crate) owner: String,
    pub(crate) kind: SourceKind,
    /// Consecutive failed passes, so a handler failing on every event is
    /// reported once rather than once per event (`super::events`).
    pub(crate) failures: Cell<u32>,
}

impl Source {
    fn new(owner: &str, kind: SourceKind) -> Self {
        Self {
            owner: owner.to_string(),
            kind,
            failures: Cell::new(0),
        }
    }
}

/// `msg::on(filter, handler)`: subscribe and remember the handler.
pub fn on(
    fabric: &Rc<Fabric>,
    owner: &str,
    filter: &str,
    opts: &Map,
    handler: FnPtr,
) -> Fallible<Subscription> {
    let subscription = super::topics::subscribe(fabric, filter, opts)?;
    let kind = SourceKind::Topic {
        subscription: subscription.clone(),
        handler,
    };
    fabric.sources.borrow_mut().push(Source::new(owner, kind));
    Ok(subscription)
}

/// `msg::serve(name, interface, handlers)`: register and remember.
pub fn serve(
    fabric: &Rc<Fabric>,
    owner: &str,
    name: &str,
    interface: &str,
    handlers: Map,
) -> Fallible<()> {
    let iface = schema::interface(interface)
        .ok_or_else(|| script_error(format!("msg::serve: unknown interface `{interface}`")))?;
    let mut table = Vec::new();
    for (key, value) in handlers {
        let method = iface.method(&key).ok_or_else(|| {
            script_error(format!("msg::serve: {} has no method `{key}`", iface.name))
        })?;
        let handler = value.try_cast::<FnPtr>().ok_or_else(|| {
            script_error(format!(
                "msg::serve: the handler for `{key}` is not a function"
            ))
        })?;
        table.push((method, handler));
    }
    let endpoint = fabric
        .bus()
        .register(name, &[iface.id], &[iface.name])
        .map_err(|e| script_error(format!("msg::serve: cannot register `{name}`: {e}")))?;
    let kind = SourceKind::Service {
        name: name.into(),
        endpoint,
        interface: iface,
        handlers: table,
    };
    fabric.sources.borrow_mut().push(Source::new(owner, kind));
    Ok(())
}

/// What one pass over a source produced, taken out of the source list so no
/// borrow is held while a handler runs (a handler may call `msg::on` too).
pub(crate) enum Work {
    Event(Subscription, FnPtr, Dynamic),
    Request(
        &'static Interface,
        Option<(&'static Method, FnPtr)>,
        Incoming,
    ),
}

/// The next piece of work from source `index`, waiting as `wait` allows.
pub(crate) fn poll(fabric: &Fabric, index: usize, wait: Wait) -> Fallible<Option<Work>> {
    let sources = fabric.sources.borrow();
    let Some(source) = sources.get(index) else {
        return Ok(None);
    };
    match &source.kind {
        SourceKind::Topic {
            subscription,
            handler,
        } => {
            let (subscription, handler) = (subscription.clone(), handler.clone());
            drop(sources);
            let event = subscription.next(wait)?;
            Ok((!event.is_unit()).then(|| Work::Event(subscription, handler, event)))
        }
        SourceKind::Service {
            name,
            endpoint,
            interface,
            handlers,
        } => {
            let incoming = fabric
                .bus()
                .recv(*endpoint, wait)
                .map_err(|e| script_error(format!("msg: serving {name}: {e}")))?;
            Ok(incoming.map(|request| {
                let handler = interface
                    .method_by_id(request.method)
                    .and_then(|m| handlers.iter().find(|(h, _)| h.id == m.id).cloned());
                Work::Request(interface, handler, request)
            }))
        }
    }
}

/// The error a thrown value becomes on the wire: `(code, message)`.
fn thrown(error: &EvalAltResult) -> (u32, String) {
    // The throw happened inside the handler closure: look past the call frame.
    let error = error.unwrap_inner();
    if let EvalAltResult::ErrorRuntime(value, _) = error {
        if let Some(map) = value.read_lock::<Map>() {
            let code = map
                .get("code")
                .and_then(|c| c.as_int().ok())
                .unwrap_or(EIO as INT);
            let message = map
                .get("message")
                .map_or_else(String::new, |m| m.to_string());
            return (u32::try_from(code).unwrap_or(EIO), message);
        }
        return (EIO, value.to_string());
    }
    (EIO, error.to_string())
}

fn error_body(code: u32, message: &str) -> Vec<u8> {
    let mut body = Encoder::new();
    // A message too long for a body is cut rather than lost.
    let message: String = message.chars().take(512).collect();
    let _ = body.error(ERROR_FIELD, code, &message);
    body.finish()
}

/// Answer one request: decode, run the handler, encode the reply or error.
fn answer(
    call: &mut Call,
    iface: &'static Interface,
    handler: Option<(&'static Method, FnPtr)>,
    request: &Incoming,
) -> Vec<u8> {
    let Some((method, handler)) = handler else {
        return error_body(ENOSYS, "this Rhai service does not handle that method");
    };
    let args = match codec::decode_named(iface, method.params, &request.body, 0) {
        Ok(mut map) => method
            .params
            .iter()
            .map(|p| map.remove(p.name).unwrap_or(Dynamic::UNIT))
            .collect::<Vec<_>>(),
        Err(e) => return error_body(22, &format!("bad arguments: {e}")),
    };
    let value = match call(&handler, args) {
        Ok(value) => value,
        Err(error) => {
            let (code, message) = thrown(&error);
            return error_body(code, &message);
        }
    };
    let encoded = match method.returns {
        [] => Ok(Vec::new()),
        [_] => codec::encode_positional(iface, method.returns, core::slice::from_ref(&value)),
        _ => match value.read_lock::<Map>() {
            Some(map) => codec::encode_named(iface, method.returns, &map, 0),
            None => Err(format!(
                "the handler must return a map of {} values",
                method.returns.len()
            )),
        },
    };
    encoded.unwrap_or_else(|e| {
        error_body(
            EIO,
            &format!("{}: bad reply from the handler: {e}", method.name),
        )
    })
}

/// Run one piece of work. A topic handler's error comes back to the caller
/// *after* a reliable event is acked: the event reached the script, and
/// redelivering it would only fail again. A service handler's error is the
/// reply the caller gets, so it is not an error here.
pub(crate) fn handle(fabric: &Fabric, work: Work, call: &mut Call) -> Fallible<()> {
    match work {
        Work::Event(subscription, handler, event) => {
            let sequence = event
                .read_lock::<Map>()
                .and_then(|m| m.get("sequence").and_then(|s| s.as_int().ok()));
            // A topic handler's value has no reader.
            let outcome = call(&handler, alloc::vec![event]).map(|_| ());
            if let (true, Some(sequence)) = (subscription.is_reliable(), sequence) {
                subscription.ack(sequence)?;
            }
            outcome
        }
        Work::Request(iface, handler, request) => {
            let body = answer(call, iface, handler, &request);
            if let Some(txn) = request.txn {
                fabric
                    .bus()
                    .reply(txn, request.interface, request.method, &body)
                    .map_err(|e| script_error(format!("msg: reply: {e}")))?;
            }
            Ok(())
        }
    }
}

/// `msg::run([ms])`: wait on `owner`'s sources and run handlers until
/// `msg::stop()` or, with `ms`, until that much time has passed. Returns the
/// number of events and requests handled.
pub fn run(
    ctx: &NativeCallContext,
    fabric: &Rc<Fabric>,
    owner: &str,
    budget_ms: Option<u64>,
) -> Fallible<INT> {
    let now_ms = || fabric.bus().clock_ms();
    let mine = |fabric: &Fabric| -> Vec<usize> {
        let sources = fabric.sources.borrow();
        (0..sources.len())
            .filter(|&i| sources[i].owner == owner)
            .collect()
    };
    if mine(fabric).is_empty() {
        return Err(script_error(
            "msg::run: nothing to wait for (use msg::on or msg::serve first)",
        ));
    }
    let mut call = |handler: &FnPtr, args: Vec<Dynamic>| handler.call_within_context(ctx, args);
    fabric.stop.set(false);
    let started = now_ms();
    let mut handled: INT = 0;
    loop {
        let indices = mine(fabric);
        for &index in &indices {
            let remaining = budget_ms.map(|b| b.saturating_sub(now_ms().saturating_sub(started)));
            if fabric.stop.get() || remaining == Some(0) {
                return Ok(handled);
            }
            let slice = if indices.len() == 1 {
                SLICE_MS
            } else {
                POLL_MS
            };
            let wait = Wait::Ms(remaining.map_or(slice, |r| r.min(slice)).max(1));
            if let Some(work) = poll(fabric, index, wait)? {
                handle(fabric, work, &mut call)?;
                handled += 1;
            }
        }
    }
}
