//! The text of `docs/icons.md`, generated from the table so the catalog app
//! authors read can never drift from the names the code accepts (a test
//! compares the checked-in file with this output).

use std::fmt::Write;

/// The header: the contract and how to use a name, before the table.
const INTRO: &str = "\
# Named icons (`lazyicons`)

<!-- Generated by `cargo run -p lazyicons --example catalog` (in `xui-app/`);
     do not edit by hand. A test keeps this file current. -->

LazyOS names its outline icons with short kebab-case words (`save`,
`volume-2`) so an app, the shell, a LazyRAD form or a script can ask for a
picture by name, including across a process boundary such as the tray. The
table lives in the `lazyicons` crate (`xui-app/crates/named-icons`) over
xui's vendored [Lucide](https://lucide.dev) outlines; each name is the Lucide
file name, so lucide.dev shows the picture. Plan: `docs/tray-plan.md` §6.3.

## The contract

- **Stable, append-only names.** A shipped name is never removed and never
  redrawn as a different picture. If an outline is replaced upstream, its old
  name keeps working as an alias of the replacement.
- **Exact lookups.** Names are case-sensitive and matched exactly. An unknown
  name is an error the caller sees (`None` in Rust), never a silent
  substitute: the caller chooses its own fallback.
- **Growth by request.** Need an icon that is not listed? Add its outline to
  xui (`assets/lucide/`, then its generator), bump the xui revision here, and
  append the name in `xui-app/crates/named-icons/src/names.rs` (the build
  fails until the new outline has a name). Then regenerate this file.

## Use from Rust

```rust
use xui_core::{Color, Rect};

// Look a name up (untrusted input is fine: unknown or oversized is None).
let icon = lazyicons::from_name(\"save\"); // Some(Lucide::Save)

// Or draw it straight onto a canvas, 16 px at 1x; false means unknown.
let drawn = lazyicons::draw(canvas, \"volume-2\", Rect::new(0, 0, 16, 16), Color::rgb(0, 0, 0), 96);
```

";

/// The full Markdown catalog: [`INTRO`], then one table row per name.
pub fn catalog_markdown() -> String {
    let mut out = String::from(INTRO);
    let count = crate::all().count();
    // `write!` into a `String` cannot fail.
    let _ = writeln!(out, "## The names ({count})\n");
    out.push_str("| Name | Rust (`xui_core::Lucide`) |\n|---|---|\n");
    for (name, icon) in crate::all() {
        let _ = writeln!(out, "| `{name}` | `Lucide::{icon:?}` |");
    }
    if !crate::names::ALIASES.is_empty() {
        out.push_str(
            "\n## Aliases\n\nOld names of outlines replaced upstream; they still work.\n\n",
        );
        out.push_str("| Alias | Draws |\n|---|---|\n");
        for &(alias, icon) in crate::names::ALIASES {
            let _ = writeln!(out, "| `{alias}` | `{}` |", crate::name(icon));
        }
    }
    out
}
