//! The name table: one stable kebab-case name per [`Lucide`] outline.
//!
//! The table is an exhaustive `match` rather than a list so that a toolkit
//! bump which adds, renames or removes an outline fails to compile here until
//! a person decides the name: a new outline gets a new name, and a removed
//! one keeps its old name as an alias of its replacement ([`ALIASES`]),
//! because shipped names are a contract that packages and scripts rely on.
//!
//! The names are Lucide's own file names (xui's generated enum documents each
//! variant as "The `<name>` outline"), so an app author finds the picture on
//! lucide.dev under the same word.

use xui_core::Lucide;

/// Old names kept working after their outline was replaced upstream, as
/// `(alias, current outline)`. Empty while no shipped outline has been
/// replaced; an entry is never removed once it has shipped.
pub(crate) const ALIASES: &[(&str, Lucide)] = &[];

/// The canonical name of `icon`, the one [`crate::all`] lists.
pub fn name(icon: Lucide) -> &'static str {
    match icon {
        Lucide::AppWindow => "app-window",
        Lucide::ArrowDownAZ => "arrow-down-a-z",
        Lucide::BetweenHorizontalEnd => "between-horizontal-end",
        Lucide::BetweenHorizontalStart => "between-horizontal-start",
        Lucide::BetweenVerticalEnd => "between-vertical-end",
        Lucide::BetweenVerticalStart => "between-vertical-start",
        Lucide::Bold => "bold",
        Lucide::BookOpen => "book-open",
        Lucide::Box => "box",
        Lucide::Bug => "bug",
        Lucide::Check => "check",
        Lucide::ChevronDown => "chevron-down",
        Lucide::ChevronLeft => "chevron-left",
        Lucide::ChevronRight => "chevron-right",
        Lucide::ChevronUp => "chevron-up",
        Lucide::ChevronsUpDown => "chevrons-up-down",
        Lucide::CircleDot => "circle-dot",
        Lucide::CircleHelp => "circle-help",
        Lucide::CircleX => "circle-x",
        Lucide::ClipboardPaste => "clipboard-paste",
        Lucide::Code => "code",
        Lucide::Copy => "copy",
        Lucide::Disc => "disc",
        Lucide::Download => "download",
        Lucide::Ellipsis => "ellipsis",
        Lucide::ExternalLink => "external-link",
        Lucide::EyeOff => "eye-off",
        Lucide::Eye => "eye",
        Lucide::FileCode => "file-code",
        Lucide::FilePlus => "file-plus",
        Lucide::FileText => "file-text",
        Lucide::File => "file",
        Lucide::FolderOpen => "folder-open",
        Lucide::Folder => "folder",
        Lucide::Group => "group",
        Lucide::Heading1 => "heading-1",
        Lucide::Heading2 => "heading-2",
        Lucide::Heading3 => "heading-3",
        Lucide::History => "history",
        Lucide::Home => "home",
        Lucide::Image => "image",
        Lucide::Inbox => "inbox",
        Lucide::IndentDecrease => "indent-decrease",
        Lucide::IndentIncrease => "indent-increase",
        Lucide::Info => "info",
        Lucide::Italic => "italic",
        Lucide::LayoutGrid => "layout-grid",
        Lucide::Link => "link",
        Lucide::ListOrdered => "list-ordered",
        Lucide::ListTree => "list-tree",
        Lucide::List => "list",
        Lucide::Lock => "lock",
        Lucide::LogOut => "log-out",
        Lucide::Mail => "mail",
        Lucide::Menu => "menu",
        Lucide::Minus => "minus",
        Lucide::Monitor => "monitor",
        Lucide::MousePointer2 => "mouse-pointer-2",
        Lucide::Package => "package",
        Lucide::Pause => "pause",
        Lucide::Pencil => "pencil",
        Lucide::Play => "play",
        Lucide::Plus => "plus",
        Lucide::Printer => "printer",
        Lucide::RectangleHorizontal => "rectangle-horizontal",
        Lucide::Redo2 => "redo-2",
        Lucide::RefreshCw => "refresh-cw",
        Lucide::Repeat => "repeat",
        Lucide::Reply => "reply",
        Lucide::Ruler => "ruler",
        Lucide::SaveAll => "save-all",
        Lucide::Save => "save",
        Lucide::Scissors => "scissors",
        Lucide::Search => "search",
        Lucide::Send => "send",
        Lucide::SeparatorHorizontal => "separator-horizontal",
        Lucide::Settings => "settings",
        Lucide::Shuffle => "shuffle",
        Lucide::SkipBack => "skip-back",
        Lucide::SkipForward => "skip-forward",
        Lucide::SquareCheck => "square-check",
        Lucide::SquareMousePointer => "square-mouse-pointer",
        Lucide::Square => "square",
        Lucide::Star => "star",
        Lucide::Strikethrough => "strikethrough",
        Lucide::Table => "table",
        Lucide::Tag => "tag",
        Lucide::Terminal => "terminal",
        Lucide::TextAlignCenter => "text-align-center",
        Lucide::TextAlignEnd => "text-align-end",
        Lucide::TextAlignJustify => "text-align-justify",
        Lucide::TextAlignStart => "text-align-start",
        Lucide::TextCursorInput => "text-cursor-input",
        Lucide::TextQuote => "text-quote",
        Lucide::Trash2 => "trash-2",
        Lucide::TriangleAlert => "triangle-alert",
        Lucide::Type => "type",
        Lucide::Underline => "underline",
        Lucide::Undo2 => "undo-2",
        Lucide::Unlock => "unlock",
        Lucide::Upload => "upload",
        Lucide::Users => "users",
        Lucide::Volume2 => "volume-2",
        Lucide::WrapText => "wrap-text",
        Lucide::X => "x",
        Lucide::Zap => "zap",
    }
}
