#!/usr/bin/env python3
"""The window create/close soak (issue #161, docs/shell-plan.md S5.3): open
the Calculator from the start menu with the keyboard and close it with
Alt+F4, many times over, then judge the serial log.

Every cycle goes through the whole window-manager path: the shell's menu,
`init.Launch`, `CreateSurface` (`XUID:WM:OPENED`), the client's buffers and
first frame (`CALC:UP:PASS`), Alt+F4's `WindowClose` (`XUID:WM:CLOSED`)
and the app's exit (`INIT:LAUNCH:EXIT`). The judge wants every cycle
complete, the window count back to the baseline after each close (the
Terminal the image opens), and no failure marker.

    python tools/screenshot/wm_soak.py --write              # tools/screenshot/examples/wm_soak.json
    python tools/screenshot/wm_soak.py --write --cycles 50 --out shots/wm_soak50.json
    python tools/screenshot/qemu_session.py --image target/lazyos.img \\
        --out shots/wm_soak --script tools/screenshot/examples/wm_soak.json
    python tools/screenshot/wm_soak.py --judge shots/wm_soak/serial.log

The image: `LAZYOS_DESKTOP=1 LAZYOS_UI_PROBE=1 LAZYOS_XUI_AUTOSTART=term`.
Prints `WM:SOAK:PASS cycles=<n>` and exits 0 when the log passes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPT = ROOT / "tools/screenshot/examples/wm_soak.json"
CYCLES = 20
APP = "os.lazy.calc"
TITLE = "Calculator"
#: Windows open between cycles: the Terminal.
BASELINE = 1

#: Lines that fail the soak wherever they appear.
FORBIDDEN = ["XUID:SNAP:FAIL", "XUID:FOCUS:FAIL", "SHELL:MENU:FAIL", "SHELL:LINK:LOST",
             "INIT:RESTART:PASS name=xuid", "panicked"]


def setup() -> list[dict]:
    return [
        {"wait_for": "PKGD:PROVISION:DONE", "timeout": 420,
         "note": "generated by tools/screenshot/wm_soak.py; image: LAZYOS_DESKTOP=1 "
                 "LAZYOS_UI_PROBE=1 LAZYOS_XUI_AUTOSTART=term"},
        {"wait_for": "TERM:UP:PASS", "timeout": 240},
        {"wait_for": "XUID:WM:OPENED id=\\d+ windows=1 title=Terminal", "regex": True,
         "timeout": 60},
        {"wait": 1.5},
    ]


def cycle(n: int) -> list[dict]:
    """One open/close of the Calculator (`n` counts from 1)."""
    return [
        {"key": "super", "until": "SHELL:MENU:OPEN", "timeout": 20, "retries": 1},
        {"wait": 0.3},
        {"key": "down", "until": "SHELL:MENU:KEY:SELECT row=Accessories", "timeout": 3,
         "retries": 6},
        {"key": "right", "until": "SHELL:SUBMENU:OPEN category=accessories", "timeout": 10},
        {"key": "down", "until": f"SHELL:SUBMENU:KEY:SELECT row={TITLE}", "timeout": 3,
         "retries": 8},
        {"key": "enter", "until": f"XUID:WM:OPENED id=\\d+ windows={BASELINE + 1} title={TITLE}",
         "regex": True, "timeout": 60},
        {"wait_for": "CALC:UP:PASS", "occurrence": n, "timeout": 60},
        {"wait": 0.5},
        {"key_down": "alt"},
        {"wait": 0.1},
        {"key": "f4", "until": f"XUID:WM:CLOSED id=\\d+ windows={BASELINE} title={TITLE}",
         "regex": True, "timeout": 20},
        {"key_up": "alt"},
        {"wait_for": f"INIT:LAUNCH:EXIT app={APP}", "occurrence": n, "timeout": 30},
        {"wait": 0.3},
    ]


def session(cycles: int) -> list[dict]:
    steps = setup()
    for n in range(1, cycles + 1):
        steps += cycle(n)
        if n == 1:
            steps.append({"shot": "01_after_first_cycle"})
    steps += [{"wait": 1.0}, {"shot": "02_after_soak"}, {"quit": True}]
    return steps


def judge(log: str, cycles: int) -> list[str]:
    """Every failure in `log` for a soak of `cycles`; empty when it passed."""
    failures = []
    opened = re.findall(rf"XUID:WM:OPENED id=(\d+) windows=(\d+) title={TITLE}\r?$", log, re.M)
    closed = re.findall(rf"XUID:WM:CLOSED id=(\d+) windows=(\d+) title={TITLE}\r?$", log, re.M)
    exits = log.count(f"INIT:LAUNCH:EXIT app={APP}")
    if len(opened) != cycles:
        failures.append(f"{len(opened)} {TITLE} windows opened, expected {cycles}")
    if len(closed) != cycles:
        failures.append(f"{len(closed)} {TITLE} windows closed, expected {cycles}")
    if exits != cycles:
        failures.append(f"{exits} {APP} exits, expected {cycles}")
    if sorted(i for i, _ in opened) != sorted(i for i, _ in closed):
        failures.append("the closed windows are not the opened ones")
    if len({i for i, _ in opened}) != len(opened):
        failures.append("a surface id was reused")
    for _, count in opened:
        if int(count) != BASELINE + 1:
            failures.append(f"a {TITLE} window opened with {count} windows up")
    for _, count in closed:
        if int(count) != BASELINE:
            failures.append(f"{count} windows left after a close, expected {BASELINE}")
    for line in FORBIDDEN:
        if line in log:
            failures.append(f"{line!r} in the log")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cycles", type=int, default=CYCLES)
    parser.add_argument("--write", action="store_true", help="write the session script")
    parser.add_argument("--out", type=Path, default=SCRIPT)
    parser.add_argument("--judge", type=Path, help="judge this serial log")
    args = parser.parse_args()
    if args.write:
        args.out.write_text(json.dumps(session(args.cycles), indent=1) + "\n", encoding="utf-8")
        print(f"wrote {args.out} ({args.cycles} cycles)")
    if args.judge:
        log = args.judge.read_text(encoding="utf-8", errors="replace")
        failures = judge(log, args.cycles)
        for failure in failures:
            print(f"FAIL: {failure}")
        print(f"WM:SOAK:PASS cycles={args.cycles}" if not failures
              else f"WM:SOAK:FAIL {len(failures)} failure(s)")
        return 1 if failures else 0
    if not args.write:
        parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
