//! What lives on the FAT `/boot` volume: the kernel and `lazyos.cfg`. Every
//! other file is on the ext2 OS volume (`crate::bin`, `crate::etc`,
//! `crate::share`).

/// The volume configuration the bootloader hands the kernel (`root=`,
/// `home=`). Generated by the image build.
pub const LAZYOS_CFG: &str = "lazyos.cfg";

/// [`LAZYOS_CFG`] as the running system sees it: the FAT volume is mounted
/// read-only at `/boot`. Read by `xuid` (`diag.hold`) and `dbgd`
/// (`diag.dbg.*`).
pub const LAZYOS_CFG_PATH: &str = "/boot/lazyos.cfg";

/// The `argv[0]` BusyBox must be started under to treat its first argument as
/// an applet (`busybox sh -i`). BusyBox matches the program's base name
/// case-sensitively, so a caller that runs [`crate::bin::BUSYBOX`] sets it
/// explicitly rather than relying on the file name.
pub const BUSYBOX_ARGV0: &str = "busybox";
