//! Kernel build script: rasterize a real monospace font into an anti-aliased
//! glyph atlas and emit it as Rust source + a raw coverage blob in `OUT_DIR`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let font_path = manifest_dir.join("../assets/fonts/JetBrainsMono-Regular.ttf");

    println!("cargo:rerun-if-changed={}", font_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let font_bytes = fs::read(&font_path).expect("read JetBrainsMono-Regular.ttf");
    let atlas = font_atlas::build(&font_bytes, 20.0);

    fs::write(out_dir.join("font_atlas.bin"), &atlas.coverage).expect("write coverage blob");

    let mut src = String::new();
    src.push_str("// @generated by kernel/build.rs -- do not edit by hand.\n");
    src.push_str(&format!(
        "pub const FIRST_CHAR: u8 = {};\n",
        font_atlas::FIRST_CHAR
    ));
    src.push_str(&format!(
        "pub const LAST_CHAR: u8 = {};\n",
        font_atlas::LAST_CHAR
    ));
    src.push_str(&format!("pub const ASCENDER: i32 = {};\n", atlas.ascender));
    src.push_str(&format!(
        "pub const DESCENDER: i32 = {};\n",
        atlas.descender
    ));
    src.push_str(&format!(
        "pub const LINE_HEIGHT: i32 = {};\n",
        atlas.line_height
    ));
    src.push_str(&format!("pub const ADVANCE: u32 = {};\n", atlas.advance));
    src.push_str("pub const GLYPHS: &[Glyph] = &[\n");
    for g in &atlas.glyphs {
        src.push_str(&format!(
            "    Glyph {{ width: {}, height: {}, left: {}, top: {}, offset: {} }},\n",
            g.width, g.height, g.left, g.top, g.offset
        ));
    }
    src.push_str("];\n");
    src.push_str(
        "pub static COVERAGE: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/font_atlas.bin\"));\n",
    );

    fs::write(out_dir.join("font_atlas.rs"), src).expect("write generated atlas source");
}
