//! A Messenger *service* from an xui app: publish an endpoint under a name and
//! answer calls on it without blocking the UI loop.
//!
//! Native services (`user/src/bin/*`) block in `recv`; an xui app cannot,
//! because its event loop must keep painting. [`Server::poll`] therefore asks
//! the channel counters whether anything is queued first (instant, never
//! parks) and only then receives, so the app polls it from a UI timer for free.
//!
//! The registration is the same kernel op native services use
//! (`registry::register`, `REGISTRY_TARGET_SELF`): this task owns the name
//! until it exits, when the kernel reaps it. Request and reply bodies come
//! from the generated stubs of the service's interface; this module only
//! moves parcels and builds the envelope and the structured error field.

use libmessenger::{Encoder, Header, Parcel, VERSION};

use crate::sys::{self, errno, msg_op, MsgArgs, MsgResult, SenderId, EXPIRED_DEADLINE};

/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
pub use messenger_generated::errors::ERROR_FIELD;

/// One received call (or one-way message).
#[derive(Clone, Debug)]
pub struct Request {
    /// The sender's task slot, kernel-stamped.
    pub sender: u64,
    /// Who sent it (uid, gid, label, session), stamped by the kernel when the
    /// message was queued: what a service authorizes the caller by. Reading
    /// it needs no capability, unlike `cred_get` on [`Request::sender`].
    pub origin: SenderId,
    /// The transaction to answer, or `None` for a one-way message.
    pub txn: Option<u64>,
    pub parcel: Parcel,
}

/// A published service endpoint.
pub struct Server {
    /// The end this task receives calls on.
    endpoint: u64,
}

impl Server {
    /// Publish a fresh endpoint as `name`, implementing `interfaces` (with
    /// their names, `INTERFACE_NAME` of each generated module). Fails with
    /// the registry's errno (`-EEXIST` while a previous owner's name is still
    /// registered, `-EACCES` for an app serving outside its own domain);
    /// nothing stays open on failure.
    pub fn register(
        name: &str,
        interfaces: &[u64],
        interface_names: &[&str],
    ) -> Result<Server, i64> {
        let (published, endpoint) = sys::msg_create_pair()?;
        if let Err(code) = sys::msg_register(name, published, interfaces, interface_names) {
            let _ = close(published, 0);
            let _ = close(endpoint, 0);
            return Err(code);
        }
        Ok(Server { endpoint })
    }

    /// The next queued request, or `None` when nothing is waiting. Never
    /// parks when the queue is empty. A message too large for `buf` is
    /// dropped (`Err(-E2BIG)`); one that is not a parcel is skipped. Any
    /// channel or buffer the sender transferred is released.
    pub fn poll(&self, buf: &mut [u8]) -> Result<Option<Request>, i64> {
        Ok(self.receive(buf, false)?.map(|(request, _)| request))
    }

    /// [`Server::poll`] for a method that transfers a channel (the tray's
    /// `Set`): the first transferred channel end is kept and returned, and
    /// the caller must keep or close it. Buffers are still released.
    pub fn poll_keeping_channel(
        &self,
        buf: &mut [u8],
    ) -> Result<Option<(Request, Option<u64>)>, i64> {
        self.receive(buf, true)
    }

    fn receive(&self, buf: &mut [u8], keep: bool) -> Result<Option<(Request, Option<u64>)>, i64> {
        if sys::msg_queued(self.endpoint)? == 0 {
            return Ok(None);
        }
        let (result, origin) = match sys::msg_recv_from(self.endpoint, buf, EXPIRED_DEADLINE) {
            Ok(received) => received,
            Err(code) if code == -errno::ETIMEDOUT => return Ok(None),
            Err(code) => return Err(code),
        };
        let channel = release_transfers(&result, keep);
        let txn = (result.value != 0).then_some(result.value);
        let Ok(parcel) = Parcel::decode(&buf[..result.bytes as usize]) else {
            if let Some(handle) = channel {
                let _ = close(handle, msg_op::CLOSE_RELEASE);
            }
            // Answer a malformed call so its sender does not wait forever.
            if let Some(txn) = txn {
                let _ = self.reply(txn, &error_parcel(0, 0, errno::EINVAL, "bad parcel"));
            }
            return Ok(None);
        };
        let request = Request {
            sender: result.aux,
            origin,
            txn,
            parcel,
        };
        Ok(Some((request, channel)))
    }

    /// Park until a request is queued or the absolute PIT `deadline` passes
    /// (`0` waits forever), for a service with no UI loop to poll from
    /// (`printd`). Nothing is received: [`Server::poll`] takes it.
    pub fn wait(&self, deadline: u64) -> Result<(), i64> {
        match sys::msg_wait_any(&[self.endpoint], deadline) {
            Ok(_) => Ok(()),
            Err(code) if code == -errno::ETIMEDOUT => Ok(()),
            Err(code) => Err(code),
        }
    }

    /// Answer `txn`. A caller that gave up (deadline, cancel, exit) leaves no
    /// transaction and the kernel answers `-ENOENT`: an ordinary race, not an
    /// error of the service, so it is swallowed.
    pub fn reply(&self, txn: u64, reply: &Parcel) -> Result<(), i64> {
        match sys::msg_reply(txn, reply) {
            Err(code) if code == -errno::ENOENT => Ok(()),
            other => other,
        }
    }
}

/// A reply parcel for `interface`/`method` carrying `body`.
pub fn reply_parcel(interface: u64, method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: interface,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        handles: Vec::new(),
        buffers: Vec::new(),
    }
}

/// A failure reply: the structured error field with positive errno `code`
/// and a short friendly `message`.
pub fn error_parcel(interface: u64, method: u32, code: i64, message: &str) -> Parcel {
    let mut body = Encoder::new();
    // One bounded field into a fresh encoder cannot overflow.
    let _ = body.error(ERROR_FIELD, code.unsigned_abs() as u32, message);
    reply_parcel(interface, method, body.finish())
}

/// Close what a sender transferred with its message, unless `keep` asks for
/// the channel (returned): most protocols take no handle or buffer, and
/// keeping them would let any caller fill this task's tables. Only the first
/// of each is reported by the kernel, which is all a well-formed request could
/// carry anyway.
fn release_transfers(result: &MsgResult, keep: bool) -> Option<u64> {
    let mut kept = None;
    if result.reserved[1] > 0 {
        if keep {
            kept = Some(result.reserved[0]);
        } else {
            let _ = close(result.reserved[0], msg_op::CLOSE_RELEASE);
        }
    }
    if result.reserved[3] > 0 {
        let _ = sys::display_close_buffer(result.reserved[2]);
    }
    kept
}

/// `CLOSE_ENDPOINT` on `handle` with `flags`.
fn close(handle: u64, flags: u64) -> Result<(), i64> {
    let args = MsgArgs {
        handle,
        flags,
        ..MsgArgs::default()
    };
    let code = sys::messenger(
        msg_op::CLOSE_ENDPOINT,
        &args as *const MsgArgs as u64,
        &mut MsgResult::default() as *mut MsgResult as u64,
    );
    if code < 0 {
        Err(code)
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use libmessenger::{Decoder, Kind};

    #[test]
    fn an_error_reply_carries_the_positive_code_and_text() {
        let parcel = error_parcel(7, 3, -13, "denied");
        assert_eq!((parcel.header.interface_id, parcel.header.method), (7, 3));
        let mut decoder = Decoder::new(&parcel.body);
        let field = decoder.next().unwrap().unwrap();
        assert_eq!((field.kind, field.id), (Kind::Error, ERROR_FIELD));
        assert_eq!(field.error_parts().unwrap(), (13, "denied"));
    }
}
