//! A Messenger *service* from an xui app: publish an endpoint under a name and
//! answer calls on it without blocking the UI loop.
//!
//! Native services (`user/src/bin/*`) block in `recv`; an xui app cannot,
//! because its event loop must keep painting. [`Server::poll`] therefore asks
//! the channel counters whether anything is queued first (instant, never
//! parks) and only then receives, so the app polls it from a UI timer for free.
//!
//! The registration is the same kernel op native services use
//! (`registry::register`, `REGISTRY_TARGET_SELF`): this task owns the name
//! until it exits, when the kernel reaps it. Request and reply bodies come
//! from the generated stubs of the service's interface; this module only
//! moves parcels and builds the envelope and the structured error field.

use std::cell::RefCell;

use libmessenger::{Encoder, Header, Object, Parcel, VERSION};

use crate::sys::{self, errno, SenderId, EXPIRED_DEADLINE};

/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
pub use messenger_generated::errors::ERROR_FIELD;

/// One received call (or one-way message). It owns the objects the kernel
/// installed for it (a channel end moved here, a buffer shared with this
/// task) until a generated decoder claims them ([`Request::decode`]);
/// whatever is still unclaimed when it drops is closed, so a request a
/// service refuses or ignores leaves nothing in its handle table.
#[derive(Debug)]
pub struct Request {
    /// The sender's task slot, kernel-stamped.
    pub sender: u64,
    /// Who sent it (uid, gid, label, session), stamped by the kernel when the
    /// message was queued: what a service authorizes the caller by. Reading
    /// it needs no capability, unlike `cred_get` on [`Request::sender`].
    pub origin: SenderId,
    /// The transaction to answer, or `None` for a one-way message.
    pub txn: Option<u64>,
    /// The parcel; its own object list holds the sender's numbers.
    pub parcel: Parcel,
    /// The objects as installed in this task's table, in object-list order.
    objects: RefCell<Vec<Object>>,
}

impl Request {
    /// Decode the request with a generated `decode_<method>_args` that takes
    /// the installed objects. On success the decoded value owns every
    /// object; on failure the request keeps them and closes them on drop.
    pub fn decode<T>(
        &self,
        decoder: impl FnOnce(&[u8], &[Object]) -> Result<T, libmessenger::Error>,
    ) -> Result<T, libmessenger::Error> {
        let mut objects = self.objects.borrow_mut();
        let value = decoder(&self.parcel.body, &objects)?;
        objects.clear();
        Ok(value)
    }
}

impl Drop for Request {
    fn drop(&mut self) {
        for object in self.objects.get_mut().drain(..) {
            let _ = match object {
                Object::Channel(handle) => sys::msg_release(handle),
                Object::Buffer(handle) => sys::buffer_close(handle),
            };
        }
    }
}

/// A published service endpoint.
pub struct Server {
    /// The end this task receives calls on.
    endpoint: u64,
}

impl Server {
    /// Publish a fresh endpoint as `name`, implementing `interfaces` (with
    /// their names, `INTERFACE_NAME` of each generated module). Fails with
    /// the registry's errno (`-EEXIST` while a previous owner's name is still
    /// registered, `-EACCES` for an app serving outside its own domain);
    /// nothing stays open on failure.
    pub fn register(
        name: &str,
        interfaces: &[u64],
        interface_names: &[&str],
    ) -> Result<Server, i64> {
        let (published, endpoint) = sys::msg_create_pair()?;
        if let Err(code) = sys::msg_register(name, published, interfaces, interface_names) {
            let _ = sys::msg_close(published);
            let _ = sys::msg_close(endpoint);
            return Err(code);
        }
        Ok(Server { endpoint })
    }

    /// The next queued request, or `None` when nothing is waiting. Never
    /// parks when the queue is empty. A message too large for `buf` is
    /// dropped (`Err(-E2BIG)`); one that is not a parcel is skipped. The
    /// objects the sender's request carried are the request's
    /// ([`Request::decode`]).
    pub fn poll(&self, buf: &mut [u8]) -> Result<Option<Request>, i64> {
        if sys::msg_queued(self.endpoint)? == 0 {
            return Ok(None);
        }
        let (result, origin) = match sys::msg_recv_from(self.endpoint, buf, EXPIRED_DEADLINE) {
            Ok(received) => received,
            Err(code) if code == -errno::ETIMEDOUT => return Ok(None),
            Err(code) => return Err(code),
        };
        let txn = (result.value != 0).then_some(result.value);
        let installed = result.delivered();
        let parcel = match Parcel::decode(&buf[..result.bytes as usize]) {
            // The kernel installs exactly the list it validated.
            Ok(parcel) if parcel.objects.len() == installed.len() => parcel,
            _ => {
                for &handle in installed {
                    let _ = sys::msg_release(handle);
                }
                // Answer a malformed call so its sender does not wait forever.
                if let Some(txn) = txn {
                    let _ = self.reply(txn, &error_parcel(0, 0, errno::EINVAL, "bad parcel"));
                }
                return Ok(None);
            }
        };
        let objects = parcel
            .objects
            .iter()
            .zip(installed)
            .map(|(object, &handle)| object.with_handle(handle))
            .collect();
        Ok(Some(Request {
            sender: result.aux,
            origin,
            txn,
            parcel,
            objects: RefCell::new(objects),
        }))
    }

    /// Park until a request is queued or the absolute PIT `deadline` passes
    /// (`0` waits forever), for a service with no UI loop to poll from
    /// (`printd`). Nothing is received: [`Server::poll`] takes it.
    pub fn wait(&self, deadline: u64) -> Result<(), i64> {
        match sys::msg_wait_any(&[self.endpoint], deadline) {
            Ok(_) => Ok(()),
            Err(code) if code == -errno::ETIMEDOUT => Ok(()),
            Err(code) => Err(code),
        }
    }

    /// Answer `txn`. A caller that gave up (deadline, cancel, exit) leaves no
    /// transaction and the kernel answers `-ENOENT`: an ordinary race, not an
    /// error of the service, so it is swallowed.
    pub fn reply(&self, txn: u64, reply: &Parcel) -> Result<(), i64> {
        match sys::msg_reply(txn, reply) {
            Err(code) if code == -errno::ENOENT => Ok(()),
            other => other,
        }
    }
}

/// A reply parcel for `interface`/`method` carrying `body`.
pub fn reply_parcel(interface: u64, method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: interface,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        objects: Vec::new(),
    }
}

/// A failure reply: the structured error field with positive errno `code`
/// and a short friendly `message`.
pub fn error_parcel(interface: u64, method: u32, code: i64, message: &str) -> Parcel {
    let mut body = Encoder::new();
    // One bounded field into a fresh encoder cannot overflow.
    let _ = body.error(ERROR_FIELD, code.unsigned_abs() as u32, message);
    reply_parcel(interface, method, body.finish())
}

#[cfg(test)]
mod tests {
    use super::*;
    use libmessenger::{Decoder, Kind};

    #[test]
    fn an_error_reply_carries_the_positive_code_and_text() {
        let parcel = error_parcel(7, 3, -13, "denied");
        assert_eq!((parcel.header.interface_id, parcel.header.method), (7, 3));
        let mut decoder = Decoder::new(&parcel.body);
        let field = decoder.next().unwrap().unwrap();
        assert_eq!((field.kind, field.id), (Kind::Error, ERROR_FIELD));
        assert_eq!(field.error_parts().unwrap(), (13, "denied"));
    }
}
