#!/usr/bin/env python3
"""Extract the EAPOL-Key frames of a WPA handshake from a pcap, standard library only.

Used once to build `libs/eapol/src/tests/capture.rs` from Wireshark's sample
capture `wpa-Induction.pcap` (SSID "Coherer", passphrase "Induction"; GPL-2.0-or-later,
test data only). The capture is untrusted input: this is a small reader of the pcap
container, radiotap, 802.11 data frames and LLC/SNAP written for the purpose; it executes
nothing from the file and bounds every read. Run it with `python -I` from a directory
that holds no other Python files:

    python -I tools/wifi/extract_capture_vectors.py PATH/wpa-Induction.pcap          # print
    python -I tools/wifi/extract_capture_vectors.py PATH/wpa-Induction.pcap --write  # rewrite the fixture
    python -I tools/wifi/extract_capture_vectors.py PATH/wpa-Induction.pcap --check  # compare with the fixture

`--check` and `--write` skip with exit 0 (and say so) when PATH does not exist, so CI never
depends on the download. The capture itself is never committed.
"""
import hashlib
import struct
import sys
from pathlib import Path

FIXTURE = Path(__file__).resolve().parents[2] / "libs" / "eapol" / "src" / "tests" / "capture.rs"
SOURCE = "https://wiki.wireshark.org/SampleCaptures (attachment wpa-Induction.pcap)"
PASSPHRASE = "Induction"
SSID = "Coherer"
LINK_80211, LINK_RADIOTAP = 105, 127


def packets(data):
    """Yield (linktype, packet bytes) from a classic pcap, little or big endian."""
    magic = data[:4]
    if magic in (b"\xd4\xc3\xb2\xa1", b"\x4d\x3c\xb2\xa1"):
        end = "<"
    elif magic in (b"\xa1\xb2\xc3\xd4", b"\xa1\xb2\x3c\x4d"):
        end = ">"
    else:
        raise SystemExit("not a classic pcap file")
    link = struct.unpack(end + "I", data[20:24])[0]
    at = 24
    while at + 16 <= len(data):
        incl = struct.unpack(end + "I", data[at + 8:at + 12])[0]
        at += 16
        if incl > len(data) - at:
            break
        yield link, data[at:at + incl]
        at += incl


def dot11(link, pkt):
    """The 802.11 frame inside the link layer (radiotap header skipped), or None."""
    if link == LINK_RADIOTAP:
        if len(pkt) < 4:
            return None
        length = struct.unpack("<H", pkt[2:4])[0]
        return pkt[length:] if length <= len(pkt) else None
    return pkt if link == LINK_80211 else None


def eapol_of(frame):
    """(sa, da, bssid, eapol bytes) when `frame` is an unencrypted data frame carrying EAPOL."""
    if len(frame) < 24 or frame[0] & 0x0C != 0x08:  # not a data frame
        return None
    subtype, flags = frame[0] >> 4, frame[1]
    if flags & 0x40:  # protected
        return None
    a1, a2, a3 = frame[4:10], frame[10:16], frame[16:22]
    to_ds, from_ds = flags & 1, flags >> 1 & 1
    if (to_ds, from_ds) == (1, 0):
        bssid, sa, da = a1, a2, a3
    elif (to_ds, from_ds) == (0, 1):
        da, bssid, sa = a1, a2, a3
    else:
        return None
    at = 24 + (2 if subtype & 8 else 0) + (4 if flags & 0x80 and subtype & 8 else 0)
    if frame[at:at + 8] != bytes.fromhex("aaaa03000000888e"):
        return None
    pdu = frame[at + 8:]
    if len(pdu) < 4 or pdu[1] != 3:
        return None
    total = 4 + struct.unpack(">H", pdu[2:4])[0]
    return sa, da, bssid, pdu[:total] if total <= len(pdu) else None


def exchange(path):
    data = Path(path).read_bytes()
    found = []
    for link, pkt in packets(data):
        frame = dot11(link, pkt)
        got = eapol_of(frame) if frame else None
        if got and got[3]:
            found.append(got)
    return hashlib.sha256(data).hexdigest(), found


def classify(pdu):
    info = struct.unpack(">H", pdu[5:7])[0]
    pairwise, ack, mic, secure = info >> 3 & 1, info >> 7 & 1, info >> 8 & 1, info >> 9 & 1
    if pairwise and ack and not mic:
        return "msg1"
    if pairwise and not ack and mic and not secure:
        return "msg2"
    if pairwise and ack and mic:
        return "msg3"
    if pairwise and not ack and mic and secure:
        return "msg4"
    return "group1" if not pairwise and ack else "group2" if not pairwise else "other"


def first_handshake(found):
    """Messages 1-4 of the first complete handshake, by key-info classification."""
    wanted, out = ["msg1", "msg2", "msg3", "msg4"], {}
    for sa, da, bssid, pdu in found:
        kind = classify(pdu)
        if kind == wanted[len(out)]:
            out[kind] = (sa, da, bssid, pdu)
        elif kind == "msg1":
            out = {"msg1": (sa, da, bssid, pdu)}
    return out if len(out) == 4 else None


def render(sha, hs):
    ap = hs["msg1"][0]
    sta = hs["msg1"][1]
    lines = [
        "// @generated by tools/wifi/extract_capture_vectors.py: do not edit.",
        "//! Test data from a real capture. Source: " + SOURCE + ".",
        "//! File: wpa-Induction.pcap, SHA-256 " + sha + ".",
        "//! Licence: GPL-2.0-or-later (Wireshark sample captures), test data only, not in the OS image.",
        "//! SSID and passphrase are the capture's documented ones. The pcap itself is not in the tree.",
        "",
        f'pub const SSID: &str = "{SSID}";',
        f'pub const PASSPHRASE: &str = "{PASSPHRASE}";',
        f'pub const AP: &str = "{ap.hex()}";',
        f'pub const STA: &str = "{sta.hex()}";',
    ]
    for name in ("msg1", "msg2", "msg3", "msg4"):
        lines.append(f'pub const {name.upper()}: &str = "{hs[name][3].hex()}";')
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) < 2:
        raise SystemExit(__doc__)
    path, mode = argv[1], (argv[2] if len(argv) > 2 else "--print")
    if mode in ("--check", "--write") and not Path(path).exists():
        print(f"{path} not present: skipping")
        return 0
    sha, found = exchange(path)
    print(f"sha256 {sha}; {len(found)} EAPOL frames: " + " ".join(classify(f[3]) for f in found))
    hs = first_handshake(found)
    if hs is None:
        raise SystemExit("no complete 4-way handshake found")
    text = render(sha, hs).encode()
    if mode == "--write":
        FIXTURE.write_bytes(text)
        print(f"wrote {FIXTURE}")
    elif mode == "--check":
        have = FIXTURE.read_bytes().replace(b"\r\n", b"\n") if FIXTURE.exists() else None
        if have != text:
            print(f"stale: {FIXTURE}")
            return 1
        print("capture fixture is current")
    else:
        print(text.decode())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
