#!/usr/bin/env python3
"""Count what an idle LazyOS desktop wakes up for (docs/performance-plan.md P7).

Builds the desktop with the kernel's perf instrumentation
(`LAZYOS_DESKTOP=1 LAZYOS_PERF=1 cargo build`), boots it headless, touches
nothing, and reads the kernel's `PERF:sched` lines: cumulative per-slot wakes
(blocked -> runnable) and runs (the scheduler switched to the task), printed
every 2 s (`kernel/src/perf/wakeups.rs`). The rates are the difference between
the first line at or after `--settle` seconds of guest time and the last one,
over at least `--window` seconds, divided by the guest ticks between them.

    python tools/perf/idle.py                       # build, boot, measure
    python tools/perf/idle.py --no-build --window 60
    python tools/perf/idle.py --max-switches 10     # exit 1 above the P7 target

Writes `docs/perf/idle.md` (+ `idle.json`) unless `--no-report`.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "tools" / "screenshot"))
from qemu_qmp import (  # noqa: E402
    DEFAULT_MEMORY, accel_args, build_qemu_command, find_qemu, free_port, resolve_accel,
)

REPORT_DIR = ROOT / "docs" / "perf"
TICK_HZ = 100
RE_SCHED = re.compile(r"^PERF:sched:tick=(\d+) idle=(\d+)(.*)$")
RE_ENTRY = re.compile(r"(\S+)#(\d+)=(\d+)/(\d+)")


def build_image() -> Path:
    # The desktop session logged straight in, as before there was a login (#623).
    env = dict(os.environ, LAZYOS_DESKTOP="1", LAZYOS_PERF="1", LAZYOS_AUTOLOGIN="user")
    print("building xui apps: python tools/xui/build.py", flush=True)
    subprocess.run([sys.executable, str(ROOT / "tools" / "xui" / "build.py")], cwd=ROOT, check=True)
    print("building: LAZYOS_DESKTOP=1 LAZYOS_PERF=1 cargo build", flush=True)
    result = subprocess.run(["cargo", "build"], cwd=ROOT, env=env, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"cargo build failed:\n{result.stderr[-4000:]}")
    return ROOT / "target" / "lazyos.img"


def parse_lines(text: str) -> list[tuple[int, int, dict[int, tuple[str, int, int]]]]:
    """Every `PERF:sched` line as (tick, idle ticks, {slot: (name, wakes, runs)})."""
    lines = []
    for raw in text.splitlines():
        match = RE_SCHED.match(raw.strip())
        if not match:
            continue
        slots = {
            int(slot): (name, int(wakes), int(runs))
            for name, slot, wakes, runs in RE_ENTRY.findall(match.group(3))
        }
        lines.append((int(match.group(1)), int(match.group(2)), slots))
    return lines


def rates(first, last) -> dict:
    """Per-task wake and switch rates between two `PERF:sched` lines."""
    ticks = last[0] - first[0]
    seconds = ticks / TICK_HZ
    rows = []
    for slot, (name, wakes, runs) in sorted(last[2].items()):
        before = first[2].get(slot)
        if before is None or before[0] != name:
            # The slot was (re)used inside the window: count it whole.
            before = (name, 0, 0)
        dw, dr = wakes - before[1], runs - before[2]
        if dw or dr:
            rows.append({"slot": slot, "name": name, "wakes_per_s": dw / seconds,
                         "switches_per_s": dr / seconds, "wakes": dw, "switches": dr})
    rows.sort(key=lambda row: (-row["switches_per_s"], -row["wakes_per_s"]))
    return {
        "window_s": seconds,
        "idle_fraction": (last[1] - first[1]) / ticks if ticks else 0.0,
        "switches_per_s": sum(row["switches"] for row in rows) / seconds,
        "wakes_per_s": sum(row["wakes"] for row in rows) / seconds,
        "tasks": rows,
    }


def wait_for_tick(serial: Path, proc: subprocess.Popen, tick: int, timeout: float) -> str:
    """The serial text once a `PERF:sched` line at or past `tick` is in it."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        text = serial.read_text(errors="replace") if serial.is_file() else ""
        lines = parse_lines(text)
        if lines and lines[-1][0] >= tick:
            return text
        if "PANIC" in text or proc.poll() is not None:
            break
        time.sleep(0.5)
    return serial.read_text(errors="replace") if serial.is_file() else ""


def write_report(payload: dict) -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    (REPORT_DIR / "idle.json").write_text(json.dumps(payload, indent=2) + "\n")
    meta, result = payload["meta"], payload["result"]
    lines = [
        "# Idle desktop wakeups",
        "",
        f"Generated by `tools/perf/idle.py` on {meta['generated']} (commit `{meta['commit']}`,"
        f" {meta['accel']}, guest window {result['window_s']:.0f} s after {meta['settle_s']} s).",
        "",
        f"**{result['switches_per_s']:.1f} context switches/s**, {result['wakes_per_s']:.1f} wakes/s,"
        f" CPU idle {result['idle_fraction'] * 100:.1f}% of ticks.",
        "",
        "| Task | Slot | Switches/s | Wakes/s |",
        "|---|---:|---:|---:|",
    ]
    for row in result["tasks"]:
        lines.append(f"| `{row['name']}` | {row['slot']} | {row['switches_per_s']:.2f} | {row['wakes_per_s']:.2f} |")
    path = REPORT_DIR / "idle.md"
    path.write_text("\n".join(lines) + "\n")
    return path


def git_commit() -> str:
    result = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True)
    return result.stdout.strip() or "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--image", default=str(ROOT / "target" / "lazyos.img"))
    parser.add_argument("--out", default="shots/idle", help="output dir (serial.log)")
    parser.add_argument("--qemu", help="path to qemu-system-x86_64")
    parser.add_argument("--accel", default="auto", choices=["auto", "none", "tcg", "whpx", "kvm"])
    parser.add_argument("--memory", default=DEFAULT_MEMORY)
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument("--settle", type=float, default=30.0,
                        help="guest seconds before the window opens (boot, autostart, the in-kernel benches)")
    parser.add_argument("--window", type=float, default=30.0, help="guest seconds measured")
    parser.add_argument("--timeout", type=float, default=300.0, help="host seconds for the whole run")
    parser.add_argument("--max-switches", type=float, help="fail above this many switches per second")
    parser.add_argument("--no-report", action="store_true", help="do not write docs/perf/idle.md")
    args = parser.parse_args()

    image = Path(args.image) if args.no_build else build_image()
    qemu = find_qemu(args.qemu)
    out = (ROOT / args.out) if not Path(args.out).is_absolute() else Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    serial = out / "serial.log"
    serial.unlink(missing_ok=True)
    accel = resolve_accel(args.accel, qemu)
    command = build_qemu_command(qemu, str(image), free_port(), serial, memory=args.memory,
                                 extra_args=accel_args(args.accel, qemu))
    print(f"booting ({accel}), idle for {args.settle + args.window:.0f} guest seconds", flush=True)
    proc = subprocess.Popen(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        end_tick = int((args.settle + args.window) * TICK_HZ)
        text = wait_for_tick(serial, proc, end_tick, args.timeout)
    finally:
        proc.kill()
        proc.wait(timeout=15)

    lines = parse_lines(text)
    window = [line for line in lines if line[0] >= args.settle * TICK_HZ]
    if len(window) < 2 or window[-1][0] - window[0][0] < args.window * TICK_HZ * 0.9:
        print(text[-3000:])
        print("FAIL: not enough PERF:sched lines (is this a LAZYOS_PERF=1 image?)", file=sys.stderr)
        return 1
    result = rates(window[0], window[-1])
    print(f"{result['switches_per_s']:.1f} switches/s, {result['wakes_per_s']:.1f} wakes/s over"
          f" {result['window_s']:.0f} s (idle {result['idle_fraction'] * 100:.1f}%)")
    for row in result["tasks"]:
        print(f"  {row['name']:>24}#{row['slot']:<3} switches/s {row['switches_per_s']:7.2f}"
              f"  wakes/s {row['wakes_per_s']:7.2f}")
    if not args.no_report:
        payload = {
            "meta": {
                "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "commit": git_commit(),
                "accel": accel,
                "settle_s": args.settle,
            },
            "result": result,
        }
        print(f"report: {write_report(payload).relative_to(ROOT)}")
    if args.max_switches is not None and result["switches_per_s"] > args.max_switches:
        print(f"FAIL: {result['switches_per_s']:.1f} switches/s > {args.max_switches}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
