// @generated by tools/midlc/midlc.py - do not edit.
// Regenerate with:
//   python tools/midlc/midlc.py --rhai-api libs/rhai-lazy/api idl/*.midl
//
// The generated Rhai API modules (`sys::<alias>`), embedded by
// `libs/rhai-lazy/src/msg/api.rs`.
#[rustfmt::skip]
pub static MODULES: &[ApiModule] = &[
    ApiModule {
        alias: "accounts",
        interface: "os.lazy.accounts.v1",
        source: include_str!("accounts.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "audio",
        interface: "os.lazy.audio.v1",
        source: include_str!("audio.rhai"),
        topics: &[ApiTopic { helper: "event", pattern: "system/audio/+/event" }],
    },
    ApiModule {
        alias: "audio_mixer",
        interface: "os.lazy.audio.mixer.v1",
        source: include_str!("audio_mixer.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "clipboard",
        interface: "os.lazy.clipboard.v1",
        source: include_str!("clipboard.rhai"),
        topics: &[ApiTopic { helper: "session_changed", pattern: "session/+/clipboard/changed" }, ApiTopic { helper: "paste", pattern: "system/events/clipboard/paste" }, ApiTopic { helper: "security", pattern: "system/events/security/clipboard" }],
    },
    ApiModule {
        alias: "confd",
        interface: "os.lazy.confd.v1",
        source: include_str!("confd.rhai"),
        topics: &[ApiTopic { helper: "changed", pattern: "system/confd/changed/#" }],
    },
    ApiModule {
        alias: "display",
        interface: "os.lazy.display.v1",
        source: include_str!("display.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "echo",
        interface: "os.lazy.echo.v1",
        source: include_str!("echo.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "files",
        interface: "os.lazy.files.v1",
        source: include_str!("files.rhai"),
        topics: &[ApiTopic { helper: "session_selection", pattern: "session/+/selection" }],
    },
    ApiModule {
        alias: "healthd",
        interface: "os.lazy.healthd.v1",
        source: include_str!("healthd.rhai"),
        topics: &[ApiTopic { helper: "summary", pattern: "system/health/summary" }, ApiTopic { helper: "health", pattern: "system/health/+" }],
    },
    ApiModule {
        alias: "init",
        interface: "os.lazy.init.v1",
        source: include_str!("init.rhai"),
        topics: &[ApiTopic { helper: "power_state", pattern: "system/power/state" }, ApiTopic { helper: "service", pattern: "system/events/service/+" }, ApiTopic { helper: "app", pattern: "system/events/app/+" }],
    },
    ApiModule {
        alias: "input",
        interface: "os.lazy.input.v1",
        source: include_str!("input.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "input_shell",
        interface: "os.lazy.input.shell.v1",
        source: include_str!("input_shell.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "keyd",
        interface: "os.lazy.keyd.v1",
        source: include_str!("keyd.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "lifecycle",
        interface: "os.lazy.lifecycle.v1",
        source: include_str!("lifecycle.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "logd",
        interface: "os.lazy.logd.v1",
        source: include_str!("logd.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "logind",
        interface: "os.lazy.logind.v1",
        source: include_str!("logind.rhai"),
        topics: &[ApiTopic { helper: "start", pattern: "system/events/login/start" }, ApiTopic { helper: "session", pattern: "system/events/login/session/+" }, ApiTopic { helper: "denied", pattern: "system/events/login/denied" }, ApiTopic { helper: "end", pattern: "system/events/login/end" }],
    },
    ApiModule {
        alias: "mimed",
        interface: "os.lazy.mimed.v1",
        source: include_str!("mimed.rhai"),
        topics: &[ApiTopic { helper: "open", pattern: "system/events/open/+" }],
    },
    ApiModule {
        alias: "net_nic",
        interface: "os.lazy.net.nic.v1",
        source: include_str!("net_nic.rhai"),
        topics: &[ApiTopic { helper: "link", pattern: "system/net/+/link" }],
    },
    ApiModule {
        alias: "net_stack",
        interface: "os.lazy.net.stack.v1",
        source: include_str!("net_stack.rhai"),
        topics: &[ApiTopic { helper: "addr", pattern: "system/net/+/addr" }, ApiTopic { helper: "network_up", pattern: "system/events/network/up" }],
    },
    ApiModule {
        alias: "net_socket",
        interface: "os.lazy.net.socket.v1",
        source: include_str!("net_socket.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "pkgd",
        interface: "os.lazy.pkgd.v1",
        source: include_str!("pkgd.rhai"),
        topics: &[ApiTopic { helper: "pkg", pattern: "system/events/pkg/+" }],
    },
    ApiModule {
        alias: "print",
        interface: "os.lazy.print.v1",
        source: include_str!("print.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "messenger_registry",
        interface: "os.lazy.messenger.registry.v1",
        source: include_str!("messenger_registry.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "shell",
        interface: "os.lazy.shell.v1",
        source: include_str!("shell.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "sysmond",
        interface: "os.lazy.sysmond.v1",
        source: include_str!("sysmond.rhai"),
        topics: &[ApiTopic { helper: "stats_memory", pattern: "system/stats/memory" }, ApiTopic { helper: "stats_tasks", pattern: "system/stats/tasks" }],
    },
    ApiModule {
        alias: "timed",
        interface: "os.lazy.timed.v1",
        source: include_str!("timed.rhai"),
        topics: &[ApiTopic { helper: "tick", pattern: "time/tick" }],
    },
    ApiModule {
        alias: "messenger_topics",
        interface: "os.lazy.messenger.topics.v1",
        source: include_str!("messenger_topics.rhai"),
        topics: &[],
    },
    ApiModule {
        alias: "messenger_topics_bell",
        interface: "os.lazy.messenger.topics.bell.v1",
        source: include_str!("messenger_topics_bell.rhai"),
        topics: &[],
    },
];
