//! `LAZYOS_LIMIT_*` -> `limit.*` lines in `lazyos.cfg` (build_support/limits_cfg.rs).

use crate::os_image::{boot_cfg, limits_cfg};

#[test]
fn accepts_sizes_and_counts() {
    for (key, value) in [
        ("heap_max", "512M"),
        ("heap_max", "1g"),
        ("stack_size", "65536"),
        ("shared_buffer_max", "2T"),
        ("fd_max", "4096"),
    ] {
        assert_eq!(limits_cfg::validate(key, value), Ok(()), "{key}={value}");
    }
}

#[test]
fn refuses_malformed_values() {
    for (key, value) in [
        ("heap_max", ""),
        ("heap_max", "M"),
        ("heap_max", "-1"),
        ("heap_max", "1.5G"),
        ("heap_max", "0x10"),
        ("heap_max", "12Q"),
        ("heap_max", "99999999999999999999"),
        ("fd_max", "1M"),
        ("fd_max", "+4"),
    ] {
        let error = limits_cfg::validate(key, value).expect_err(value);
        assert!(error.contains(&limits_cfg::env_name(key)), "{error}");
    }
}

#[test]
fn every_kernel_key_has_a_variable() {
    assert_eq!(limits_cfg::env_name("heap_max"), "LAZYOS_LIMIT_HEAP_MAX");
    assert_eq!(limits_cfg::KEYS.len(), 6);
}

#[test]
fn boot_cfg_carries_the_limits_after_the_volumes() {
    let limits = vec![
        ("heap_max".to_string(), "512M".to_string()),
        ("fd_max".to_string(), "4096".to_string()),
    ];
    let text = boot_cfg([0x11; 16], &limits);
    assert!(
        text.starts_with("# Generated by the image build.\nroot=UUID="),
        "{text}"
    );
    assert!(
        text.ends_with("home=LABEL=lazyhome\nlimit.heap_max=512M\nlimit.fd_max=4096\n"),
        "{text}"
    );
    assert!(!boot_cfg([0x11; 16], &[]).contains("limit."));
}
