//! `LAZYOS_LIMIT_*` -> `limit.*` lines in `lazyos.cfg` (build_support/limits_cfg.rs).

use crate::os_image::{boot_cfg, limits_cfg};

#[test]
fn accepts_sizes_and_counts() {
    for (key, value) in [
        ("heap_max", "512M"),
        ("heap_max", "1g"),
        ("stack_size", "65536"),
        ("shared_buffer_max", "2T"),
        ("fd_max", "4096"),
    ] {
        assert_eq!(limits_cfg::validate(key, value), Ok(()), "{key}={value}");
    }
}

#[test]
fn refuses_malformed_values() {
    for (key, value) in [
        ("heap_max", ""),
        ("heap_max", "M"),
        ("heap_max", "-1"),
        ("heap_max", "1.5G"),
        ("heap_max", "0x10"),
        ("heap_max", "12Q"),
        ("heap_max", "99999999999999999999"),
        ("fd_max", "1M"),
        ("fd_max", "+4"),
    ] {
        let error = limits_cfg::validate(key, value).expect_err(value);
        assert!(error.contains(&limits_cfg::env_name(key)), "{error}");
    }
}

#[test]
fn every_kernel_key_has_a_variable() {
    assert_eq!(limits_cfg::env_name("heap_max"), "LAZYOS_LIMIT_HEAP_MAX");
    assert_eq!(limits_cfg::KEYS.len(), 6);
}

#[test]
fn boot_cfg_carries_the_limits_after_the_volumes() {
    let limits = vec![
        ("heap_max".to_string(), "512M".to_string()),
        ("fd_max".to_string(), "4096".to_string()),
    ];
    let text = boot_cfg([0x11; 16], &limits);
    assert!(
        text.starts_with("# Generated by the image build.\nroot=UUID="),
        "{text}"
    );
    assert!(
        text.ends_with("home=LABEL=lazyhome\nlimit.heap_max=512M\nlimit.fd_max=4096\n"),
        "{text}"
    );
    assert!(!boot_cfg([0x11; 16], &[]).contains("limit."));
}

#[test]
fn display_mode_and_scale_lines() {
    use crate::os_image::display_cfg;
    for mode in ["2560x1440", "1280x720", "640x480", "3840X2160"] {
        assert_eq!(display_cfg::validate_mode(mode), Ok(()), "{mode}");
    }
    for mode in [
        "",
        "2560",
        "2560x",
        "x1440",
        "4000x2000",
        "639x480",
        "-1x5",
        "2560x1440x2",
        "99999999x1",
    ] {
        let error = display_cfg::validate_mode(mode).expect_err(mode);
        assert!(error.contains("LAZYOS_DISPLAY_MODE"), "{error}");
    }
    for scale in ["auto", "1", "2"] {
        assert_eq!(display_cfg::validate_scale(scale), Ok(()));
    }
    for scale in ["0", "3", "1.5", "AUTO "] {
        assert!(display_cfg::validate_scale(scale).is_err(), "{scale}");
    }
    assert_eq!(display_cfg::lines(None, None), "");
    assert_eq!(
        display_cfg::lines(Some("2560x1440"), Some("2")),
        "display.mode=2560x1440\ndisplay.scale=2\n"
    );
}

#[test]
fn diag_hold_line_only_for_a_positive_number_and_is_clamped() {
    use crate::os_image::diag_hold_line;
    assert_eq!(diag_hold_line(Some("45")), "diag.hold=45\n");
    assert_eq!(diag_hold_line(Some(" 30 ")), "diag.hold=30\n");
    assert_eq!(diag_hold_line(Some("100000")), "diag.hold=600\n");
    for none in [None, Some(""), Some("0"), Some("-5"), Some("soon"), Some("1.5")] {
        assert_eq!(diag_hold_line(none), "", "{none:?}");
    }
}
