#!/usr/bin/env python3
"""Summarise Linux-ABI syscall coverage from bench serial logs.

The kernel logs unimplemented syscalls as `ENOSYS <nr> <name>` to serial. This
tool scans the logs under `shots/abi/` (or paths given on the command line) and
writes `docs/compat/coverage.md` + `coverage.json` listing what was observed.

Until the Linux syscall dispatch exists the report is empty — the plumbing is
here so gaps surface automatically once it does.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
COMPAT = ROOT / "docs" / "compat"
ENOSYS = re.compile(r"ENOSYS\s+(\d+)(?:\s+(\S+))?")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="serial logs (default: shots/abi/*/serial.log)")
    args = parser.parse_args()

    if args.paths:
        logs = [Path(p) for p in args.paths]
    else:
        logs = sorted((ROOT / "shots" / "abi").glob("*/serial.log"))

    missing: Counter[tuple[int, str]] = Counter()
    for log in logs:
        if not log.is_file():
            continue
        for match in ENOSYS.finditer(log.read_text(errors="replace")):
            number = int(match.group(1))
            name = match.group(2) or f"syscall_{number}"
            missing[(number, name)] += 1

    COMPAT.mkdir(parents=True, exist_ok=True)
    report = [{"nr": nr, "name": name, "count": count} for (nr, name), count in sorted(missing.items())]
    (COMPAT / "coverage.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Linux ABI syscall coverage",
        "",
        "_Generated by `tools/abi/coverage.py` from bench serial logs._",
        "",
        f"Unimplemented syscalls observed: **{len(report)}**",
        "",
    ]
    if report:
        lines += ["| nr | name | hits |", "|---|---|---|"]
        lines += [f"| {r['nr']} | {r['name']} | {r['count']} |" for r in report]
    else:
        lines.append("None observed yet (no Linux syscalls dispatched so far).")
    (COMPAT / "coverage.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"coverage: {len(report)} unimplemented syscalls observed across {len(logs)} logs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
