#!/usr/bin/env python3
"""Summarise Linux-ABI syscall coverage from bench serial logs.

The kernel logs:
  * `SYSCALL_USED <nr> <name>` the first time it dispatches a syscall, and
  * `ENOSYS <nr> <name>` whenever a syscall is unimplemented.

This tool scans the logs under `shots/abi/` (or paths given on the command line)
and writes `docs/compat/coverage.md` + `coverage.json` listing what each fixture
needed and which gaps it hit.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
COMPAT = ROOT / "docs" / "compat"
USED = re.compile(r"SYSCALL_USED\s+(\d+)(?:\s+(\S+))?")
ENOSYS = re.compile(r"ENOSYS\s+(\d+)(?:\s+(\S+))?")


def collect(pattern: re.Pattern[str], text: str) -> Counter[tuple[int, str]]:
    found: Counter[tuple[int, str]] = Counter()
    for match in pattern.finditer(text):
        number = int(match.group(1))
        name = match.group(2) or f"syscall_{number}"
        found[(number, name)] += 1
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="serial logs (default: shots/abi/*/serial.log)")
    args = parser.parse_args()

    if args.paths:
        logs = [Path(p) for p in args.paths]
    else:
        logs = sorted((ROOT / "shots" / "abi").glob("*/serial.log"))

    used: Counter[tuple[int, str]] = Counter()
    missing: Counter[tuple[int, str]] = Counter()
    for log in logs:
        if not log.is_file():
            continue
        text = log.read_text(errors="replace")
        used += collect(USED, text)
        missing += collect(ENOSYS, text)

    implemented = {key: count for key, count in used.items() if key not in missing}
    COMPAT.mkdir(parents=True, exist_ok=True)
    report = {
        "implemented": [
            {"nr": nr, "name": name, "count": count}
            for (nr, name), count in sorted(implemented.items())
        ],
        "missing": [
            {"nr": nr, "name": name, "count": count}
            for (nr, name), count in sorted(missing.items())
        ],
    }
    (COMPAT / "coverage.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Linux ABI syscall coverage",
        "",
        "_Generated by `tools/abi/coverage.py` from bench serial logs._",
        "",
        f"Syscalls exercised: **{len(used)}** | implemented: **{len(implemented)}** | "
        f"unimplemented: **{len(missing)}**",
        "",
    ]
    if implemented:
        lines += ["## Implemented (exercised by the fixtures)", "", "| nr | name | hits |", "|---|---|---|"]
        lines += [f"| {nr} | {name} | {count} |" for (nr, name), count in sorted(implemented.items())]
        lines.append("")
    lines += ["## Unimplemented (returned `-ENOSYS`)", ""]
    if missing:
        lines += ["| nr | name | hits |", "|---|---|---|"]
        lines += [f"| {nr} | {name} | {count} |" for (nr, name), count in sorted(missing.items())]
    else:
        lines.append("None - every syscall the fixtures exercised is implemented.")
    (COMPAT / "coverage.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"coverage: {len(used)} exercised, {len(implemented)} implemented, "
        f"{len(missing)} unimplemented across {len(logs)} logs"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
