#!/usr/bin/env python3
"""Run the Linux-ABI conformance bench and write the compatibility matrix.

For each fixture: rebuild the OS image with the fixture embedded as `INIT.ELF`
(`LAZYOS_INIT=<path> cargo build`), boot it headless, capture the serial log, and
classify the result from the log:

    ABI:<fixture>:PASS            -> pass
    ABI:<fixture>:FAIL:<reason>   -> fail
    ABI:INIT:SKIP:<reason>        -> skip  (kernel recognised the fixture but
                                           cannot run Linux binaries yet)
    (no marker)                   -> not-run

Outputs `docs/compat/matrix.md` and `docs/compat/compat.json`.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FIXTURE_DIR = ROOT / "target" / "abi" / "fixtures"
SHOTS = ROOT / "shots" / "abi"
COMPAT = ROOT / "docs" / "compat"
IMAGE = ROOT / "target" / "lazyos.img"

ORDER = [
    "hello",
    "alloc",
    "hashmap",
    "file",
    "time",
    "thread",
    "syncstress",
    "fsstress",
    "memstress",
    "procstress",
    "sigstress",
    "epollstress",
    "unixstress",
    "busybox",
]


def build_image(fixture_path: Path, busybox: bool = False) -> bool:
    env = dict(os.environ)
    # Never let a caller's exports leak between rows: a `BUSYBOX` embedded for
    # another fixture would shadow its `INIT.ELF`, and vice versa.
    for key in ("LAZYOS_INIT", "LAZYOS_BUSYBOX", "LAZYOS_BUSYBOX_TEST"):
        env.pop(key, None)
    if busybox:
        # The BusyBox row embeds it as the system shell and makes the kernel run
        # `sh -c "echo ABI:busybox:PASS"` (the `busybox_test` cfg), then exit.
        env["LAZYOS_BUSYBOX"] = str(fixture_path)
        env["LAZYOS_BUSYBOX_TEST"] = "1"
    else:
        env["LAZYOS_INIT"] = str(fixture_path)
    result = subprocess.run(["cargo", "build"], cwd=ROOT, env=env, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"warning: image build failed for {fixture_path.name}", file=sys.stderr)
        print(result.stderr[-1500:], file=sys.stderr)
    return result.returncode == 0


def capture(name: str, at: str, accel: str = "auto") -> str:
    out = SHOTS / name
    subprocess.run(
        [
            sys.executable,
            str(ROOT / "tools" / "screenshot" / "qemu_shot.py"),
            "--out",
            str(out),
            "--at",
            at,
            "--accel",
            accel,
            "--image",
            str(IMAGE),
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    log = out / "serial.log"
    return log.read_text(errors="replace") if log.is_file() else ""


def classify(name: str, serial: str) -> tuple[str, str]:
    if re.search(rf"ABI:{re.escape(name)}:PASS", serial):
        return "pass", ""
    match = re.search(rf"ABI:{re.escape(name)}:FAIL:(.*)", serial)
    if match:
        return "fail", match.group(1).strip()[:120]
    match = re.search(r"ABI:INIT:SKIP:(.*)", serial)
    if match:
        return "skip", match.group(1).strip()[:120]
    return "not-run", ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--at", default="8", help="capture time in seconds (default 8)")
    parser.add_argument("--only", help="comma-separated fixture names to run")
    parser.add_argument("--accel", default="auto",
                        help="QEMU accelerator: auto (kvm/whpx if usable, else TCG), kvm, whpx, none")
    args = parser.parse_args()

    COMPAT.mkdir(parents=True, exist_ok=True)
    SHOTS.mkdir(parents=True, exist_ok=True)

    wanted = set(args.only.split(",")) if args.only else set(ORDER)
    results: list[dict] = []

    for name in ORDER:
        if name not in wanted:
            continue
        fixture = FIXTURE_DIR / f"{name}.elf"
        if not fixture.is_file():
            results.append({"fixture": name, "status": "unavailable", "detail": "fixture not built"})
            continue
        if not build_image(fixture, busybox=(name == "busybox")):
            results.append({"fixture": name, "status": "fail", "detail": "image build failed"})
            continue
        status, detail = classify(name, capture(name, args.at, args.accel))
        results.append({"fixture": name, "status": status, "detail": detail})
        print(f"{name}: {status} {detail}".rstrip())

    readme = ROOT / "docs" / "compat" / "compat.json"
    readme.write_text(json.dumps(results, indent=2), encoding="utf-8")

    icons = {"pass": "PASS", "fail": "FAIL", "skip": "skip", "unavailable": "n/a", "not-run": "not-run"}
    lines = [
        "# Linux ABI compatibility matrix",
        "",
        "_Generated by `tools/abi/run.py`. See the wiki page Linux ABI Compatibility._",
        "",
        "| Fixture | Status | Detail |",
        "|---|---|---|",
    ]
    for row in results:
        status = icons.get(row["status"], row["status"])
        lines.append(f"| {row['fixture']} | {status} | {row['detail']} |")
    (COMPAT / "matrix.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    passed = sum(1 for r in results if r["status"] == "pass")
    print(f"\n{passed}/{len(results)} fixtures passing")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
