"""PNG and GIF encoders in the standard library, for the LazyWeb fixtures.

`gen_fixtures.py` draws the theoldnet.com test site's pictures with these (and
`jpegenc.py` for the photo), so the harness needs no Pillow and the checked-in
files can be regenerated byte for byte. Pictures are row-major lists of RGB(A)
tuples (PNG) or of palette indices (GIF).
"""

from __future__ import annotations

import struct
import zlib


def _chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def png(width: int, height: int, pixels: list[tuple[int, ...]]) -> bytes:
    """An 8-bit RGB or RGBA PNG (by the tuples' length), filter 0, no interlace."""
    if len(pixels) != width * height or not pixels:
        raise ValueError("pixel count does not match the size")
    channels = len(pixels[0])
    if channels not in (3, 4):
        raise ValueError("pixels must be RGB or RGBA tuples")
    rows = bytearray()
    for y in range(height):
        rows.append(0)
        for pixel in pixels[y * width:(y + 1) * width]:
            rows.extend(pixel)
    header = struct.pack(">IIBBBBB", width, height, 8, 6 if channels == 4 else 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + _chunk(b"IHDR", header)
            + _chunk(b"IDAT", zlib.compress(bytes(rows), 9)) + _chunk(b"IEND", b""))


def _lzw(indices: list[int], min_size: int) -> bytes:
    """GIF's variable-width LZW, packed little-endian into sub-blocks."""
    clear, end = 1 << min_size, (1 << min_size) + 1
    codes: list[int] = [clear]
    widths: list[int] = [min_size + 1]
    table = {(i,): i for i in range(clear)}
    next_code, width = end + 1, min_size + 1
    current: tuple[int, ...] = ()
    for index in indices:
        candidate = current + (index,)
        if candidate in table:
            current = candidate
            continue
        codes.append(table[current])
        widths.append(width)
        if next_code < 4096:
            table[candidate] = next_code
            next_code += 1
            if next_code > (1 << width) and width < 12:
                width += 1
        else:  # table full: start over
            codes.append(clear)
            widths.append(width)
            table = {(i,): i for i in range(clear)}
            next_code, width = end + 1, min_size + 1
        current = (index,)
    if current:
        codes.append(table[current])
        widths.append(width)
    codes.append(end)
    widths.append(width)
    bits = bytearray()
    acc = count = 0
    for code, size in zip(codes, widths):
        acc |= code << count
        count += size
        while count >= 8:
            bits.append(acc & 0xFF)
            acc >>= 8
            count -= 8
    if count:
        bits.append(acc & 0xFF)
    blocks = b"".join(bytes([len(bits[i:i + 255])]) + bits[i:i + 255] for i in range(0, len(bits), 255))
    return bytes([min_size]) + blocks + b"\x00"


def gif(width: int, height: int, palette: list[tuple[int, int, int]], frames: list[list[int]],
        delay_cs: int = 0, transparent: int | None = None) -> bytes:
    """A GIF89a of one or more frames of palette indices. More than one frame
    makes an animation that loops forever, `delay_cs` hundredths apart."""
    depth = max(1, (len(palette) - 1).bit_length())
    table = list(palette) + [(0, 0, 0)] * ((1 << depth) - len(palette))
    out = bytearray(b"GIF89a")
    out += struct.pack("<HHBBB", width, height, 0x80 | 0x70 | (depth - 1), 0, 0)
    out += b"".join(bytes(rgb) for rgb in table)
    if len(frames) > 1:
        out += b"\x21\xff\x0bNETSCAPE2.0\x03\x01\x00\x00\x00"
    for frame in frames:
        if len(frame) != width * height:
            raise ValueError("frame size does not match")
        if len(frames) > 1 or transparent is not None:
            flags = 0x04 | (1 if transparent is not None else 0)  # dispose: restore background
            out += struct.pack("<BBBBHBB", 0x21, 0xF9, 4, flags, delay_cs, transparent or 0, 0)
        out += struct.pack("<BHHHHB", 0x2C, 0, 0, width, height, 0)
        out += _lzw(frame, max(2, depth))
    out += b"\x3b"
    return bytes(out)
