"""midlc schema backend: every interface as a static data table.

Part of the Messenger IDL compiler; see `midlc.py` for the CLI. The Rust
backend (`midlc_rust`) emits one typed codec per method, which a compiled
client needs. A *dynamic* client (the Rhai `msg` module, a future debugger or
`messengerctl call`) instead needs to know, at run time, which methods an
interface has and how each argument travels. This backend emits that as plain
data: a `static INTERFACES: &[Interface]` table whose types (`Interface`,
`Method`, `Field`, `Ty`, ...) are declared by the consuming crate's
`schema` module, so the generated file has no dependency of its own.

Every field carries its wire id (`= N`, or its 1-based position when the
`.midl` leaves it implicit), exactly as the Rust backend numbers them.
"""

from __future__ import annotations

from midlc_model import SCALARS, Interface, Method, Param, Type
from midlc_topics import QOS_VALUES

SCHEMA_HEADER = (
    "// @generated by tools/midlc/midlc.py - do not edit.\n"
    "// Regenerate with:\n"
    "//   python tools/midlc/midlc.py --schema libs/rhai-lazy/src/msg/idl.rs idl/*.midl\n"
    "//\n"
    "// Every Messenger interface as data, for dynamic clients (the Rhai `msg`\n"
    "// module). Each field carries its wire id.\n"
    "use super::schema::{Enum, Field, Interface, Method, Object, Struct, Topic, Ty};\n\n"
)

# Builtin MIDL type -> `Ty` variant (scalars plus the leaf kinds). An object
# parameter is a `Channel` (the handle number) or a `Buffer` (a ring buffer
# is one too); a dynamic client cannot build either, so it only names them.
_LEAF = {name: name for name in SCALARS} | {
    "String": "String",
    "Bytes": "Bytes",
    "Channel": "Channel",
    "Buffer": "Buffer",
    "Ring": "Buffer",
}


def rust_str(text: str) -> str:
    """`text` as a Rust string literal (docs may hold quotes and newlines)."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def ty_expr(ty: Type, interface: Interface) -> str:
    """The `Ty` constant expression for `ty`; named types resolve to the
    interface's own structs and enums (the parser rejects anything else)."""
    if ty.name in _LEAF:
        return f"Ty::{_LEAF[ty.name]}"
    if ty.name in ("Array", "Option"):
        return f"Ty::{ty.name}(&{ty_expr(ty.args[0], interface)})"
    if any(enum.name == ty.name for enum in interface.enums):
        return f"Ty::Enum({rust_str(ty.name)})"
    return f"Ty::Struct({rust_str(ty.name)})"


def fields_expr(fields: list[Param], interface: Interface) -> str:
    if not fields:
        return "&[]"
    items = ", ".join(
        f"Field {{ name: {rust_str(f.name)}, id: {f.id}, ty: {ty_expr(f.ty, interface)} }}" for f in fields
    )
    return f"&[{items}]"


def objects_expr(method: Method) -> str:
    """The `Object` list of `method`, in object-list order: a channel names
    its interface."""
    if not method.objects:
        return "&[]"
    items = ", ".join(
        f"Object {{ name: {rust_str(o.dotted)}, channel: "
        + (f"Some({rust_str(o.interface)})" if o.kind == "channel" else "None")
        + " }"
        for o in method.objects
    )
    return f"&[{items}]"


def section(name: str, items: list[str]) -> list[str]:
    """`name: &[ ... ],` with one item block per entry, or `&[]` when empty."""
    if not items:
        return [f"        {name}: &[],"]
    return [f"        {name}: &["] + items + ["        ],"]


def emit_interface(interface: Interface) -> list[str]:
    lines = [
        "    Interface {",
        f"        name: {rust_str(interface.name)},",
        f"        id: {interface.id:#x},",
        f"        doc: {rust_str(interface.docs)},",
    ]
    methods: list[str] = []
    for method in interface.methods:
        methods += [
            "            Method {",
            f"                name: {rust_str(method.name)},",
            f"                id: {method.method_id},",
            f"                oneway: {str(method.oneway).lower()},",
            f"                doc: {rust_str(method.doc)},",
            f"                params: {fields_expr(method.params, interface)},",
            f"                returns: {fields_expr(method.returns, interface)},",
            f"                objects: {objects_expr(method)},",
            "            },",
        ]
    lines += section("methods", methods)
    structs: list[str] = []
    for struct in interface.structs:
        structs += [
            "            Struct {",
            f"                name: {rust_str(struct.name)},",
            f"                doc: {rust_str(struct.doc)},",
            f"                fields: {fields_expr(struct.fields, interface)},",
            "            },",
        ]
    lines += section("structs", structs)
    enums = [
        f"            Enum {{ name: {rust_str(e.name)}, variants: &[{', '.join(rust_str(v) for v in e.variants)}] }},"
        for e in interface.enums
    ]
    lines += section("enums", enums)
    topics: list[str] = []
    for topic in interface.topics:
        topics += [
            "            Topic {",
            f"                pattern: {rust_str(topic.name)},",
            f"                payload: {rust_str(topic.payload)},",
            f"                qos: {QOS_VALUES.index(topic.qos)},",
            f"                retained: {str(topic.retained).lower()},",
            f"                doc: {rust_str(topic.doc)},",
            "            },",
        ]
    lines += section("topics", topics)
    lines.append("    },")
    return lines


def emit_schema(interfaces: list[Interface]) -> str:
    """The whole generated schema file."""
    lines = ["#[rustfmt::skip]", "pub static INTERFACES: &[Interface] = &["]
    for interface in interfaces:
        lines += emit_interface(interface)
    lines.append("];")
    return SCHEMA_HEADER + "\n".join(lines) + "\n"
