"""midlc topic runtime: the Rust support module emitted once per crate.

Part of the Messenger IDL compiler (issue #307); see `docs/midl.md`. The
per-topic `publish_*`/`subscribe_*` helpers (emitted by `midlc_rust`) share
this small runtime. It depends only on `libmessenger` because the kernel links
the generated crate too, so no userspace transport may leak in.

Kept in its own module so `midlc_rust.py` stays under the repository's file
size limit.
"""

from __future__ import annotations

#: Emitted once at the top of the generated crate, before the interface
#: modules. The `#[rustfmt::skip]` keeps the generated bytes reproducible
#: (`midlc --check`), since the generator does not run rustfmt.
TOPIC_SUPPORT = '''\
/// Shared runtime for the topic helpers generated from `topic` declarations
/// (issue #307, `docs/midl.md`).
// Generated code is not hand-formatted; skip rustfmt so the generator's output
// is byte-for-byte reproducible (`midlc --check`).
#[rustfmt::skip]
pub mod topics {
    use alloc::string::String;

    /// `Qos::Latest` (`idl/topics.midl`).
    pub const QOS_LATEST: u32 = 0;
    /// `Qos::Buffered`.
    pub const QOS_BUFFERED: u32 = 1;
    /// `Qos::Conflate`.
    pub const QOS_CONFLATE: u32 = 2;
    /// `Qos::Reliable`.
    pub const QOS_RELIABLE: u32 = 3;

    /// Longest topic name, mirroring the broker and the kernel ACL gate.
    pub const MAX_NAME_BYTES: usize = 128;
    /// Deepest topic, mirroring the broker and the kernel ACL gate.
    pub const MAX_SEGMENTS: usize = 8;

    /// Whether a generated name is a concrete publish topic or a filter.
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub enum Mode {
        /// Publishing: every wildcard must be given a literal segment.
        Publish,
        /// Subscribing: a `+` segment and a trailing `#` are allowed.
        Subscribe,
    }

    /// Why a generated topic helper refused to build a name.
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub enum TopicError {
        /// A segment was empty or used a character the broker refuses.
        BadSegment,
        /// Fewer arguments than the pattern's wildcards.
        MissingSegment,
        /// More arguments than the pattern's wildcards.
        ExtraSegment,
        /// The built name exceeded the broker's byte or segment limit.
        TooLong,
        /// A payload could not be encoded.
        Encode(libmessenger::Error),
    }

    impl From<libmessenger::Error> for TopicError {
        fn from(error: libmessenger::Error) -> Self {
            TopicError::Encode(error)
        }
    }

    /// A transport that publishes already-encoded topic payload bytes.
    pub trait Publish {
        /// The transport's error type.
        type Error;
        /// Publish `payload` under `topic`; `retained` keeps it for late
        /// subscribers.
        fn publish_topic(
            &mut self,
            topic: &str,
            payload: &[u8],
            retained: bool,
        ) -> Result<u64, Self::Error>;
    }

    /// A transport that subscribes to a topic filter.
    pub trait Subscribe {
        /// The transport's error type.
        type Error;
        /// The live subscription handle.
        type Subscription;
        /// Subscribe to `filter` with the `qos` code from `idl/topics.midl`.
        fn subscribe_topic(&mut self, filter: &str, qos: u32)
            -> Result<Self::Subscription, Self::Error>;
    }

    /// One declared topic, for introspection (`messengerctl topics`).
    #[derive(Clone, Copy, Debug)]
    pub struct TopicDecl {
        /// Owning interface name.
        pub interface: &'static str,
        /// Normalized filter pattern (`+`/`#`).
        pub name: &'static str,
        /// Payload type name declared in the interface.
        pub payload: &'static str,
        /// `Qos` code from `idl/topics.midl`.
        pub qos: u32,
        /// Whether publishers mark the topic retained.
        pub retained: bool,
        /// The `publish:<pattern>` permission string.
        pub publish_permission: &'static str,
        /// The `subscribe:<pattern>` permission string.
        pub subscribe_permission: &'static str,
    }

    /// Whether `byte` may appear in a literal segment (the broker's set).
    fn valid_literal_byte(byte: u8) -> bool {
        byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.')
    }

    fn push_literal(out: &mut String, segment: &str) -> Result<(), TopicError> {
        if segment.is_empty() || !segment.bytes().all(valid_literal_byte) {
            return Err(TopicError::BadSegment);
        }
        out.push_str(segment);
        Ok(())
    }

    /// Push a `#` argument: one or more literal segments, or (subscribe only)
    /// a literal prefix whose last segment is a standalone `#`.
    fn push_tail(out: &mut String, arg: &str, mode: Mode) -> Result<(), TopicError> {
        let mut parts = arg.split('/').peekable();
        while let Some(part) = parts.next() {
            let last = parts.peek().is_none();
            if mode == Mode::Subscribe && last && part == "#" {
                out.push('#');
            } else {
                push_literal(out, part)?;
            }
            if !last {
                out.push('/');
            }
        }
        Ok(())
    }

    /// Build a concrete name (`Mode::Publish`) or a filter
    /// (`Mode::Subscribe`) from the normalized `pattern` and one argument per
    /// wildcard, left to right.
    pub fn build(pattern: &str, args: &[&str], mode: Mode) -> Result<String, TopicError> {
        if pattern.is_empty() || pattern.split('/').count() > MAX_SEGMENTS {
            return Err(TopicError::TooLong);
        }
        let mut out = String::new();
        let mut used = 0usize;
        for (index, segment) in pattern.split('/').enumerate() {
            if index > 0 {
                out.push('/');
            }
            match segment {
                "+" => {
                    let arg = *args.get(used).ok_or(TopicError::MissingSegment)?;
                    used += 1;
                    if mode == Mode::Subscribe && arg == "+" {
                        out.push('+');
                    } else {
                        push_literal(&mut out, arg)?;
                    }
                }
                "#" => {
                    let arg = *args.get(used).ok_or(TopicError::MissingSegment)?;
                    used += 1;
                    push_tail(&mut out, arg, mode)?;
                }
                literal => push_literal(&mut out, literal)?,
            }
        }
        if used != args.len() {
            return Err(TopicError::ExtraSegment);
        }
        if out.len() > MAX_NAME_BYTES || out.split('/').count() > MAX_SEGMENTS {
            return Err(TopicError::TooLong);
        }
        Ok(out)
    }

    /// Whether the topic filter `filter` matches the concrete `topic`: `+` is
    /// one segment, a trailing `#` is zero or more. Mirrors the broker.
    pub fn matches(filter: &str, topic: &str) -> bool {
        let mut filter_segments = filter.split('/');
        let mut topic_segments = topic.split('/');
        loop {
            match (filter_segments.next(), topic_segments.next()) {
                (Some("#"), _) => return true,
                (Some("+"), Some(_)) => {}
                (Some(expected), Some(actual)) if expected == actual => {}
                (None, None) => return true,
                _ => return false,
            }
        }
    }
}
'''
