#!/usr/bin/env python3
"""midlc - the Messenger IDL compiler (issue #90).

Reads `.midl` interface definitions (docs/messenger.md section 11) and emits:

  * Rust wire helpers (encode/decode over the `libmessenger` parcel codec),
  * a Markdown reference per interface (signatures, types),
  * a machine-readable manifest (method ids and the interface hash),
  * a schema table (`--schema`): every interface as static data for dynamic
    clients such as the Rhai `msg` module (`midlc_schema`).

Usage:
    python tools/midlc/midlc.py --out libs/generated/src/lib.rs idl/echo.midl
    python tools/midlc/midlc.py --check --out libs/generated/src/lib.rs idl/echo.midl
    python tools/midlc/midlc.py --manifest build/manifest.json idl/echo.midl
    python tools/midlc/midlc.py --schema libs/rhai-lazy/src/msg/idl.rs idl/*.midl

`--check` regenerates in memory and fails if the committed `--out` (and, when
given, `--schema`) file differs, so
generated code cannot silently drift; CI runs it on every pull request.

Grammar (small on purpose):

    interface os.lazy.echo.v1 {
        /// Doc comment for the method.
        method Echo(text: String, count: U32) -> (reply: String);
        method Notify(event: Event) -> () oneway;    // oneway methods return ()
        struct Event { topic: String, at: U64 }
        enum Level { Info, Warn, Error }
    }

Method ids are stable: an explicit `= 7` wins, otherwise a deterministic hash of
the method name is used; adding methods never renumbers existing ones.

The compiler is split across sibling modules so each stays small:
`midlc_model` (types and hashing), `midlc_lexer`, `midlc_parser`,
`midlc_rust` (Rust backend), `midlc_docs` (Markdown/manifest), and this CLI
entry point. Their public names are re-exported here for compatibility.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from midlc_docs import emit_manifest, emit_markdown
from midlc_lexer import TOKEN, Token, lex
from midlc_model import (
    BUILTINS,
    SCALARS,
    Enum,
    Interface,
    Method,
    MidlError,
    Param,
    Struct,
    Topic,
    TopicParam,
    Type,
    fnv1a32,
    fnv1a64,
    snake_case,
)
from midlc_parser import Parser, check_type, validate
from midlc_schema import emit_schema
from midlc_rust import (
    DECODE_EXPR,
    ITEM_EXPR,
    RUST_TYPE,
    decode_block,
    deref,
    emit_doc_lines,
    emit_field_dispatch,
    emit_message,
    emit_rust,
    emit_struct,
    emit_topic,
    emit_topic_table,
    encode_lines,
    rust_type,
)
from midlc_topic_support import TOPIC_SUPPORT
from midlc_topics import make_topic, parse_pattern, qos_rust_expr

HEADER = (
    "// @generated by tools/midlc/midlc.py - do not edit.\n"
    "// Regenerate with:\n"
    "//   python tools/midlc/midlc.py --out libs/generated/src/lib.rs idl/*.midl\n"
    "#![cfg_attr(not(test), no_std)]\n"
    "extern crate alloc;\n\n"
)


def parse_all(inputs: list[Path]) -> list[Interface]:
    interfaces = []
    for path in inputs:
        interfaces += Parser(lex(path.read_text(encoding="utf-8"))).parse_interfaces()
    return interfaces


def generate(inputs: list[Path]) -> tuple[str, list[dict], dict[str, str]]:
    interfaces = parse_all(inputs)
    modules = "\n\n".join(emit_rust(i) for i in interfaces)
    # The shared topic runtime comes before the modules that use it, and the
    # crate-level declaration table after them.
    rust = HEADER + TOPIC_SUPPORT + "\n" + modules + "\n\n" + emit_topic_table(interfaces)
    return rust, [emit_manifest(i) for i in interfaces], {i.name: emit_markdown(i) for i in interfaces}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="+", type=Path, help=".midl files")
    parser.add_argument("--out", type=Path, help="write generated Rust here")
    parser.add_argument("--manifest", type=Path, help="write the JSON manifest here")
    parser.add_argument("--docs", type=Path, help="write Markdown docs into this directory")
    parser.add_argument("--schema", type=Path, help="write the interface schema table here")
    parser.add_argument("--check", action="store_true", help="fail if --out/--schema would change")
    args = parser.parse_args()

    try:
        rust, manifests, docs = generate(args.inputs)
        schema = emit_schema(parse_all(args.inputs)) if args.schema else ""
    except MidlError as error:
        print(f"midlc: {error}", file=sys.stderr)
        return 1

    if args.check:
        targets = [(flag, path, text) for flag, path, text in
                   (("--out", args.out, rust), ("--schema", args.schema, schema)) if path]
        if not targets:
            print("midlc: --check needs --out and/or --schema", file=sys.stderr)
            return 1
        for flag, path, text in targets:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                print(
                    f"midlc: {path} is out of date; regenerate with:\n"
                    f"  python tools/midlc/midlc.py {flag} {path} {' '.join(str(p) for p in args.inputs)}",
                    file=sys.stderr,
                )
                return 1
            print(f"midlc: {path} is up to date ({len(manifests)} interface(s))")
        return 0

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(rust, encoding="utf-8")
        print(f"midlc: wrote {args.out}")
    if args.schema:
        args.schema.parent.mkdir(parents=True, exist_ok=True)
        args.schema.write_text(schema, encoding="utf-8")
        print(f"midlc: wrote {args.schema}")
    if args.manifest:
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(json.dumps(manifests, indent=2) + "\n", encoding="utf-8")
        print(f"midlc: wrote {args.manifest}")
    if args.docs:
        args.docs.mkdir(parents=True, exist_ok=True)
        for name, text in docs.items():
            (args.docs / f"{name}.md").write_text(text, encoding="utf-8")
        print(f"midlc: wrote {len(docs)} doc page(s) to {args.docs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
