"""midlc Rhai API backend: one scripting module per interface.

Part of the Messenger IDL compiler; see `midlc.py` for the CLI and
`docs/lazyrad-messenger-plan.md` for the design. The schema backend
(`midlc_schema`) already makes every interface callable from Rhai through the
generic `msg` module (`msg::connect("os.lazy.confd.v1").invoke("Get", [...])`).
This backend writes the *convenient* layer on top of it, as Rhai source a
script author can read:

    sys::confd::get("sys/ui/theme")            // one function per method
    sys::confd::new_value()                    // a struct with every field
    sys::confd::on_changed("sys/#", |event| { ... })   // typed topic helpers
    sys::messenger_topics::QOS_RELIABLE        // enum variants as constants

Every generated body is one call into `msg`, so values, errors and timeouts
behave exactly as `docs/rhai/msg.md` describes; nothing here touches the wire.

Output (`--rhai-api DIR`): `DIR/<alias>.rhai` per interface, `DIR/index.rs`
(the Rust table `rhai-lazy` embeds: alias, interface, source, topic helpers)
and `DIR/README.md` (the reference, from `midlc_rhai_docs`).
"""

from __future__ import annotations

import re

from midlc_model import SCALARS, Interface, Method, MidlError, Param, Topic, Type, snake_case

GENERATED = (
    "// @generated by tools/midlc/midlc.py - do not edit.\n"
    "// Regenerate with:\n"
    "//   python tools/midlc/midlc.py --rhai-api libs/rhai-lazy/api idl/*.midl\n"
)

#: Interfaces that are request layouts for kernel operations (ACL scopes, the
#: privileged policy loader): no service ever receives them as a parcel, so a
#: function calling them could only fail.
KERNEL_SCOPES = frozenset(
    {
        "os.lazy.messenger.policy.v1",
        "os.lazy.messenger.names.resolve.v1",
        "os.lazy.messenger.topics.publish.v1",
        "os.lazy.messenger.topics.subscribe.v1",
    }
)

#: Rhai keywords and reserved words: a generated name equal to one gets a
#: trailing `_` (a parameter) or is refused (a function, which must keep its
#: documented spelling).
RHAI_RESERVED = frozenset(
    """true false let const if else switch do while until loop for in continue
    break return throw try catch fn private import export as global Fn call
    curry is_shared is_def_fn is_def_var this type_of print debug eval var
    static shared goto exit match case public protected new use with module
    package super thread spawn go await async sync yield default void null
    nil is""".split()
)

#: Leading topic segments that say nothing about the event.
_NOISE_SEGMENTS = {"system", "events"}

#: Zero value of each leaf type, as a Rhai expression.
_ZERO = {name: ("0.0" if name == "F64" else "false" if name == "Bool" else "0") for name in SCALARS} | {
    "String": '""',
    "Bytes": "blob()",
}


def alias(interface: Interface) -> str:
    """`os.lazy.confd.v1` -> `confd`; `os.lazy.net.nic.v1` -> `net_nic`."""
    name = re.sub(r"\.v\d+$", "", interface.name)
    name = re.sub(r"^os\.lazy\.", "", name)
    return re.sub(r"[^0-9a-z]+", "_", name.lower()).strip("_")


def scriptable(interfaces: list[Interface]) -> list[Interface]:
    """The interfaces that get a module, with their aliases checked unique."""
    chosen = [i for i in interfaces if i.name not in KERNEL_SCOPES]
    seen: dict[str, str] = {}
    for interface in chosen:
        name = alias(interface)
        if name in seen:
            raise MidlError(
                f"interfaces {seen[name]!r} and {interface.name!r} both map to the "
                f"Rhai module sys::{name}"
            )
        seen[name] = interface.name
    return chosen


def topic_helper(interface: Interface, topic: Topic) -> str:
    """The helper stem for `topic`: its literal segments without `system`,
    `events` or the interface's own name (`system/confd/changed/{path...}` in
    `confd` -> `changed`). A topic whose segments are all dropped keeps them
    minus the noise words (`system/health/{name}` in `healthd` -> `health`)."""
    own = set(alias(interface).split("_"))
    own |= {part[:-1] for part in own if part.endswith("d")}
    literal = [seg for seg in topic.segments if seg not in ("+", "#")]
    kept = [seg for seg in literal if seg not in _NOISE_SEGMENTS and seg not in own]
    if not kept:
        kept = [seg for seg in literal if seg not in _NOISE_SEGMENTS] or literal
    return re.sub(r"[^0-9a-z]+", "_", "_".join(kept).lower()).strip("_")


def topic_helpers(interface: Interface) -> list[tuple[Topic, str]]:
    """Every topic with its helper stem; two topics of one interface that fold
    to the same stem use their full literal suffix instead."""
    stems = [topic_helper(interface, topic) for topic in interface.topics]
    result = []
    for topic, stem in zip(interface.topics, stems):
        if stems.count(stem) > 1:
            stem = topic.suffix.lower()
        result.append((topic, stem))
    return result


def param_name(name: str) -> str:
    """A Rhai-safe parameter name."""
    return f"{name}_" if name in RHAI_RESERVED else name


def placeholder_names(topic: Topic) -> list[str]:
    return [param_name(p.rust_name) for p in topic.params]


def callable_methods(interface: Interface) -> list[Method]:
    """Methods a script can call: a request that transfers a kernel object
    (channel, buffer, ring) needs something a script cannot create."""
    return [m for m in interface.methods if not m.transfers]


def struct_zero(ty: Type, interface: Interface) -> str:
    """The Rhai expression for `ty`'s zero value (`new_<struct>()` for a
    nested struct, the first variant for an enum)."""
    if ty.name in _ZERO:
        return _ZERO[ty.name]
    if ty.name == "Array":
        return "[]"
    if ty.name == "Option":
        return "()"
    for enum in interface.enums:
        if enum.name == ty.name:
            return rhai_str(enum.variants[0])
    return f"new_{snake_case(ty.name)}()"


def rhai_str(text: str) -> str:
    """`text` as a Rhai string literal."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def doc_lines(text: str, prefix: str = "///") -> list[str]:
    return [f"{prefix} {line}".rstrip() for line in text.splitlines()] if text else []


def signature(method: Method) -> str:
    def fields(items: list[Param]) -> str:
        return ", ".join(f"{p.name}: {p.ty}" for p in items)

    tail = " oneway" if method.oneway else ""
    return f"{method.name}({fields(method.params)}) -> ({fields(method.returns)}){tail}"


class ModuleWriter:
    """Builds one interface's module, refusing two functions with the same
    name and arity (Rhai would silently keep the last)."""

    def __init__(self, interface: Interface):
        self.interface = interface
        self.alias = alias(interface)
        self.lines: list[str] = []
        self.functions: set[tuple[str, int]] = set()
        self.constants: set[str] = set()

    def fn(self, docs: list[str], name: str, params: list[str], body: str) -> None:
        if name in RHAI_RESERVED:
            raise MidlError(f"{self.interface.name}: the Rhai function name {name!r} is reserved")
        key = (name, len(params))
        if key in self.functions:
            raise MidlError(
                f"{self.interface.name}: two Rhai functions sys::{self.alias}::{name} "
                f"take {len(params)} argument(s)"
            )
        self.functions.add(key)
        self.lines += docs + [f"fn {name}({', '.join(params)}) {{", f"    {body}", "}", ""]

    def const(self, comment: list[str], name: str, value: str) -> None:
        if name in self.constants:
            raise MidlError(f"{self.interface.name}: two Rhai constants named {name}")
        self.constants.add(name)
        self.lines += comment + [f"export const {name} = {value};", ""]

    def connect_expr(self) -> str:
        return f"msg::connect({rhai_str(self.interface.name)})"

    def header(self) -> None:
        i = self.interface
        self.lines += [GENERATED.rstrip("\n"), "//", f"// `sys::{self.alias}`: the Messenger interface `{i.name}`."]
        if i.docs:
            self.lines += ["//"] + doc_lines(i.docs, "//")
        self.lines.append("")
        self.const(["// The interface every function of this module calls."], "INTERFACE", rhai_str(i.name))
        self.fn(
            [
                "/// The connected service: `invoke`, `invoke_oneway` and method sugar",
                "/// (`docs/rhai/msg.md`). Resolved once per process.",
            ],
            "connect",
            [],
            self.connect_expr(),
        )

    def methods(self) -> None:
        for method in callable_methods(self.interface):
            params = [param_name(p.name) for p in method.params]
            docs = [f"/// `{signature(method)}`"]
            if method.doc:
                docs += ["///"] + doc_lines(method.doc)
            if method.oneway:
                docs += ["///", "/// One-way: returns `()` once the message is queued."]
            body = f"{self.connect_expr()}.invoke({rhai_str(method.name)}, [{', '.join(params)}])"
            self.fn(docs, snake_case(method.name), params, body)
        skipped = [m.name for m in self.interface.methods if m.transfers]
        if skipped:
            self.lines += [
                "// Not callable from a script (the request transfers a channel, buffer",
                f"// or ring): {', '.join(skipped)}.",
                "",
            ]

    def structs(self) -> None:
        for struct in self.interface.structs:
            fields = ", ".join(f"{f.name}: {struct_zero(f.ty, self.interface)}" for f in struct.fields)
            docs = [f"/// A `{struct.name}` with every field at its zero value."]
            if struct.doc:
                docs += ["///"] + doc_lines(struct.doc)
            self.fn(docs, f"new_{snake_case(struct.name)}", [], f"#{{ {fields} }}" if fields else "#{}")

    def enums(self) -> None:
        for enum in self.interface.enums:
            prefix = snake_case(enum.name).upper()
            variants = ", ".join(rhai_str(v) for v in enum.variants)
            self.const([f"// The variants of `{enum.name}`, in wire order."], prefix, f"[{variants}]")
            for variant in enum.variants:
                self.const([], f"{prefix}_{snake_case(variant).upper()}", rhai_str(variant))

    def topics(self) -> None:
        for topic, stem in topic_helpers(self.interface):
            self.topic(topic, stem)

    def topic(self, topic: Topic, stem: str) -> None:
        names = placeholder_names(topic)
        about = (
            f"`{topic.source}` (payload `{topic.payload}`, qos {topic.qos}"
            + (", retained" if topic.retained else "")
            + ")"
        )
        self.const(
            [f"// Filter for every event of the topic {about}."] + doc_lines(topic.doc, "//"),
            f"{stem.upper()}_PATTERN",
            rhai_str(topic.name),
        )
        filled = self.fill(topic, names)
        if names:
            self.fn(
                [f"/// The topic name of {about} for these placeholder values."],
                f"{stem}_topic",
                names,
                filled,
            )
        pattern = rhai_str(topic.name)
        on_docs = [
            f"/// Run `handler(event)` for each event of {about}; `event.payload` is",
            f"/// the decoded `{topic.payload}`. Returns the `Subscription`.",
        ]
        self.fn(on_docs, f"on_{stem}", ["handler"], f"msg::on({pattern}, handler)")
        sub_docs = [f"/// Subscribe to {about} to pull events with `sub.next()`."]
        self.fn(sub_docs, f"subscribe_{stem}", [], f"msg::subscribe({pattern})")
        if names:
            narrowed = "/// Placeholder values narrow the filter (`+` or `#` keep a wildcard)."
            self.fn(on_docs + [narrowed], f"on_{stem}", names + ["handler"], f"msg::on({filled}, handler)")
            self.fn(sub_docs + [narrowed], f"subscribe_{stem}", names, f"msg::subscribe({filled})")
        self.fn(
            [f"/// Publish `payload` (a `{topic.payload}`) on {about}."],
            f"publish_{stem}",
            names + ["payload"],
            f"msg::publish({filled}, payload)",
        )

    @staticmethod
    def fill(topic: Topic, names: list[str]) -> str:
        """A Rhai expression building the concrete topic from `names`."""
        if not names:
            return rhai_str(topic.name)
        values = iter(names)
        segments = [
            "${" + next(values) + "}" if segment in ("+", "#") else segment
            for segment in topic.segments
        ]
        return "`" + "/".join(segments) + "`"

    def render(self) -> str:
        self.header()
        self.methods()
        self.structs()
        self.enums()
        self.topics()
        while self.lines and self.lines[-1] == "":
            self.lines.pop()
        return "\n".join(self.lines) + "\n"


def emit_module(interface: Interface) -> str:
    """The `.rhai` source of `interface`'s module."""
    return ModuleWriter(interface).render()


def emit_index(interfaces: list[Interface]) -> str:
    """`index.rs`: the table `rhai-lazy` embeds (`msg::api`). Each topic row
    names its helper stem and its normalized filter, for permission
    derivation."""
    lines = [
        GENERATED.rstrip("\n"),
        "//",
        "// The generated Rhai API modules (`sys::<alias>`), embedded by",
        "// `libs/rhai-lazy/src/msg/api.rs`.",
        "#[rustfmt::skip]",
        "pub static MODULES: &[ApiModule] = &[",
    ]
    for interface in interfaces:
        name = alias(interface)
        topics = ", ".join(
            f"ApiTopic {{ helper: {rhai_str(stem)}, pattern: {rhai_str(topic.name)} }}"
            for topic, stem in topic_helpers(interface)
        )
        lines += [
            "    ApiModule {",
            f"        alias: {rhai_str(name)},",
            f"        interface: {rhai_str(interface.name)},",
            f'        source: include_str!("{name}.rhai"),',
            f"        topics: &[{topics}],",
            "    },",
        ]
    lines.append("];")
    return "\n".join(lines) + "\n"


def emit_rhai_api(interfaces: list[Interface]) -> dict[str, str]:
    """Every file of the `--rhai-api` directory, by file name."""
    from midlc_rhai_docs import emit_reference

    chosen = scriptable(interfaces)
    files = {f"{alias(i)}.rhai": emit_module(i) for i in chosen}
    files["index.rs"] = emit_index(chosen)
    files["README.md"] = emit_reference(chosen)
    return files
