"""midlc conformance, Rust side: hold the generated codecs to the corpus.

Part of the Messenger IDL compiler; see `midlc_conformance.py`. Emits
`libs/generated/tests/conformance.rs`: the Rust codecs `midlc_rust` generates
for every valid corpus case, and one test per sample value that encodes it
with them, compares the bytes with the corpus (written by the independent
`midlc_wire` encoder), then decodes the corpus bytes back to the same value.
The standard-error samples are checked against `messenger_generated::errors`.
"""

from __future__ import annotations

import json
import re
import struct
from pathlib import Path

from midlc_conformance import ERROR_MESSAGE, parse_case
from midlc_model import Interface, Type, snake_case
from midlc_rust import emit_rust
from midlc_schema import rust_str
from midlc_wire import enum_index, message_fields

HEADER = """\
// @generated by tools/midlc/conformance.py - do not edit.
// Regenerate with:
//   python tools/midlc/conformance.py --write
//
// The midlc Rust codecs for every case of idl/conformance/valid, each held
// to the bytes the corpus records for its sample values.

extern crate alloc;

#[rustfmt::skip]
#[allow(dead_code, unused_imports, clippy::all)]
mod corpus {
use alloc::string::String;
use alloc::vec::Vec;

fn hex(text: &str) -> Vec<u8> {
    (0..text.len()).step_by(2).map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap()).collect()
}
"""

INT_SUFFIX = {"I32": "i32", "I64": "i64", "U32": "u32", "U64": "u64"}


def literal(interface: Interface, module: str, ty: Type, value) -> str:
    """`value` of type `ty` as a Rust expression of the generated type."""
    if ty.enum:
        return f"{enum_index(interface, ty, value)}u32"
    if ty.name == "Bool":
        return "true" if value else "false"
    if ty.name in INT_SUFFIX:
        return f"{value}{INT_SUFFIX[ty.name]}"
    if ty.name == "F64":
        return f"f64::from_bits({struct.unpack('<Q', struct.pack('<d', value))[0]:#x})"
    if ty.name == "String":
        return f"String::from({rust_str(value)})"
    if ty.name == "Bytes":
        return "Vec::<u8>::from([" + ", ".join(f"{b}u8" for b in bytes.fromhex(value)) + "])"
    if ty.name == "Array":
        items = ", ".join(literal(interface, module, ty.args[0], item) for item in value)
        return f"alloc::vec![{items}]"
    if ty.name == "Option":
        return "None" if value is None else f"Some({literal(interface, module, ty.args[0], value)})"
    record = next(s for s in interface.structs if s.name == ty.name)
    return record_literal(interface, module, f"{module}::{record.name}", record.fields, value)


def record_literal(interface: Interface, module: str, path: str, fields, value: dict) -> str:
    inits = ", ".join(f"{f.name}: {literal(interface, module, f.ty, value[f.name])}" for f in fields)
    return f"{path} {{ {inits} }}"


def codec_names(message: str) -> tuple[str, str]:
    """(Rust type name, codec suffix) of a struct or `Method.args`/`.reply`."""
    if "." in message:
        method, kind = message.split(".", 1)
        return f"{method}{kind.capitalize()}", f"{snake_case(method)}_{kind}"
    return message, snake_case(message)


def test_name(case: str, vector: str) -> str:
    return re.sub(r"[^0-9a-z_]", "_", f"{case}_{vector}".lower())


def emit_vector(case: str, interfaces: list[Interface], vector: dict) -> list[str]:
    name = test_name(case, vector["name"])
    expected = vector["bytes"]
    if vector["message"] == ERROR_MESSAGE:
        value = vector["value"]
        build = f"messenger_generated::errors::ReplyError::new({value['code']}, {rust_str(value['message'])})"
        if value.get("domain"):
            build += f".with_domain({rust_str(value['domain'])})"
        for key in ("hint", "docs"):
            if value.get(key) is not None:
                build += f".with_{key}({rust_str(value[key])})"
        return [
            "#[test]",
            f"fn {name}() {{",
            f"    let value = {build};",
            f'    let bytes = hex("{expected}");',
            "    assert_eq!(messenger_generated::errors::encode(&value).unwrap(), bytes);",
            "    assert_eq!(messenger_generated::errors::find(&bytes).unwrap(), Some(value));",
            "}",
            "",
        ]
    interface = next(i for i in interfaces if i.name == vector.get("interface", interfaces[0].name))
    module = f"case_{case}::{interface.module}"
    type_name, suffix = codec_names(vector["message"])
    fields = message_fields(interface, vector["message"])
    value = record_literal(interface, module, f"{module}::{type_name}", fields, vector["value"])
    return [
        "#[test]",
        f"fn {name}() {{",
        f"    let value = {value};",
        f'    let bytes = hex("{expected}");',
        f"    assert_eq!({module}::encode_{suffix}(&value).unwrap(), bytes);",
        f"    assert_eq!({module}::decode_{suffix}(&bytes).unwrap(), value);",
        "}",
        "",
    ]


def emit_conformance_rust(corpus: Path, expected: dict[Path, str]) -> str:
    """The Rust test file for the corpus, given its expected files."""
    lines = [HEADER]
    for midl in sorted((corpus / "valid").glob("*.midl")):
        case = midl.stem
        interfaces, _ = parse_case(midl.read_text(encoding="utf-8"))
        lines.append(f"mod case_{case} {{")
        lines.append("use messenger_generated::{rings, topics, transfers};")
        lines += [emit_rust(i) for i in interfaces]
        lines.append("}")
        lines.append("")
        data = json.loads(expected[midl.with_suffix(".expected.json")])
        for vector in data["vectors"]:
            lines += emit_vector(case, interfaces, vector)
    lines.append("}")
    return "\n".join(lines) + "\n"
