//! Parcel framing for the topics broker protocol.
//!
//! The wire shapes are the `midlc`-generated `os.lazy.messenger.topics.v1`
//! stubs ([`generated`], from `idl/topics.midl`); this module frames them in
//! parcels on the broker interface and converts to the module's plain Rust
//! types. Only the structured error field is hand-written: it is a convention
//! every service shares, not part of the interface.

use alloc::string::String;
use alloc::vec::Vec;

use libmessenger::{Decoder, Encoder, Kind, Parcel};
use messenger_generated::os_lazy_messenger_topics_v1 as generated;

use super::super::{errno, Error, Result};
use super::{header, Event, Qos, SubscriptionStats, TopicInfo};

pub use generated::{
    decode_ack_args, decode_publish_args, decode_subscribe_args, METHOD_ACK, METHOD_LISTTOPICS,
    METHOD_NEXTEVENT, METHOD_PING, METHOD_PUBLISH, METHOD_STATS, METHOD_SUBSCRIBE,
    METHOD_UNSUBSCRIBE,
};

/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;

/// Wrap an encoded body in a broker parcel.
pub fn request_parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: header(method),
        body,
        objects: Vec::new(),
    }
}

/// An empty reply.
pub fn reply_ok(method: u32) -> Parcel {
    request_parcel(method, Vec::new())
}

fn wire<T>(result: core::result::Result<T, libmessenger::Error>) -> Result<T> {
    result.map_err(Error::Parcel)
}

// -- Requests ---------------------------------------------------------------

/// A `Publish` request; `payload` is the publisher's encoded parcel.
pub fn publish_request(topic: &str, payload: &[u8], retained: bool) -> Result<Parcel> {
    let args = generated::PublishArgs {
        topic: String::from(topic),
        payload: payload.to_vec(),
        retained,
    };
    Ok(request_parcel(
        METHOD_PUBLISH,
        wire(generated::encode_publish_args(&args))?,
    ))
}

/// A `Subscribe` request for `filter` under `qos`.
pub fn subscribe_request(filter: &str, qos: Qos) -> Result<Parcel> {
    let args = generated::SubscribeArgs {
        filter: String::from(filter),
        qos: qos.code(),
        depth: qos.depth(),
    };
    Ok(request_parcel(
        METHOD_SUBSCRIBE,
        wire(generated::encode_subscribe_args(&args))?,
    ))
}

/// A request that names one subscription: `Unsubscribe`, `NextEvent` or
/// `Stats` (`method`); the three argument layouts are identical.
pub fn subscription_request(method: u32, id: u64) -> Result<Parcel> {
    let args = generated::UnsubscribeArgs { subscription: id };
    Ok(request_parcel(
        method,
        wire(generated::encode_unsubscribe_args(&args))?,
    ))
}

/// The subscription id a `NextEvent`/`Unsubscribe`/`Stats` request names.
pub fn decode_subscription_args(parcel: &Parcel) -> Result<u64> {
    Ok(wire(generated::decode_unsubscribe_args(&parcel.body))?.subscription)
}

/// An `Ack` request retiring every event up to `sequence`.
pub fn ack_request(id: u64, sequence: u64) -> Result<Parcel> {
    let args = generated::AckArgs {
        subscription: id,
        sequence,
    };
    Ok(request_parcel(
        METHOD_ACK,
        wire(generated::encode_ack_args(&args))?,
    ))
}

/// A `ListTopics` request.
pub fn list_request() -> Parcel {
    reply_ok(METHOD_LISTTOPICS)
}

/// A `Ping` request.
pub fn ping_request() -> Parcel {
    reply_ok(METHOD_PING)
}

// -- Replies (built by the broker) -----------------------------------------

/// A publish reply carrying the subscriber count the event reached.
pub fn reply_matched(matched: u64) -> Result<Parcel> {
    let reply = generated::PublishReply { matched };
    Ok(request_parcel(
        METHOD_PUBLISH,
        wire(generated::encode_publish_reply(&reply))?,
    ))
}

/// A subscribe reply carrying the new subscription id.
pub fn reply_subscription(id: u64) -> Result<Parcel> {
    let reply = generated::SubscribeReply { subscription: id };
    Ok(request_parcel(
        METHOD_SUBSCRIBE,
        wire(generated::encode_subscribe_reply(&reply))?,
    ))
}

/// A `NextEvent` reply carrying one event.
pub fn reply_event(event: &Event) -> Result<Parcel> {
    let reply = generated::NextEventReply {
        event: generated::Event {
            topic: event.topic.clone(),
            publisher: event.publisher,
            sequence: event.sequence,
            retained: event.retained,
            payload: event.payload.clone(),
        },
    };
    Ok(request_parcel(
        METHOD_NEXTEVENT,
        wire(generated::encode_next_event_reply(&reply))?,
    ))
}

/// A stats reply.
pub fn reply_stats(stats: &SubscriptionStats) -> Result<Parcel> {
    let reply = generated::StatsReply {
        stats: generated::Stats {
            qos: stats.qos,
            depth: stats.depth,
            queued: stats.queued,
            delivered: stats.delivered,
            matched: stats.matched,
            drops: stats.drops,
        },
    };
    Ok(request_parcel(
        METHOD_STATS,
        wire(generated::encode_stats_reply(&reply))?,
    ))
}

/// A topic-list reply.
pub fn reply_topics(topics: &[TopicInfo]) -> Result<Parcel> {
    let reply = generated::ListTopicsReply {
        topics: topics
            .iter()
            .map(|info| generated::TopicInfo {
                topic: info.topic.clone(),
                subscribers: info.subscribers,
                retained: info.retained,
            })
            .collect(),
    };
    Ok(request_parcel(
        METHOD_LISTTOPICS,
        wire(generated::encode_list_topics_reply(&reply))?,
    ))
}

/// The broker error answer: errno-style code plus friendly text.
pub fn error_reply(method: u32, error: Error) -> Parcel {
    let code = error.errno().map(|code| -code).unwrap_or(errno::EINVAL);
    let mut body = Encoder::new();
    // A structured error field cannot overflow a fresh encoder here.
    let _ = body.error(ERROR_FIELD, code as u32, error.message());
    request_parcel(method, body.finish())
}

// -- Reply decoding (client side) ------------------------------------------

/// The first structured error field, when the reply is a broker failure.
///
/// Every client checks each reply for a daemon failure before decoding it.
pub fn error_field(parcel: &Parcel) -> Result<Option<i64>> {
    let mut decoder = Decoder::new(&parcel.body);
    while let Some(field) = decoder.next().map_err(Error::Parcel)? {
        if field.kind == Kind::Error && field.id == ERROR_FIELD {
            let (code, _message) = field.error_parts().map_err(Error::Parcel)?;
            return Ok(Some(code as i64));
        }
    }
    Ok(None)
}

/// The subscriber count of a publish reply (zero when the field is absent).
pub fn decode_matched(parcel: &Parcel) -> Result<u64> {
    Ok(wire(generated::decode_publish_reply(&parcel.body))?.matched)
}

/// The subscription id of a subscribe reply; a reply without one is
/// malformed.
pub fn decode_subscription(parcel: &Parcel) -> Result<u64> {
    let id = wire(generated::decode_subscribe_reply(&parcel.body))?.subscription;
    // Subscription ids start at 1, so zero is the absent-field default.
    if id == 0 {
        return Err(Error::Errno(-errno::EINVAL));
    }
    Ok(id)
}

/// Decode the event of a `NextEvent` reply; `None` when the reply is empty.
pub fn decode_event(parcel: &Parcel) -> Result<Option<Event>> {
    if parcel.body.is_empty() {
        return Ok(None);
    }
    let event = wire(generated::decode_next_event_reply(&parcel.body))?.event;
    Ok(Some(Event {
        topic: event.topic,
        publisher: event.publisher,
        sequence: event.sequence,
        retained: event.retained,
        payload: event.payload,
    }))
}

/// Decode a stats reply.
pub fn decode_stats(parcel: &Parcel) -> Result<SubscriptionStats> {
    let stats = wire(generated::decode_stats_reply(&parcel.body))?.stats;
    Ok(SubscriptionStats {
        qos: stats.qos,
        depth: stats.depth,
        queued: stats.queued,
        delivered: stats.delivered,
        matched: stats.matched,
        drops: stats.drops,
    })
}

/// Decode a topic-list reply.
pub fn decode_topics(parcel: &Parcel) -> Result<Vec<TopicInfo>> {
    let reply = wire(generated::decode_list_topics_reply(&parcel.body))?;
    Ok(reply
        .topics
        .into_iter()
        .map(|info| TopicInfo {
            topic: info.topic,
            subscribers: info.subscribers,
            retained: info.retained,
        })
        .collect())
}
