"""Tests for tools/check_file_length.py (offline, temp trees)."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_file_length as cfl  # noqa: E402


def lines(n: int, head: str = "") -> str:
    return head + "x = 1\n" * n


class CheckTests(unittest.TestCase):
    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.root = Path(tmp.name)

    def put(self, name: str, text: str) -> None:
        (self.root / name).write_text(text, encoding="utf-8")

    def run_check(self, names: list[str], allow: dict[str, int] | None = None) -> list[str]:
        return cfl.check(names, self.root, allow or {})

    def test_at_limit_passes_and_over_fails(self) -> None:
        self.put("ok.py", lines(500))
        self.put("big.rs", lines(501))
        problems = self.run_check(["ok.py", "big.rs"])
        self.assertEqual(len(problems), 1)
        self.assertIn("big.rs", problems[0])

    def test_generated_header_is_exempt(self) -> None:
        self.put("gen.rs", lines(900, "// @generated by midlc\n"))
        self.assertEqual(self.run_check(["gen.rs"]), [])

    def test_allowlisted_file_may_not_grow(self) -> None:
        self.put("old.py", lines(600))
        self.assertEqual(self.run_check(["old.py"], {"old.py": 600}), [])
        self.put("old.py", lines(601))
        self.assertEqual(len(self.run_check(["old.py"], {"old.py": 600})), 1)

    def test_stale_allowlist_entries_are_reported(self) -> None:
        self.put("split.py", lines(100))
        self.assertEqual(len(self.run_check(["split.py"], {"split.py": 600})), 1)

    def test_repository_passes(self) -> None:
        self.assertEqual(cfl.check(cfl.tracked_files()), [])


if __name__ == "__main__":
    unittest.main()
