//! 7z reading, against archives made by 7-Zip itself (`tests/fixtures`,
//! regenerated by `tests/fixtures/make.py`).

use std::path::PathBuf;
use std::sync::Arc;

use crate::extract;
use crate::{Archive, EntryKind, Error, Format, Progress};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn open(name: &str) -> Archive {
    Archive::open(&fixture(name), &Arc::new(Progress::new())).unwrap()
}

/// Every file's data, by path.
fn contents(archive: &Archive) -> Vec<(String, Vec<u8>)> {
    let mut out = Vec::new();
    archive
        .visit(&|_| true, &Arc::new(Progress::new()), &mut |entry, data| {
            let mut buf = Vec::new();
            data.read_to_end(&mut buf)?;
            if matches!(entry.kind, EntryKind::File) {
                out.push((entry.path.clone(), buf));
            }
            Ok(())
        })
        .unwrap();
    out.sort();
    out
}

#[test]
fn every_7z_coder_we_support_reads_the_same_tree() {
    for name in ["lzma2.7z", "lzma.7z", "copy.7z", "deflate.7z"] {
        let archive = open(name);
        assert_eq!(archive.format, Format::SevenZ, "{name}");
        let dirs: Vec<_> = archive
            .entries
            .iter()
            .filter(|e| e.kind.is_dir())
            .map(|e| e.path.as_str())
            .collect();
        assert!(dirs.contains(&"tree/sub"), "{name}: {dirs:?}");
        let files = contents(&archive);
        let names: Vec<_> = files.iter().map(|(p, _)| p.as_str()).collect();
        assert_eq!(
            names,
            ["tree/empty.txt", "tree/hello.txt", "tree/sub/numbers.txt"],
            "{name}"
        );
        assert_eq!(files[1].1, b"Hello from 7-Zip!\n");
        assert_eq!(files[2].1.len(), 46890);
        assert!(files[0].1.is_empty());
    }
}

#[test]
fn an_encrypted_7z_lists_and_refuses_its_data() {
    let archive = open("aes.7z");
    let hello = archive
        .entries
        .iter()
        .find(|e| e.path == "tree/hello.txt")
        .unwrap();
    assert!(hello.encrypted);
    let dest = std::env::temp_dir().join(format!("lazyarc-7z-aes-{}", std::process::id()));
    let report = extract::extract(
        &archive,
        &|_| true,
        &dest,
        &extract::Options::default(),
        &Arc::new(Progress::new()),
    )
    .unwrap();
    assert!(report
        .skipped
        .iter()
        .any(|(path, why)| path == "tree/hello.txt" && why == "encrypted"));
    let _ = std::fs::remove_dir_all(dest);
}

#[test]
fn a_damaged_7z_header_is_refused() {
    let mut bytes = std::fs::read(fixture("lzma2.7z")).unwrap();
    let len = bytes.len();
    bytes[len - 3] ^= 0xff;
    let path = std::env::temp_dir().join(format!("lazyarc-7z-bad-{}.7z", std::process::id()));
    std::fs::write(&path, &bytes).unwrap();
    let result = Archive::open(&path, &Arc::new(Progress::new()));
    assert!(matches!(result, Err(Error::Corrupt(_))));
    let _ = std::fs::remove_file(path);
}

#[test]
fn a_damaged_member_of_a_non_solid_7z_fails_alone() {
    // deflate.7z is non-solid: one folder per file. Damage the first
    // folder's packed bytes; the other file must still come out.
    let mut bytes = std::fs::read(fixture("deflate.7z")).unwrap();
    for byte in &mut bytes[34..44] {
        *byte ^= 0x5a;
    }
    let path = std::env::temp_dir().join(format!("lazyarc-7z-damaged-{}.7z", std::process::id()));
    std::fs::write(&path, &bytes).unwrap();
    let archive = Archive::open(&path, &Arc::new(Progress::new())).unwrap();
    let dest = std::env::temp_dir().join(format!("lazyarc-7z-damaged-out-{}", std::process::id()));
    let report = extract::extract(
        &archive,
        &|_| true,
        &dest,
        &extract::Options::default(),
        &Arc::new(Progress::new()),
    )
    .expect("a damaged member is reported, not fatal");
    assert_eq!(report.skipped.len(), 1, "{:?}", report.skipped);
    // The empty file and the undamaged member are written.
    assert!(report.files >= 2, "{report:?}");
    let _ = std::fs::remove_file(path);
    let _ = std::fs::remove_dir_all(dest);
}
