//! Anti-aliased monospace font atlas, generated at build time.

/// Per-glyph metrics, generated by `kernel/build.rs`.
#[derive(Clone, Copy)]
pub struct Glyph {
    pub width: u32,
    pub height: u32,
    pub left: i32,
    pub top: i32,
    pub offset: u32,
}

// Brings in FIRST_CHAR, LAST_CHAR, ASCENDER, DESCENDER, LINE_HEIGHT, ADVANCE,
// GLYPHS and COVERAGE, all generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/font_atlas.rs"));
