//! `os.lazy.audio.v1` client: the audio driver's control interface
//! (`idl/audio.midl`, docs/driver-plan.md D6).
//!
//! The stubs are generated by `midlc`; this module adds the service name, the
//! reply framing and a blocking [`Client`]. Sample data never crosses the wire:
//! the client creates a shared ring ([`crate::sys::display_create_buffer`]),
//! hands it over with [`Client::attach_ring`], and tells the driver how far it
//! has written with [`Client::commit`].

use alloc::vec;
use alloc::vec::Vec;

use libmessenger::{BufferDesc, Header, Parcel, VERSION};

use super::services::error_field;
use super::{registry, Endpoint, Error, Result};

/// The generated `os.lazy.audio.v1` stubs.
pub use messenger_generated::os_lazy_audio_v1 as wire;

/// Registered service name.
pub const NAME: &str = "os.lazy.audio";

/// The interface id every audio parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// `Direction` ordinals.
pub const PLAYBACK: u32 = wire::DIRECTION_PLAYBACK;
pub const CAPTURE: u32 = wire::DIRECTION_CAPTURE;

/// `Format` ordinals.
pub const S16_LE: u32 = wire::FORMAT_S16_LE;

/// The granted stream parameters.
pub use wire::StreamGrant as Grant;

/// The card's capabilities.
pub use wire::AudioInfo as Info;

/// A parcel of `method` carrying an already-encoded `body` and optional
/// shared buffers (only `AttachRing` sends one).
pub fn parcel(method: u32, body: Vec<u8>, buffers: Vec<BufferDesc>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        buffers,
        ..Parcel::default()
    }
}

/// A blocking client of the audio driver.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`]; the endpoint is opened in this task's handle table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// Run one request; a service failure comes back as its original errno.
    fn call(&self, request: Parcel, deadline: Option<u64>) -> Result<Parcel> {
        let reply = self.endpoint.call(&request, deadline)?;
        match error_field(&reply)? {
            Some(code) => Err(Error::Errno(-code)),
            None => Ok(reply),
        }
    }

    /// Send an arbitrary request (hostile-input tests): `body` and `buffers`
    /// go out as given, and a service failure still comes back as its errno.
    pub fn raw(&self, method: u32, body: Vec<u8>, buffers: Vec<BufferDesc>) -> Result<Parcel> {
        self.call(parcel(method, body, buffers), None)
    }

    fn simple(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        self.call(parcel(method, body, Vec::new()), None)
    }

    /// `Info()`: what the card can do.
    pub fn info(&self) -> Result<Info> {
        let reply = self.simple(wire::METHOD_INFO, Vec::new())?;
        Ok(wire::decode_info_reply(&reply.body)
            .map_err(Error::Parcel)?
            .info)
    }

    /// `OpenStream(...)`: negotiate a stream; the driver grants the closest
    /// supported parameters.
    pub fn open_stream(
        &self,
        direction: u32,
        format: u32,
        rate: u32,
        channels: u32,
        period_bytes: u32,
    ) -> Result<Grant> {
        let body = wire::encode_open_stream_args(&wire::OpenStreamArgs {
            dir: direction,
            format,
            rate,
            channels,
            period_bytes,
        })
        .map_err(Error::Parcel)?;
        let reply = self.simple(wire::METHOD_OPENSTREAM, body)?;
        Ok(wire::decode_open_stream_reply(&reply.body)
            .map_err(Error::Parcel)?
            .grant)
    }

    /// `AttachRing(stream)`: share `buffer` (a shared-buffer handle of at least
    /// `len` bytes) as the stream's sample ring.
    pub fn attach_ring(&self, stream: u32, buffer: u64, len: u64) -> Result<()> {
        let body = wire::encode_attach_ring_args(&wire::AttachRingArgs { stream })
            .map_err(Error::Parcel)?;
        let buffers = vec![BufferDesc {
            handle: buffer,
            offset: 0,
            len,
            flags: 0,
        }];
        self.call(parcel(wire::METHOD_ATTACHRING, body, buffers), None)
            .map(|_| ())
    }

    /// `Commit(stream, written_frames)`: returns the frames the driver has
    /// consumed so far.
    pub fn commit(&self, stream: u32, written_frames: u64) -> Result<u64> {
        let body = wire::encode_commit_args(&wire::CommitArgs {
            stream,
            written_frames,
        })
        .map_err(Error::Parcel)?;
        let reply = self.simple(wire::METHOD_COMMIT, body)?;
        Ok(wire::decode_commit_reply(&reply.body)
            .map_err(Error::Parcel)?
            .consumed)
    }

    /// `Start(stream)`.
    pub fn start(&self, stream: u32) -> Result<()> {
        let body = wire::encode_start_args(&wire::StartArgs { stream }).map_err(Error::Parcel)?;
        self.simple(wire::METHOD_START, body).map(|_| ())
    }

    /// `Stop(stream)`.
    pub fn stop(&self, stream: u32) -> Result<()> {
        let body = wire::encode_stop_args(&wire::StopArgs { stream }).map_err(Error::Parcel)?;
        self.simple(wire::METHOD_STOP, body).map(|_| ())
    }

    /// `Drain(stream)`: returns once everything committed has played. `deadline`
    /// is an absolute PIT tick, or `None` to wait as long as it takes.
    pub fn drain(&self, stream: u32, deadline: Option<u64>) -> Result<()> {
        let body = wire::encode_drain_args(&wire::DrainArgs { stream }).map_err(Error::Parcel)?;
        self.call(parcel(wire::METHOD_DRAIN, body, Vec::new()), deadline)
            .map(|_| ())
    }

    /// `Position(stream)`: frames played since the last start.
    pub fn position(&self, stream: u32) -> Result<u64> {
        let body =
            wire::encode_position_args(&wire::PositionArgs { stream }).map_err(Error::Parcel)?;
        let reply = self.simple(wire::METHOD_POSITION, body)?;
        Ok(wire::decode_position_reply(&reply.body)
            .map_err(Error::Parcel)?
            .frames)
    }

    /// `CloseStream(stream)`.
    pub fn close_stream(&self, stream: u32) -> Result<()> {
        let body = wire::encode_close_stream_args(&wire::CloseStreamArgs { stream })
            .map_err(Error::Parcel)?;
        self.simple(wire::METHOD_CLOSESTREAM, body).map(|_| ())
    }
}
