//! `os.lazy.audio.v1` server-side helpers (`idl/audio.midl`,
//! docs/audio-plan.md).
//!
//! The stubs are generated by `midlc`; this module adds the service names and
//! the reply framing the two servers (`sndd` for the card, `audiod` for the
//! mixer) share. Clients use `libs/audioclient` through [`crate::audio`].

use alloc::vec::Vec;

use libmessenger::{BufferDesc, Header, Parcel, VERSION};

/// The generated `os.lazy.audio.v1` stubs.
pub use messenger_generated::os_lazy_audio_v1 as wire;

/// The generated `os.lazy.audio.mixer.v1` stubs.
pub use messenger_generated::os_lazy_audio_mixer_v1 as control_wire;

/// The mixer (`audiod`): the name applications resolve.
pub const NAME: &str = audioclient::NAME;

/// The card driver (`sndd`): only the mixer opens it.
pub const CARD_NAME: &str = audioclient::CARD_NAME;

/// The interface id every stream parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// The interface id of the mixer's control panel.
pub const CONTROL_INTERFACE: u64 = control_wire::INTERFACE_ID;

/// `Direction` ordinals.
pub const PLAYBACK: u32 = wire::DIRECTION_PLAYBACK;
pub const CAPTURE: u32 = wire::DIRECTION_CAPTURE;

/// `Format` ordinals.
pub const S16_LE: u32 = wire::FORMAT_S16_LE;

/// The granted stream parameters.
pub use wire::StreamGrant as Grant;

/// The card's capabilities.
pub use wire::AudioInfo as Info;

/// A reply parcel of `interface`/`method` carrying an already-encoded `body`.
pub fn reply_parcel(interface: u64, method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: interface,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        buffers: Vec::<BufferDesc>::new(),
        ..Parcel::default()
    }
}

/// A stream-interface parcel of `method` (the driver's replies).
pub fn parcel(method: u32, body: Vec<u8>, buffers: Vec<BufferDesc>) -> Parcel {
    Parcel {
        buffers,
        ..reply_parcel(INTERFACE, method, body)
    }
}
