//! `confd` client and wire shapes (issue #260).
//!
//! The `os.lazy.confd.v1` stubs are generated by `midlc` into
//! `messenger-generated`; this module adds the typed [`confd::Value`]
//! conversion, the request/reply parcel framing, the
//! `system/confd/changed/<path>` payload codec, and a [`Client`] that
//! resolves-and-retries while `confd` is still registering at boot.

use alloc::string::String;
use alloc::vec::Vec;

use libmessenger::{Decoder, Encoder, Header, Kind, Parcel, VERSION};

use super::{errno, registry, Endpoint, Error, Result};

/// The generated `os.lazy.confd.v1` stubs.
pub use messenger_generated::os_lazy_confd_v1 as wire;
/// The generated helpers for the declared `system/confd/changed/#` topic, so
/// callers do not have to reach through [`wire`].
pub use messenger_generated::os_lazy_confd_v1::{
    decode_system_confd_changed, encode_system_confd_changed, name_system_confd_changed,
    publish_system_confd_changed,
};

/// Registered service name (the root object clients resolve).
pub const NAME: &str = "os.lazy.confd";

/// The interface id every `confd` parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// `CONFD_*` error codes carried in the reply's structured `ERROR` field. They
/// are deliberately outside the errno range so a client can tell a store
/// rejection from a transport failure.
pub const CONFD_NOT_FOUND: i64 = 1001;
pub const CONFD_BAD_PATH: i64 = 1002;
pub const CONFD_TOO_LARGE: i64 = 1003;
pub const CONFD_DENIED: i64 = 1004;
pub const CONFD_IO: i64 = 1005;
pub const CONFD_BAD_VALUE: i64 = 1006;

/// `Value.kind` discriminants (mirrors `idl/confd.midl`).
pub const KIND_BOOL: u32 = 0;
pub const KIND_I64: u32 = 1;
pub const KIND_U64: u32 = 2;
pub const KIND_STR: u32 = 3;
pub const KIND_BYTES: u32 = 4;

/// Structured error field id in a reply body (unused by the generated fields
/// 1-6, so it can never collide with a success payload).
const ERROR_FIELD: u16 = 15;

/// A header for a `confd` parcel of `method`.
fn header(method: u32) -> Header {
    Header {
        version: VERSION,
        flags: 0,
        interface_id: INTERFACE,
        method,
        txn_id: 0,
        reply_to: 0,
        deadline_ns: 0,
    }
}
/// Wrap an encoded body in a `confd` parcel (also the reply builder).
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: header(method),
        body,
        handles: Vec::new(),
        buffers: Vec::new(),
    }
}

/// The positive `CONFD_*` code a service failure maps to.
pub fn service_error_code(error: confd::ServiceError) -> i64 {
    match error {
        confd::ServiceError::NotFound => CONFD_NOT_FOUND,
        confd::ServiceError::BadPath => CONFD_BAD_PATH,
        confd::ServiceError::TooLarge => CONFD_TOO_LARGE,
        confd::ServiceError::Denied => CONFD_DENIED,
        confd::ServiceError::Io => CONFD_IO,
    }
}

/// A structured error reply (the daemon's failure answer).
pub fn error_reply(method: u32, code: i64, message: &str) -> Parcel {
    let mut body = Encoder::new();
    // A structured error field cannot overflow a fresh encoder here.
    let _ = body.error(ERROR_FIELD, code as u32, message);
    parcel(method, body.finish())
}

/// The first structured error code in `parcel`, if any.
fn error_code(parcel: &Parcel) -> Option<i64> {
    let mut decoder = Decoder::new(&parcel.body);
    while let Ok(Some(field)) = decoder.next() {
        if field.kind == Kind::Error && field.id == ERROR_FIELD {
            if let Ok((code, _message)) = field.error_parts() {
                return Some(code as i64);
            }
        }
    }
    None
}

/// `confd::Value` -> the generated wire value.
pub fn value_to_wire(value: &confd::Value) -> wire::Value {
    let mut out = wire::Value::default();
    match value {
        confd::Value::Bool(flag) => {
            out.kind = KIND_BOOL;
            out.bool_value = Some(*flag);
        }
        confd::Value::I64(number) => {
            out.kind = KIND_I64;
            out.i64_value = Some(*number);
        }
        confd::Value::U64(number) => {
            out.kind = KIND_U64;
            out.u64_value = Some(*number);
        }
        confd::Value::Str(text) => {
            out.kind = KIND_STR;
            out.str_value = Some(text.clone());
        }
        confd::Value::Bytes(bytes) => {
            out.kind = KIND_BYTES;
            out.bytes_value = Some(bytes.clone());
        }
    }
    out
}

/// The generated wire value -> `confd::Value`; a `kind` whose payload is
/// missing is rejected so a malformed request cannot become an empty value.
pub fn value_from_wire(value: &wire::Value) -> Result<confd::Value> {
    let invalid = || Error::Errno(-errno::EINVAL);
    match value.kind {
        KIND_BOOL => value.bool_value.map(confd::Value::Bool).ok_or_else(invalid),
        KIND_I64 => value.i64_value.map(confd::Value::I64).ok_or_else(invalid),
        KIND_U64 => value.u64_value.map(confd::Value::U64).ok_or_else(invalid),
        KIND_STR => value
            .str_value
            .clone()
            .map(confd::Value::Str)
            .ok_or_else(invalid),
        KIND_BYTES => value
            .bytes_value
            .clone()
            .map(confd::Value::Bytes)
            .ok_or_else(invalid),
        _ => Err(invalid()),
    }
}

/// A blocking client of the `confd` service.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`]; the returned endpoint is open in this task's table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// [`Client::connect`] with a short retry loop, for a client that starts
    /// before `confd` has registered its name at boot. Parks one tick between
    /// attempts (userspace has no sleep syscall).
    pub fn connect_retry(attempts: usize) -> Result<Client> {
        let mut last = Error::Errno(-errno::ENOENT);
        for _ in 0..attempts {
            match registry::resolve(NAME) {
                Ok(endpoint) => return Ok(Client { endpoint }),
                Err(error) => last = error,
            }
            park_tick();
        }
        Err(last)
    }

    /// Wrap an already-resolved endpoint.
    pub fn from_endpoint(endpoint: Endpoint) -> Client {
        Client { endpoint }
    }

    /// The underlying service endpoint (diagnostics).
    pub fn endpoint(&self) -> Endpoint {
        self.endpoint
    }

    /// Run one request and turn a `CONFD_*` error reply into [`Error::Confd`].
    fn call(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        let reply = self.endpoint.call(&parcel(method, body), None)?;
        if let Some(code) = error_code(&reply) {
            return Err(Error::Confd(code));
        }
        Ok(reply)
    }

    /// `Get(path)`: `None` when the path is absent.
    pub fn get(&self, path: &str) -> Result<Option<confd::Value>> {
        let body = wire::encode_get_args(&wire::GetArgs {
            path: String::from(path),
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_GET, body)?;
        let decoded = wire::decode_get_reply(&reply.body).map_err(Error::Parcel)?;
        match decoded.value {
            Some(value) => Ok(Some(value_from_wire(&value)?)),
            None => Ok(None),
        }
    }

    /// `Set(path, value)`.
    pub fn set(&self, path: &str, value: &confd::Value) -> Result<()> {
        let body = wire::encode_set_args(&wire::SetArgs {
            path: String::from(path),
            value: value_to_wire(value),
        })
        .map_err(Error::Parcel)?;
        self.call(wire::METHOD_SET, body).map(|_| ())
    }

    /// `Delete(path)`; deleting an absent path succeeds.
    pub fn delete(&self, path: &str) -> Result<()> {
        let body = wire::encode_delete_args(&wire::DeleteArgs {
            path: String::from(path),
        })
        .map_err(Error::Parcel)?;
        self.call(wire::METHOD_DELETE, body).map(|_| ())
    }

    /// `List(prefix)`.
    pub fn list(&self, prefix: &str) -> Result<Vec<String>> {
        let body = wire::encode_list_args(&wire::ListArgs {
            prefix: String::from(prefix),
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_LIST, body)?;
        Ok(wire::decode_list_reply(&reply.body)
            .map_err(Error::Parcel)?
            .paths)
    }

    /// `Info()`: the directory `confd` keeps its store in and whether that
    /// survives a reboot (`false` when it fell back to ramfs).
    pub fn info(&self) -> Result<(String, bool)> {
        let reply = self.call(wire::METHOD_INFO, Vec::new())?;
        let info = wire::decode_info_reply(&reply.body).map_err(Error::Parcel)?;
        Ok((info.store_dir, info.persistent))
    }

    /// Subscribe to change topics; the filter is a topic filter such as
    /// `system/confd/changed/sys/#`. Retained nothing is replayed (changes are
    /// not retained), so callers should `List`/`Get` once before watching.
    pub fn watch(&self, filter: &str) -> Result<crate::central::Subscription> {
        let mut bus = crate::central::Bus::connect_retry(4)?;
        bus.subscribe(filter)
    }

    /// Human-readable text for a [`Client`] failure.
    pub fn describe(error: Error) -> &'static str {
        error.message()
    }
}

/// Sleep one PIT tick by parking on a private channel pair with an expired
/// deadline. The pair is closed again, so no channel leaks.
fn park_tick() {
    if let Ok((probe, peer)) = super::create_pair() {
        let mut scratch = [0u8; 16];
        let _ = probe.recv_into(&mut scratch, Some(super::EXPIRED_DEADLINE));
        let _ = probe.close();
        let _ = peer.close();
    }
}
