//! `devd` client (issue #497): the device manager's view of every device.
//!
//! The `os.lazy.devd.v1` stubs are generated by `midlc` from `idl/devd.midl`;
//! this module adds the service name, the reply framing and a blocking
//! [`Client`]. The service failure convention is the shared structured error
//! field ([`super::services::error_field`]).

use alloc::vec::Vec;

use libmessenger::{Header, Parcel, VERSION};

use super::services::error_field;
use super::{registry, Endpoint, Error, Result};

/// The generated `os.lazy.devd.v1` stubs.
pub use messenger_generated::os_lazy_devd_v1 as wire;

/// One device as `devd` reports it.
pub use wire::DeviceState;

/// Registered service name.
pub const NAME: &str = "os.lazy.devd";

/// The interface id every `devd` parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// A parcel of `method` carrying an already-encoded `body` (request or reply).
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        ..Parcel::default()
    }
}

/// A blocking client of `devd`.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`]; the endpoint is opened in this task's handle table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// Every device `devd` knows.
    pub fn devices(&self) -> Result<Vec<DeviceState>> {
        let reply = self
            .endpoint
            .call(&parcel(wire::METHOD_DEVICES, Vec::new()), None)?;
        if let Some(code) = error_field(&reply)? {
            return Err(Error::Errno(-code));
        }
        Ok(wire::decode_devices_reply(&reply.body)
            .map_err(Error::Parcel)?
            .devices)
    }
}
