//! The network mount service `mountd` (docs/smb-plan.md §3.4).
//!
//! The `os.lazy.mount.v1` stubs are generated by `midlc` from
//! `idl/mount.midl`; this module adds the service name and the reply framing
//! the service uses. Its clients are the Network Drives app (`xui-app`) and
//! scripts (`sys::mount` in `rhai`), which have their own.

use alloc::vec::Vec;

use libmessenger::{Header, Parcel, VERSION};

/// The generated `os.lazy.mount.v1` stubs.
pub use messenger_generated::os_lazy_mount_v1 as wire;

/// Registered service name.
pub const NAME: &str = "os.lazy.mount";

/// The interface id every `mountd` parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// A parcel of `method` carrying an already-encoded `body` (request or reply).
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        ..Parcel::default()
    }
}
