//! `os.lazy.net.nic.v1` client: the NIC driver's control interface and the
//! client's side of its frame rings (`idl/net.midl`,
//! `docs/networking-plan.md` section 5).
//!
//! The stubs are generated by `midlc`. Frames never cross the wire: the client
//! creates one shared buffer holding both rings ([`Client::attach`]), hands it
//! to the driver with a notify endpoint, and then moves frames through the
//! rings, waking the driver with `Kick` and being woken by `Notify`.

use alloc::format;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use framering::{ring_bytes, valid_slots, Consumer, Producer, Ring};
use libmessenger::{flags, Buffer, Header, Object, Parcel, VERSION};

use super::services::error_field;
use super::{create_pair, registry, Endpoint, Error, Result};
use crate::sys;

/// The generated `os.lazy.net.nic.v1` stubs.
pub use messenger_generated::os_lazy_net_nic_v1 as wire;

/// The registry namespace of the cards: a driver serves its card as
/// `os.lazy.net.nic/<ifname>` ([`service_name`]). There is no bare name.
pub const NAME_PREFIX: &str = "os.lazy.net.nic";

/// The registered name of the card called `ifname` (`os.lazy.net.nic/eth0`).
pub fn service_name(ifname: &str) -> String {
    format!("{NAME_PREFIX}/{ifname}")
}

/// The interface name inside a registered NIC service name, if `name` is one.
pub fn ifname_of(name: &str) -> Option<&str> {
    name.strip_prefix(NAME_PREFIX)?
        .strip_prefix('/')
        .filter(|ifname| devmatch::valid_ifname(ifname))
}

/// A NIC service that is registered right now.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Present {
    pub ifname: String,
    /// The driver's task slot (the kernel-stamped sender of its messages).
    pub driver: u64,
    /// The identity the kernel holds for that task (`List` reports it; the
    /// registry only lets a driver identity hold the name, and `netd` checks
    /// again before it trusts the card).
    pub owner_uid: u64,
    pub owner_label: u64,
    pub owner_session: u64,
}

impl Present {
    /// Whether the owner is an identity that may serve a NIC
    /// (`netpolicy::may_register_nic_name`).
    pub fn owner_is_driver(&self) -> bool {
        match (
            u32::try_from(self.owner_uid),
            u32::try_from(self.owner_label),
        ) {
            (Ok(uid), Ok(label)) => {
                netpolicy::may_register_nic_name(uid, label, self.owner_session)
            }
            _ => false,
        }
    }
}

/// Every card a driver serves at this moment, in name order.
pub fn present() -> Result<Vec<Present>> {
    let mut cards: Vec<Present> = registry::list()?
        .into_iter()
        .filter_map(|entry| {
            Some(Present {
                ifname: String::from(ifname_of(&entry.name)?),
                driver: entry.owner_slot,
                owner_uid: entry.owner_uid,
                owner_label: entry.owner_label,
                owner_session: entry.owner_session,
            })
        })
        .collect();
    cards.sort_by(|a, b| a.ifname.cmp(&b.ifname));
    Ok(cards)
}

/// The interface id every NIC parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// Card description and counters.
pub use wire::{NicInfo as Info, NicStats as Stats};

/// A parcel of `method` carrying an encoded `body`, plus the objects the
/// method carries (only `AttachRing` sends any).
pub fn parcel(method: u32, body: Vec<u8>, objects: Vec<Object>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        objects,
    }
}

/// A one-way event parcel (`Kick`, `Notify`).
pub fn event(method: u32, body: Vec<u8>) -> Parcel {
    let mut parcel = parcel(method, body, Vec::new());
    parcel.header.flags = flags::ONE_WAY;
    parcel
}

/// A blocking client of the NIC driver.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve the card `ifname`; the endpoint is opened in this task's handle
    /// table.
    pub fn connect(ifname: &str) -> Result<Client> {
        if !devmatch::valid_ifname(ifname) {
            return Err(Error::Errno(-super::errno::EINVAL));
        }
        Ok(Client {
            endpoint: registry::resolve(&service_name(ifname))?,
        })
    }

    /// Give up the handle to the driver's endpoint (it was obtained by name,
    /// so it is released, not closed: the driver and its other clients keep
    /// theirs).
    pub fn release(self) {
        let _ = self.endpoint.release();
    }

    /// Run one request; a service failure comes back as its original errno.
    fn call(&self, request: Parcel, deadline: Option<u64>) -> Result<Parcel> {
        let reply = self.endpoint.call(&request, deadline)?;
        match error_field(&reply)? {
            Some(code) => Err(Error::Errno(-code)),
            None => Ok(reply),
        }
    }

    /// Send an arbitrary request (hostile-input tests): everything goes out
    /// as given, and a service failure still comes back as its errno.
    pub fn raw(&self, method: u32, body: Vec<u8>, objects: Vec<Object>) -> Result<Parcel> {
        self.call(parcel(method, body, objects), None)
    }

    /// Send a complete, arbitrary parcel (hostile-input tests that need a
    /// wrong interface id or header).
    pub fn call_parcel(&self, request: Parcel) -> Result<Parcel> {
        self.call(request, None)
    }

    /// Send an arbitrary one-way message.
    pub fn raw_event(&self, method: u32, body: Vec<u8>) -> Result<()> {
        self.endpoint.send(&event(method, body))
    }

    fn simple(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        self.call(parcel(method, body, Vec::new()), None)
    }

    /// `Info()`.
    pub fn info(&self) -> Result<Info> {
        let reply = self.simple(wire::METHOD_INFO, Vec::new())?;
        Ok(wire::decode_info_reply(&reply.body)
            .map_err(Error::Parcel)?
            .info)
    }

    /// `Stats()`.
    pub fn stats(&self) -> Result<Stats> {
        let reply = self.simple(wire::METHOD_STATS, Vec::new())?;
        Ok(wire::decode_stats_reply(&reply.body)
            .map_err(Error::Parcel)?
            .stats)
    }

    /// `SetRxMode(mode)`: whether the driver applied it.
    pub fn set_rx_mode(&self, mode: u32) -> Result<bool> {
        let body =
            wire::encode_set_rx_mode_args(&wire::SetRxModeArgs { mode }).map_err(Error::Parcel)?;
        let reply = self.simple(wire::METHOD_SETRXMODE, body)?;
        Ok(wire::decode_set_rx_mode_reply(&reply.body)
            .map_err(Error::Parcel)?
            .ok)
    }

    /// `DetachRing(ring)`.
    pub fn detach(&self, ring: u32) -> Result<()> {
        let body =
            wire::encode_detach_ring_args(&wire::DetachRingArgs { ring }).map_err(Error::Parcel)?;
        self.simple(wire::METHOD_DETACHRING, body).map(|_| ())
    }

    /// `Kick(ring)`: tell the driver frames are waiting in the transmit ring.
    pub fn kick(&self, ring: u32) -> Result<()> {
        let body = wire::encode_kick_args(&wire::KickArgs { ring }).map_err(Error::Parcel)?;
        self.endpoint.send(&event(wire::METHOD_KICK, body))
    }

    /// Create both rings in one shared buffer and a fresh notify endpoint, and
    /// attach them. The driver keeps the other side of the endpoint; the
    /// client waits on its own with [`Attachment::wait`].
    pub fn attach(&self, slots: u32) -> Result<Attachment> {
        let (mine, theirs) = create_pair()?;
        let result = self.attach_inner(slots, theirs.handle(), Some(mine));
        if result.is_err() {
            // The driver never took the far end, or closed its copy.
            let _ = mine.close();
            let _ = theirs.close();
        }
        result
    }

    /// Create both rings and attach them, telling the driver to post `Notify`
    /// into `notify`, an endpoint this task holds and **transfers** (it is
    /// gone from this task's table on success). A service that already waits
    /// on one endpoint passes a handle to that same endpoint, so notices and
    /// requests arrive in one `recv` (`netd`). The attachment then has no
    /// notify endpoint of its own.
    pub fn attach_notifying(&self, slots: u32, notify: Endpoint) -> Result<Attachment> {
        self.attach_inner(slots, notify.handle(), None)
    }

    fn attach_inner(
        &self,
        slots: u32,
        transfer: u64,
        mine: Option<Endpoint>,
    ) -> Result<Attachment> {
        if !valid_slots(slots) {
            return Err(Error::Errno(-super::errno::EINVAL));
        }
        let one = ring_bytes(slots);
        // `net.midl` declares the buffer as `Ring<Rx, Tx>`: the generated
        // layout places them back to back and sizes the whole buffer.
        let layout =
            wire::attach_ring_rings(one as u64).ok_or(Error::Errno(-super::errno::EINVAL))?;
        let len = layout.total as usize;
        let (buffer, va, _) = sys::buffer_create(len as u64).map_err(|code| Error::Errno(-code))?;
        let base = va as *mut u8;
        // SAFETY: the kernel mapped `len` zeroed bytes at `va`; each ring is
        // `one` bytes at an offset the layout keeps inside `len`, and the
        // mapping lives until `Attachment::close`.
        let (rx, tx) = unsafe {
            let rx = Ring::create(base.add(layout.rx as usize), one, slots);
            let tx = Ring::create(base.add(layout.tx as usize), one, slots);
            (rx, tx)
        };
        let (Ok(rx), Ok(tx)) = (rx, tx) else {
            let _ = sys::buffer_close(buffer);
            return Err(Error::Errno(-super::errno::EINVAL));
        };
        let (body, objects) = wire::encode_attach_ring_args(&wire::AttachRingArgs {
            slots,
            rings: Buffer::whole(buffer, len as u64),
            notify: transfer,
        })
        .map_err(Error::Parcel)?;
        let request = parcel(wire::METHOD_ATTACHRING, body, objects);
        match self.call(request, None) {
            Ok(reply) => {
                let ring = wire::decode_attach_ring_reply(&reply.body)
                    .map_err(Error::Parcel)?
                    .ring;
                Ok(Attachment {
                    ring,
                    slots,
                    buffer,
                    base,
                    notify: mine,
                    rx: rx.consumer(),
                    tx: tx.producer(),
                    buf: vec![0; 256],
                })
            }
            Err(error) => {
                let _ = sys::buffer_close(buffer);
                Err(error)
            }
        }
    }
}

/// What [`Attachment::split`] leaves: the driver-side ring id and the
/// resources to release once nothing reads or writes the rings any more.
pub struct Shared {
    pub ring: u32,
    buffer: u64,
    notify: Option<Endpoint>,
}

impl Shared {
    /// Unmap the shared buffer and close the notify endpoint. The ring
    /// endpoints must be gone first: they point into the buffer.
    pub fn close(self) {
        let _ = sys::buffer_close(self.buffer);
        if let Some(notify) = self.notify {
            let _ = notify.close();
        }
    }
}

/// A client's attachment: its ends of the two rings and its notify endpoint.
pub struct Attachment {
    pub ring: u32,
    pub slots: u32,
    buffer: u64,
    /// Start of the shared buffer: the receive ring, then the transmit ring.
    base: *mut u8,
    /// This client's own notify endpoint; `None` when it handed the driver an
    /// endpoint it waits on elsewhere (see [`Client::attach_notifying`]).
    notify: Option<Endpoint>,
    /// Frames from the driver: this client consumes.
    pub rx: Consumer,
    /// Frames to the driver: this client produces.
    pub tx: Producer,
    buf: Vec<u8>,
}

impl Attachment {
    /// Wait for a `Notify` until the absolute tick `deadline`. `Ok(Some(events))`
    /// carries the `NotifyBit` bitmap, `Ok(None)` a timeout. A message that is
    /// not a well-formed `Notify` is ignored, as a hostile sender could send one.
    pub fn wait(&mut self, deadline: u64) -> Result<Option<u32>> {
        let Some(notify) = self.notify else {
            return Err(Error::Errno(-super::errno::EINVAL));
        };
        match notify.recv_with(&mut self.buf, Some(deadline)) {
            Ok(message) => {
                if message.interface_id() == INTERFACE && message.method() == wire::METHOD_NOTIFY {
                    if let Ok(args) = wire::decode_notify_args(&message.parcel.body) {
                        return Ok(Some(args.events));
                    }
                }
                Ok(Some(0))
            }
            Err(Error::Errno(code)) if code == -super::errno::ETIMEDOUT => Ok(None),
            Err(error) => Err(error),
        }
    }

    /// Whether the notify endpoint is still connected (the driver holds the
    /// other side); `false` once the driver dropped the attachment.
    pub fn is_live(&mut self) -> bool {
        let Some(notify) = self.notify else {
            return true;
        };
        !matches!(
            notify.poll_recv_with(&mut self.buf), Err(Error::Errno(code)) if code == -super::errno::EPIPE)
    }

    /// Hostile-client simulation for the probe: make the transmit ring's
    /// producer index claim far more frames than the ring holds, which the
    /// driver must answer by dropping this client (and nothing worse).
    pub fn corrupt_transmit_ring(&mut self) {
        let head = ring_bytes(self.slots) + framering::off::HEAD;
        // SAFETY: the transmit ring lies inside the shared buffer this
        // attachment owns; the driver tolerates the peer writing any word.
        unsafe { core::ptr::write_volatile(self.base.add(head) as *mut u32, 0x7FFF_0000) };
    }

    /// Split into the two ring endpoints and what must be released when the
    /// attachment ends: for a consumer that owns the rings itself (a stack
    /// device) rather than driving them through this wrapper.
    pub fn split(self) -> (Consumer, Producer, Shared) {
        let shared = Shared {
            ring: self.ring,
            buffer: self.buffer,
            notify: self.notify,
        };
        (self.rx, self.tx, shared)
    }

    /// Release the shared buffer and the notify endpoint. Call
    /// [`Client::detach`] first to release the driver's side.
    pub fn close(self) {
        let _ = sys::buffer_close(self.buffer);
        if let Some(notify) = self.notify {
            let _ = notify.close();
        }
    }
}
