//! `os.lazy.net.socket.v1` client: sockets served by `netd`
//! (`idl/net.midl`, docs/networking-plan.md N3).
//!
//! The stubs are generated by `midlc`; this module adds the reply framing, the
//! errno values the interface reports, and a blocking [`Client`] with one
//! method per call. The std-like [`TcpStream`](super::netstd::TcpStream) and
//! friends in `netstd.rs` are built on it.
//!
//! **Waiting.** `Connect`, `Accept`, `Send`, `Recv`, `RecvFrom` and `Poll`
//! park inside `netd`, which answers when the socket is ready or after
//! `timeout_ms` with `ETIMEDOUT`. The caller's own kernel deadline is set a
//! little beyond that, so `netd`'s answer, not the kernel's, ends a wait.
//! The service endpoint is the stack service's (`os.lazy.net.stack`): `netd`
//! tells the interfaces apart by id.

use alloc::vec;
use alloc::vec::Vec;
use core::cell::RefCell;

use libmessenger::{Header, Parcel, VERSION};

use super::services::error_field;
use super::{registry, Endpoint, Error, Result};
use crate::sys;

/// The generated `os.lazy.net.socket.v1` stubs.
pub use messenger_generated::os_lazy_net_socket_v1 as wire;

/// Registered service name: the socket interface rides on `netd`'s endpoint.
pub const NAME: &str = super::netstack::NAME;

/// The interface id every socket parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// Errno values (Linux numbering) `netd` reports for the socket interface.
pub mod errno {
    pub const EBADF: i64 = 9;
    pub const ENFILE: i64 = 23;
    pub const EMFILE: i64 = 24;
    pub const EMSGSIZE: i64 = 90;
    pub const EADDRINUSE: i64 = 98;
    pub const ENETUNREACH: i64 = 101;
    pub const ECONNRESET: i64 = 104;
    pub const ENOTCONN: i64 = 107;
    pub const ECONNREFUSED: i64 = 111;
}

/// Largest `Send` and `Recv` chunk.
pub const MAX_CHUNK: usize = 16 * 1024;
/// The longest a call may park (`timeout_ms` 0 means this).
pub const MAX_TIMEOUT_MS: u32 = 60_000;
/// Ticks a caller waits beyond a call's own timeout.
const DEADLINE_SLACK_TICKS: u64 = 100;
/// Room for a parcel of a full chunk plus its framing.
const BUFFER: usize = MAX_CHUNK + 4096;

/// An IPv4 address and port.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Addr {
    pub ip: [u8; 4],
    pub port: u16,
}

impl Addr {
    pub const ANY: Addr = Addr {
        ip: [0; 4],
        port: 0,
    };

    pub fn new(ip: [u8; 4], port: u16) -> Addr {
        Addr { ip, port }
    }

    fn to_wire(self) -> wire::SockAddr {
        wire::SockAddr {
            addr: self.ip.to_vec(),
            port: u32::from(self.port),
        }
    }

    fn from_wire(addr: &wire::SockAddr) -> Result<Addr> {
        let ip: [u8; 4] = addr
            .addr
            .as_slice()
            .try_into()
            .map_err(|_| Error::Errno(-super::errno::EINVAL))?;
        let port = u16::try_from(addr.port).map_err(|_| Error::Errno(-super::errno::EINVAL))?;
        Ok(Addr { ip, port })
    }
}

/// A parcel of `method` carrying an encoded `body`.
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        ..Parcel::default()
    }
}

/// The wire `timeout_ms` for a wait of at most `ms` (0: the longest).
fn clamp_timeout(ms: u32) -> u32 {
    match ms {
        0 => MAX_TIMEOUT_MS,
        ms => ms.clamp(10, MAX_TIMEOUT_MS),
    }
}

fn deadline_for(timeout_ms: u32) -> u64 {
    sys::clock() + u64::from(timeout_ms) / 10 + DEADLINE_SLACK_TICKS
}

/// A blocking client of the socket service.
pub struct Client {
    endpoint: Endpoint,
    /// One reply buffer for the life of the client (the user heap recycles
    /// small blocks only, so a per-call 20 KiB buffer would be wasteful).
    buffer: RefCell<Vec<u8>>,
}

impl Client {
    /// Resolve [`NAME`]; the endpoint is opened in this task's handle table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
            buffer: RefCell::new(vec![0u8; BUFFER]),
        })
    }

    /// The underlying endpoint (hostile-input probes build their own requests).
    pub fn endpoint(&self) -> Endpoint {
        self.endpoint
    }

    /// Run one request; a service failure comes back as its original errno.
    pub fn call_parcel(&self, request: Parcel, deadline: Option<u64>) -> Result<Parcel> {
        let mut buffer = self.buffer.borrow_mut();
        let reply = self.endpoint.call_with(&request, &mut buffer, deadline)?;
        match error_field(&reply)? {
            Some(code) => Err(Error::Errno(-code)),
            None => Ok(reply),
        }
    }

    /// Send an arbitrary request (hostile-input tests).
    pub fn raw(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        self.call_parcel(parcel(method, body), None)
    }

    /// A call that never parks: the kernel deadline is a generous fixed one.
    fn quick(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        self.call_parcel(parcel(method, body), Some(deadline_for(0)))
    }

    /// A call that may park for `timeout_ms`.
    fn parking(&self, method: u32, body: Vec<u8>, timeout_ms: u32) -> Result<Parcel> {
        self.call_parcel(parcel(method, body), Some(deadline_for(timeout_ms)))
    }

    /// `Open`: a new socket of `kind` (`wire::SOCK_KIND_*`).
    pub fn open(&self, kind: u32) -> Result<u32> {
        let body = wire::encode_open_args(&wire::OpenArgs { kind }).map_err(Error::Parcel)?;
        let reply = self.quick(wire::METHOD_OPEN, body)?;
        Ok(wire::decode_open_reply(&reply.body)
            .map_err(Error::Parcel)?
            .sock)
    }

    pub fn bind(&self, sock: u32, addr: Addr) -> Result<()> {
        let body = wire::encode_bind_args(&wire::BindArgs {
            sock,
            addr: addr.to_wire(),
        })
        .map_err(Error::Parcel)?;
        self.quick(wire::METHOD_BIND, body).map(|_| ())
    }

    pub fn connect_to(&self, sock: u32, addr: Addr, timeout_ms: u32) -> Result<()> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let body = wire::encode_connect_args(&wire::ConnectArgs {
            sock,
            addr: addr.to_wire(),
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        self.parking(wire::METHOD_CONNECT, body, timeout_ms)
            .map(|_| ())
    }

    pub fn listen(&self, sock: u32, backlog: u32) -> Result<()> {
        let body =
            wire::encode_listen_args(&wire::ListenArgs { sock, backlog }).map_err(Error::Parcel)?;
        self.quick(wire::METHOD_LISTEN, body).map(|_| ())
    }

    /// `Accept`: the new socket and the peer's address.
    pub fn accept(&self, sock: u32, timeout_ms: u32) -> Result<(u32, Addr)> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let body = wire::encode_accept_args(&wire::AcceptArgs { sock, timeout_ms })
            .map_err(Error::Parcel)?;
        let reply = self.parking(wire::METHOD_ACCEPT, body, timeout_ms)?;
        let reply = wire::decode_accept_reply(&reply.body).map_err(Error::Parcel)?;
        Ok((reply.conn, Addr::from_wire(&reply.peer)?))
    }

    /// `Send`: how many bytes were queued (at most [`MAX_CHUNK`] are offered).
    pub fn send(&self, sock: u32, data: &[u8], timeout_ms: u32) -> Result<usize> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let data = &data[..data.len().min(MAX_CHUNK)];
        let body = wire::encode_send_args(&wire::SendArgs {
            sock,
            data: data.to_vec(),
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        let reply = self.parking(wire::METHOD_SEND, body, timeout_ms)?;
        Ok(wire::decode_send_reply(&reply.body)
            .map_err(Error::Parcel)?
            .sent as usize)
    }

    /// `Recv`: up to `max` bytes; an empty vector is the end of the stream.
    pub fn recv(&self, sock: u32, max: usize, timeout_ms: u32) -> Result<Vec<u8>> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let body = wire::encode_recv_args(&wire::RecvArgs {
            sock,
            max: max.min(MAX_CHUNK) as u32,
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        let reply = self.parking(wire::METHOD_RECV, body, timeout_ms)?;
        Ok(wire::decode_recv_reply(&reply.body)
            .map_err(Error::Parcel)?
            .data)
    }

    pub fn send_to(&self, sock: u32, addr: Addr, data: &[u8]) -> Result<usize> {
        let body = wire::encode_send_to_args(&wire::SendToArgs {
            sock,
            addr: addr.to_wire(),
            data: data.to_vec(),
        })
        .map_err(Error::Parcel)?;
        let reply = self.quick(wire::METHOD_SENDTO, body)?;
        Ok(wire::decode_send_to_reply(&reply.body)
            .map_err(Error::Parcel)?
            .sent as usize)
    }

    pub fn recv_from(&self, sock: u32, max: usize, timeout_ms: u32) -> Result<(Vec<u8>, Addr)> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let body = wire::encode_recv_from_args(&wire::RecvFromArgs {
            sock,
            max: max.min(MAX_CHUNK) as u32,
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        let reply = self.parking(wire::METHOD_RECVFROM, body, timeout_ms)?;
        let reply = wire::decode_recv_from_reply(&reply.body).map_err(Error::Parcel)?;
        Ok((reply.data, Addr::from_wire(&reply.from)?))
    }

    /// `Poll`: the readiness bits (`1 << wire::READY_*`) among `interest`,
    /// plus `Closed` and `Error` whenever they hold.
    pub fn poll(&self, sock: u32, interest: u32, timeout_ms: u32) -> Result<u32> {
        let timeout_ms = clamp_timeout(timeout_ms);
        let body = wire::encode_poll_args(&wire::PollArgs {
            sock,
            interest,
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        let reply = self.parking(wire::METHOD_POLL, body, timeout_ms)?;
        Ok(wire::decode_poll_reply(&reply.body)
            .map_err(Error::Parcel)?
            .ready)
    }

    pub fn shutdown(&self, sock: u32, how: u32) -> Result<()> {
        let body =
            wire::encode_shutdown_args(&wire::ShutdownArgs { sock, how }).map_err(Error::Parcel)?;
        self.quick(wire::METHOD_SHUTDOWN, body).map(|_| ())
    }

    pub fn local_addr(&self, sock: u32) -> Result<Addr> {
        let body =
            wire::encode_local_addr_args(&wire::LocalAddrArgs { sock }).map_err(Error::Parcel)?;
        let reply = self.quick(wire::METHOD_LOCALADDR, body)?;
        Addr::from_wire(
            &wire::decode_local_addr_reply(&reply.body)
                .map_err(Error::Parcel)?
                .addr,
        )
    }

    pub fn peer_addr(&self, sock: u32) -> Result<Addr> {
        let body =
            wire::encode_peer_addr_args(&wire::PeerAddrArgs { sock }).map_err(Error::Parcel)?;
        let reply = self.quick(wire::METHOD_PEERADDR, body)?;
        Addr::from_wire(
            &wire::decode_peer_addr_reply(&reply.body)
                .map_err(Error::Parcel)?
                .addr,
        )
    }

    pub fn close(&self, sock: u32) -> Result<()> {
        let body = wire::encode_close_args(&wire::CloseArgs { sock }).map_err(Error::Parcel)?;
        self.quick(wire::METHOD_CLOSE, body).map(|_| ())
    }

    pub fn stats(&self) -> Result<wire::SocketStats> {
        let reply = self.quick(wire::METHOD_STATS, Vec::new())?;
        Ok(wire::decode_stats_reply(&reply.body)
            .map_err(Error::Parcel)?
            .stats)
    }
}
