//! `os.lazy.net.stack.v1` client: the network stack service `netd`
//! (`idl/net.midl`, docs/networking-plan.md N2).
//!
//! The stubs are generated by `midlc`; this module adds the service name, the
//! reply framing and a blocking [`Client`]. `Ping` is the one call that parks:
//! `netd` answers it when the echo reply arrives, so the caller passes a
//! deadline (an absolute PIT tick) that covers the timeout it asked for.

use alloc::vec::Vec;

use libmessenger::{Header, Parcel, VERSION};

use super::services::error_field;
use super::{registry, Endpoint, Error, Result};
use crate::sys;

/// The generated `os.lazy.net.stack.v1` stubs.
pub use messenger_generated::os_lazy_net_stack_v1 as wire;

/// Registered service name.
pub const NAME: &str = "os.lazy.net.stack";

/// The interface id every stack parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// Extra ticks a caller waits beyond the ping's own timeout, so `netd`'s
/// timeout reply (not the kernel's deadline) is what ends a lost ping.
const DEADLINE_SLACK_TICKS: u64 = 100;

/// A parcel of `method` carrying an encoded `body`.
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        ..Parcel::default()
    }
}

/// A blocking client of the stack service.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`]; the endpoint is opened in this task's handle table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// The underlying endpoint (for callers that manage transactions
    /// themselves, like the hostile-input probe).
    pub fn endpoint(&self) -> Endpoint {
        self.endpoint
    }

    /// Run one request; a service failure comes back as its original errno.
    pub fn call_parcel(&self, request: Parcel, deadline: Option<u64>) -> Result<Parcel> {
        let reply = self.endpoint.call(&request, deadline)?;
        match error_field(&reply)? {
            Some(code) => Err(Error::Errno(-code)),
            None => Ok(reply),
        }
    }

    /// Send an arbitrary request (hostile-input tests).
    pub fn raw(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        self.call_parcel(parcel(method, body), None)
    }

    fn simple(&self, method: u32) -> Result<Parcel> {
        self.call_parcel(parcel(method, Vec::new()), None)
    }

    pub fn interfaces(&self) -> Result<Vec<wire::InterfaceInfo>> {
        let reply = self.simple(wire::METHOD_INTERFACES)?;
        Ok(wire::decode_interfaces_reply(&reply.body)
            .map_err(Error::Parcel)?
            .list)
    }

    pub fn addresses(&self) -> Result<Vec<wire::AddressInfo>> {
        let reply = self.simple(wire::METHOD_ADDRESSES)?;
        Ok(wire::decode_addresses_reply(&reply.body)
            .map_err(Error::Parcel)?
            .list)
    }

    pub fn routes(&self) -> Result<Vec<wire::RouteInfo>> {
        let reply = self.simple(wire::METHOD_ROUTES)?;
        Ok(wire::decode_routes_reply(&reply.body)
            .map_err(Error::Parcel)?
            .list)
    }

    pub fn stats(&self) -> Result<wire::StackStats> {
        let reply = self.simple(wire::METHOD_STATS)?;
        Ok(wire::decode_stats_reply(&reply.body)
            .map_err(Error::Parcel)?
            .stats)
    }

    /// The request body of a `Ping`.
    pub fn ping_body(dst: &[u8], payload_len: u32, timeout_ms: u32) -> Result<Vec<u8>> {
        wire::encode_ping_args(&wire::PingArgs {
            dst: dst.to_vec(),
            payload_len,
            timeout_ms,
        })
        .map_err(Error::Parcel)
    }

    /// One echo request to `dst` and its reply; parks until one or the other.
    pub fn ping(
        &self,
        dst: [u8; 4],
        payload_len: u32,
        timeout_ms: u32,
    ) -> Result<wire::EchoResult> {
        let body = Client::ping_body(&dst, payload_len, timeout_ms)?;
        let deadline = sys::clock() + u64::from(timeout_ms) / 10 + DEADLINE_SLACK_TICKS;
        let reply = self.call_parcel(parcel(wire::METHOD_PING, body), Some(deadline))?;
        Ok(wire::decode_ping_reply(&reply.body)
            .map_err(Error::Parcel)?
            .result)
    }

    /// Look `name` up (A records); parks until the resolver answers.
    /// `ENOENT` means the resolver says the name has no address.
    pub fn resolve(&self, name: &str, timeout_ms: u32) -> Result<Vec<[u8; 4]>> {
        let body = wire::encode_resolve_args(&wire::ResolveArgs {
            name: name.into(),
            timeout_ms,
        })
        .map_err(Error::Parcel)?;
        let deadline = sys::clock() + u64::from(timeout_ms) / 10 + DEADLINE_SLACK_TICKS;
        let reply = self.call_parcel(parcel(wire::METHOD_RESOLVE, body), Some(deadline))?;
        let reply = wire::decode_resolve_reply(&reply.body).map_err(Error::Parcel)?;
        Ok(reply
            .addrs
            .iter()
            .filter_map(|a| <[u8; 4]>::try_from(a.as_slice()).ok())
            .collect())
    }

    /// The first address of `host`: a dotted quad as it is, anything else
    /// through [`Client::resolve`].
    pub fn lookup_host(&self, host: &str, timeout_ms: u32) -> Result<[u8; 4]> {
        if let Some(addr) = super::netstd::parse_ipv4(host) {
            return Ok(addr);
        }
        self.resolve(host, timeout_ms)?
            .first()
            .copied()
            .ok_or(Error::Errno(-super::errno::ENOENT))
    }

    /// Drop the DHCP lease and ask for a new one.
    pub fn renew(&self) -> Result<()> {
        self.simple(wire::METHOD_RENEW).map(|_| ())
    }

    /// Drop and re-establish the attachment to the NIC driver.
    pub fn reattach(&self) -> Result<()> {
        self.simple(wire::METHOD_REATTACH).map(|_| ())
    }
}
