//! `pkgd` client and wire shapes (`idl/pkgd.midl`, `docs/packages.md`).
//!
//! The `os.lazy.pkgd.v1` stubs are generated by `midlc`. A failure comes back
//! as a structured error field (errno-style code plus friendly text); the text
//! is the whole point of `pkgd`'s refusals ("the system volume is not writable", "that
//! application is already installed"), so [`Failure`] keeps it where the other
//! services' clients keep only the code.

use alloc::string::String;
use alloc::vec::Vec;

use libmessenger::{Decoder, Encoder, Header, Kind, Parcel, VERSION};

use super::{errno, registry, Endpoint, Error, Result};

/// The generated `os.lazy.pkgd.v1` stubs.
pub use messenger_generated::os_lazy_pkgd_v1 as wire;

/// Registered service name.
pub const NAME: &str = "os.lazy.pkgd";

/// The interface id every `pkgd` parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;

/// The reply buffer: one Messenger buffer, which `pkgd` keeps every reply
/// within (it caps permissions and problems, see `inspect.rs`). Native programs
/// run under the Linux shim have a small heap, so it is not larger.
pub const REPLY_BUFFER: usize = super::DEFAULT_BUFFER;

pub use wire::{Installed, PackageInfo, PkgEvent, ProvisionState};

/// A refused or failed request.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Failure {
    /// Positive errno-style code (`ENOENT`, `EEXIST`, `EPERM`, ...), or the
    /// kernel's error negated for a transport failure.
    pub code: i64,
    /// Friendly text, ready to show.
    pub text: String,
}

impl From<Error> for Failure {
    fn from(error: Error) -> Failure {
        Failure {
            code: error.errno().map(|code| -code).unwrap_or(errno::EINVAL),
            text: String::from(error.message()),
        }
    }
}

/// A header for a `pkgd` parcel of `method`.
fn header(method: u32) -> Header {
    Header {
        version: VERSION,
        flags: 0,
        interface_id: INTERFACE,
        method,
        txn_id: 0,
        reply_to: 0,
        deadline_ns: 0,
    }
}

/// Wrap an encoded body in a `pkgd` parcel (also the reply builder).
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: header(method),
        body,
        objects: Vec::new(),
    }
}

/// The service's failure answer: a positive errno-style `code` and friendly
/// `text`.
pub fn error_reply(method: u32, code: i64, text: &str) -> Parcel {
    let mut body = Encoder::new();
    // A structured error field cannot overflow a fresh encoder here.
    let _ = body.error(ERROR_FIELD, code as u32, text);
    parcel(method, body.finish())
}

/// The failure a reply carries, if it is one.
fn failure_of(reply: &Parcel) -> Option<Failure> {
    let mut decoder = Decoder::new(&reply.body);
    while let Ok(Some(field)) = decoder.next() {
        if field.kind == Kind::Error && field.id == ERROR_FIELD {
            let (code, text) = field.error_parts().ok()?;
            return Some(Failure {
                code: i64::from(code),
                text: String::from(text),
            });
        }
    }
    None
}

/// A blocking client of `pkgd`.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`].
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// [`Client::connect`] retrying for a client that starts before `pkgd` is
    /// up, or while it restarts to recycle its memory.
    pub fn connect_retry(attempts: usize) -> Result<Client> {
        let mut last = Error::Errno(-errno::ENOENT);
        for _ in 0..attempts {
            match registry::resolve(NAME) {
                Ok(endpoint) => return Ok(Client { endpoint }),
                Err(error) => last = error,
            }
            super::park_tick();
        }
        Err(last)
    }

    /// One request; a service failure becomes its [`Failure`].
    fn call(&self, method: u32, body: Vec<u8>) -> core::result::Result<Parcel, Failure> {
        self.call_until(method, body, None)
    }

    /// [`Client::call`] given up at the absolute PIT tick `deadline`.
    fn call_until(
        &self,
        method: u32,
        body: Vec<u8>,
        deadline: Option<u64>,
    ) -> core::result::Result<Parcel, Failure> {
        let mut buffer = alloc::vec![0u8; REPLY_BUFFER];
        let reply = self
            .endpoint
            .call_with(&parcel(method, body), &mut buffer, deadline)?;
        match failure_of(&reply) {
            Some(failure) => Err(failure),
            None => Ok(reply),
        }
    }

    /// `Inspect(path)`: what the package at `path` declares and why it could
    /// not be installed, if it could not.
    pub fn inspect(&self, path: &str) -> core::result::Result<PackageInfo, Failure> {
        let body = wire::encode_inspect_args(&wire::InspectArgs {
            path: String::from(path),
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_INSPECT, body)?;
        Ok(wire::decode_inspect_reply(&reply.body)
            .map_err(Error::Parcel)?
            .info)
    }

    /// `Install(path)`.
    pub fn install(&self, path: &str) -> core::result::Result<Installed, Failure> {
        let body = wire::encode_install_args(&wire::InstallArgs {
            path: String::from(path),
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_INSTALL, body)?;
        Ok(wire::decode_install_reply(&reply.body)
            .map_err(Error::Parcel)?
            .app)
    }

    /// `InstallApproved(path, digest, core)`: `elevd`'s install of what an
    /// administrator approved (only `elevd` may call it).
    pub fn install_approved(
        &self,
        path: &str,
        digest: &str,
        core: bool,
    ) -> core::result::Result<Installed, Failure> {
        let body = wire::encode_install_approved_args(&wire::InstallApprovedArgs {
            path: String::from(path),
            digest: String::from(digest),
            core,
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_INSTALLAPPROVED, body)?;
        Ok(wire::decode_install_approved_reply(&reply.body)
            .map_err(Error::Parcel)?
            .app)
    }

    /// `Remove(system_name)`.
    pub fn remove(&self, system_name: &str) -> core::result::Result<(), Failure> {
        let body = wire::encode_remove_args(&wire::RemoveArgs {
            system_name: String::from(system_name),
        })
        .map_err(Error::Parcel)?;
        self.call(wire::METHOD_REMOVE, body).map(|_| ())
    }

    /// `List()`: every installed app, in install order.
    pub fn list(&self) -> core::result::Result<Vec<Installed>, Failure> {
        let reply = self.call(wire::METHOD_LIST, Vec::new())?;
        Ok(wire::decode_list_reply(&reply.body)
            .map_err(Error::Parcel)?
            .apps)
    }

    /// `Provisioned()`: whether this start's core package provisioning is
    /// over, and what it did.
    pub fn provisioned(&self) -> core::result::Result<ProvisionState, Failure> {
        self.provisioned_until(None)
    }

    /// [`Client::provisioned`] given up at the absolute PIT tick `deadline`:
    /// `pkgd` answers only between two packages, so a caller that must not
    /// hang (the compositor at boot) bounds the wait.
    pub fn provisioned_until(
        &self,
        deadline: Option<u64>,
    ) -> core::result::Result<ProvisionState, Failure> {
        let reply = self.call_until(wire::METHOD_PROVISIONED, Vec::new(), deadline)?;
        Ok(wire::decode_provisioned_reply(&reply.body)
            .map_err(Error::Parcel)?
            .state)
    }

    /// `Installed(system_name)`.
    pub fn installed(&self, system_name: &str) -> core::result::Result<Option<Installed>, Failure> {
        let body = wire::encode_installed_args(&wire::InstalledArgs {
            system_name: String::from(system_name),
        })
        .map_err(Error::Parcel)?;
        let reply = self.call(wire::METHOD_INSTALLED, body)?;
        Ok(wire::decode_installed_reply(&reply.body)
            .map_err(Error::Parcel)?
            .app)
    }
}
