//! Service name registry client and daemon protocol (issue #89). See the
//! module doc on [`crate::messenger::registry`] for the two paths into the
//! kernel table.
//!
//! The `os.lazy.messenger.registry.v1` stubs are generated by `midlc` from
//! `idl/registry.midl` into `messenger-generated`; the kernel links the same
//! stubs to serve the native gate ops, so both ends share one wire definition.

use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use libmessenger::{Decoder, Encoder, Header, Kind, Parcel, VERSION};

use super::endpoint::syscall;
use super::{errno, op, Endpoint, Error, MsgArgs, MsgResult, Result, REGISTRY_TARGET_SELF};

/// The generated `os.lazy.messenger.registry.v1` stubs.
pub use messenger_generated::os_lazy_messenger_registry_v1 as wire;

/// The bootstrap listener well-known name. The kernel publishes it at
/// boot; it is the one name every task can resolve.
pub const NAME: &str = "os.lazy.messenger.registry";

/// Registry interface id, shared with the kernel through the generated stubs.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// Structured error field id in a daemon reply body (unused by the generated
/// fields, so it can never collide with a success payload).
const ERROR_FIELD: u16 = 15;

/// Largest `List` reply the client offers the kernel. The table holds at
/// most 64 names of 128 bytes, so 32 KiB has generous room.
pub const LIST_BUFFER: usize = 32 * 1024;

/// One registered name, decoded from a list reply.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Entry {
    /// Service name.
    pub name: String,
    /// Kernel object the name refers to (diagnostic).
    pub object_id: u64,
    /// Task slot that owns the name.
    pub owner_slot: u64,
    /// Interface ids the service implements.
    pub interfaces: Vec<u64>,
    /// Remaining lease ticks; `0` when permanent.
    pub lease_remaining: u64,
}

impl From<wire::Entry> for Entry {
    fn from(entry: wire::Entry) -> Entry {
        Entry {
            name: entry.name,
            object_id: entry.object,
            owner_slot: entry.owner,
            interfaces: entry.interfaces,
            lease_remaining: entry.lease_remaining,
        }
    }
}

impl From<&Entry> for wire::Entry {
    fn from(entry: &Entry) -> wire::Entry {
        wire::Entry {
            name: entry.name.clone(),
            object: entry.object_id,
            owner: entry.owner_slot,
            interfaces: entry.interfaces.clone(),
            lease_remaining: entry.lease_remaining,
        }
    }
}

/// A header for a registry parcel of `method`.
///
/// `ALLOW_NESTED` is required on the shared bootstrap channel: a topic
/// subscriber may be parked in `next_event` (a pending transaction on the
/// same channel) while another task resolves a name, and the kernel
/// per-channel cycle check would otherwise refuse the resolve.
fn header(method: u32) -> Header {
    Header {
        version: VERSION,
        flags: libmessenger::flags::ALLOW_NESTED,
        interface_id: INTERFACE,
        method,
        txn_id: 0,
        reply_to: 0,
        deadline_ns: 0,
    }
}

/// Wrap an encoded body in a registry parcel.
fn request_parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: header(method),
        body,
        handles: Vec::new(),
        buffers: Vec::new(),
    }
}

/// A request body carrying only `name` (`Resolve` and `Unregister`).
fn name_body(name: &str) -> Result<Vec<u8>> {
    wire::encode_resolve_args(&wire::ResolveArgs { name: name.into() }).map_err(Error::Parcel)
}

/// A register body: name, endpoint handle, interface array, lease.
fn register_body(
    name: &str,
    endpoint: u64,
    interfaces: &[u64],
    lease_ticks: u64,
) -> Result<Vec<u8>> {
    wire::encode_register_args(&wire::RegisterArgs {
        name: name.into(),
        endpoint: Some(endpoint),
        interfaces: interfaces.to_vec(),
        lease_ticks,
    })
    .map_err(Error::Parcel)
}

/// Encode a parcel for the wire.
fn encode(parcel: &Parcel) -> Result<Vec<u8>> {
    let mut bytes = Vec::new();
    parcel.encode(&mut bytes).map_err(Error::Parcel)?;
    Ok(bytes)
}

/// Run one registry request through the native gate with `target` as the
/// task whose table the operation touches.
fn registry_call(op_code: u64, target: u64, parcel: &Parcel) -> Result<MsgResult> {
    let bytes = encode(parcel)?;
    let args = MsgArgs {
        txn_id: target,
        parcel_ptr: bytes.as_ptr() as u64,
        parcel_len: bytes.len() as u64,
        ..MsgArgs::default()
    };
    let mut result = MsgResult::default();
    syscall(op_code, &args, &mut result)?;
    Ok(result)
}

/// Register `endpoint` in the table on behalf of the task in slot `target`.
///
/// The direct path passes [`REGISTRY_TARGET_SELF`]; [`serve_request`]
/// passes the requester slot and the kernel checks the proxy capability.
fn register_for(
    target: u64,
    name: &str,
    endpoint: u64,
    interfaces: &[u64],
    lease_ticks: u64,
) -> Result<()> {
    let parcel = request_parcel(
        wire::METHOD_REGISTER,
        register_body(name, endpoint, interfaces, lease_ticks)?,
    );
    registry_call(op::REGISTER, target, &parcel)?;
    Ok(())
}

/// Publish `endpoint` under `name`; the caller becomes the owner. A
/// `lease_ticks` of `0` registers a permanent name.
pub fn register(
    name: &str,
    endpoint: &Endpoint,
    interfaces: &[u64],
    lease_ticks: u64,
) -> Result<()> {
    register_for(
        REGISTRY_TARGET_SELF,
        name,
        endpoint.handle(),
        interfaces,
        lease_ticks,
    )
}

/// Resolve `name` into the table of slot `target` and return the new handle.
fn resolve_for(target: u64, name: &str) -> Result<Endpoint> {
    let parcel = request_parcel(wire::METHOD_RESOLVE, name_body(name)?);
    let result = registry_call(op::RESOLVE, target, &parcel)?;
    Ok(Endpoint::from_raw(result.value))
}

/// Resolve `name`; the returned endpoint is open in this task table.
pub fn resolve(name: &str) -> Result<Endpoint> {
    resolve_for(REGISTRY_TARGET_SELF, name)
}

/// Withdraw `name` on behalf of the task in slot `target`.
fn unregister_for(target: u64, name: &str) -> Result<()> {
    let parcel = request_parcel(wire::METHOD_UNREGISTER, name_body(name)?);
    registry_call(op::UNREGISTER, target, &parcel)?;
    Ok(())
}

/// Withdraw `name`. Only its owner (or an administrator) may.
pub fn unregister(name: &str) -> Result<()> {
    unregister_for(REGISTRY_TARGET_SELF, name)
}

/// Snapshot the name table.
pub fn list() -> Result<Vec<Entry>> {
    let mut buf = vec![0u8; LIST_BUFFER];
    let args = MsgArgs {
        buf_ptr: buf.as_mut_ptr() as u64,
        buf_cap: buf.len() as u64,
        ..MsgArgs::default()
    };
    let mut result = MsgResult::default();
    syscall(op::LIST, &args, &mut result)?;
    let len = result.bytes as usize;
    if len > buf.len() {
        return Err(Error::Errno(-errno::E2BIG));
    }
    let parcel = Parcel::decode(&buf[..len]).map_err(Error::Parcel)?;
    decode_entries(&parcel)
}

/// Decode a list reply body into entries; unknown fields are skipped so a
/// newer kernel stays compatible with this client.
fn decode_entries(parcel: &Parcel) -> Result<Vec<Entry>> {
    let reply = wire::decode_list_reply(&parcel.body).map_err(Error::Parcel)?;
    Ok(reply.entries.into_iter().map(Entry::from).collect())
}

/// Encode entries into a list reply parcel (the daemon `List` answer).
fn encode_entries(entries: &[Entry]) -> Result<Parcel> {
    let reply = wire::ListReply {
        entries: entries.iter().map(wire::Entry::from).collect(),
    };
    let body = wire::encode_list_reply(&reply).map_err(Error::Parcel)?;
    Ok(request_parcel(wire::METHOD_LIST, body))
}

/// The daemon request handler: forward one registry request to the kernel
/// on behalf of `sender` (the kernel-stamped task slot), and build the
/// reply parcel.
///
/// The endpoint handle in a `Register` request is a number in the sender
/// table; the kernel reads it there, so nothing crosses tables here.
pub fn serve_request(request: &Parcel, sender: u64) -> Result<Parcel> {
    let body = &request.body;
    match request.header.method {
        wire::METHOD_REGISTER => {
            let args = wire::decode_register_args(body).map_err(Error::Parcel)?;
            // Handle `0` is valid, so an omitted endpoint is a bad request.
            let endpoint = args.endpoint.ok_or(Error::Errno(-errno::EINVAL))?;
            register_for(
                sender,
                &args.name,
                endpoint,
                &args.interfaces,
                args.lease_ticks,
            )?;
            Ok(request_parcel(wire::METHOD_REGISTER, Vec::new()))
        }
        wire::METHOD_RESOLVE => {
            let args = wire::decode_resolve_args(body).map_err(Error::Parcel)?;
            let endpoint = resolve_for(sender, &args.name)?;
            let reply = wire::ResolveReply {
                handle: endpoint.handle(),
            };
            let body = wire::encode_resolve_reply(&reply).map_err(Error::Parcel)?;
            Ok(request_parcel(wire::METHOD_RESOLVE, body))
        }
        wire::METHOD_UNREGISTER => {
            let args = wire::decode_unregister_args(body).map_err(Error::Parcel)?;
            unregister_for(sender, &args.name)?;
            Ok(request_parcel(wire::METHOD_UNREGISTER, Vec::new()))
        }
        wire::METHOD_LIST => {
            let entries = list()?;
            encode_entries(&entries)
        }
        _ => Err(Error::Errno(-errno::EINVAL)),
    }
}

/// The daemon error answer: the errno-style code plus the friendly text,
/// so the client can return a [`Error::Registry`] with a readable message.
pub fn error_reply(method: u32, error: Error) -> Parcel {
    let code = error.errno().map(|code| -code).unwrap_or(errno::EINVAL);
    let mut body = Encoder::new();
    // A structured error field cannot overflow a fresh encoder here.
    let _ = body.error(ERROR_FIELD, code as u32, error.message());
    request_parcel(method, body.finish())
}

/// The first structured error field, when the reply is a daemon failure.
fn error_field(parcel: &Parcel) -> Result<Option<i64>> {
    let mut decoder = Decoder::new(&parcel.body);
    while let Some(field) = decoder.next().map_err(Error::Parcel)? {
        if field.kind == Kind::Error && field.id == ERROR_FIELD {
            let (code, _message) = field.error_parts().map_err(Error::Parcel)?;
            return Ok(Some(code as i64));
        }
    }
    Ok(None)
}

/// A client of the `messengerd` daemon over the bootstrap channel.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve the well-known registry name and wrap its endpoint.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: resolve(NAME)?,
        })
    }

    /// The underlying daemon endpoint (diagnostics).
    pub fn endpoint(&self) -> Endpoint {
        self.endpoint
    }

    /// Run one request as a blocking call and fail on a daemon error reply.
    fn call(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        let reply = self.endpoint.call(&request_parcel(method, body), None)?;
        if let Some(code) = error_field(&reply)? {
            return Err(Error::Registry(code));
        }
        Ok(reply)
    }

    /// Register `endpoint` under `name` through the daemon. The daemon
    /// forwards the request with this task as the owner.
    pub fn register(
        &self,
        name: &str,
        endpoint: &Endpoint,
        interfaces: &[u64],
        lease_ticks: u64,
    ) -> Result<()> {
        self.call(
            wire::METHOD_REGISTER,
            register_body(name, endpoint.handle(), interfaces, lease_ticks)?,
        )?;
        Ok(())
    }

    /// Resolve `name` through the daemon; the returned endpoint is open in
    /// this task table.
    pub fn resolve(&self, name: &str) -> Result<Endpoint> {
        let reply = self.call(wire::METHOD_RESOLVE, name_body(name)?)?;
        let reply = wire::decode_resolve_reply(&reply.body).map_err(Error::Parcel)?;
        Ok(Endpoint::from_raw(reply.handle))
    }

    /// Withdraw `name` through the daemon.
    pub fn unregister(&self, name: &str) -> Result<()> {
        self.call(wire::METHOD_UNREGISTER, name_body(name)?)?;
        Ok(())
    }

    /// Snapshot the table through the daemon.
    pub fn list(&self) -> Result<Vec<Entry>> {
        let reply = self.call(wire::METHOD_LIST, Vec::new())?;
        decode_entries(&reply)
    }
}
