//! `timed` client (issue #369): the time-of-day service.
//!
//! The `os.lazy.timed.v1` stubs are generated by `midlc` from
//! `idl/timed.midl`; this module adds the service name, the reply framing and
//! a blocking [`Client`]. The service failure convention is the shared
//! structured error field ([`super::services::error_field`]).

use alloc::string::String;
use alloc::vec::Vec;

use libmessenger::{Header, Parcel, VERSION};

use super::services::error_field;
use super::{registry, Endpoint, Error, Result};

/// The generated `os.lazy.timed.v1` stubs.
pub use messenger_generated::os_lazy_timed_v1 as wire;

/// Registered service name.
pub const NAME: &str = "os.lazy.timed";

/// The interface id every `timed` parcel carries.
pub const INTERFACE: u64 = wire::INTERFACE_ID;

/// `Now()` answer.
pub use wire::NowReply as Now;

/// A parcel of `method` carrying an already-encoded `body` (request or reply).
pub fn parcel(method: u32, body: Vec<u8>) -> Parcel {
    Parcel {
        header: Header {
            version: VERSION,
            flags: 0,
            interface_id: INTERFACE,
            method,
            txn_id: 0,
            reply_to: 0,
            deadline_ns: 0,
        },
        body,
        ..Parcel::default()
    }
}

/// A blocking client of the `timed` service.
pub struct Client {
    endpoint: Endpoint,
}

impl Client {
    /// Resolve [`NAME`]; the endpoint is opened in this task's handle table.
    pub fn connect() -> Result<Client> {
        Ok(Client {
            endpoint: registry::resolve(NAME)?,
        })
    }

    /// Run one request; a service failure comes back as its original errno.
    fn call(&self, method: u32, body: Vec<u8>) -> Result<Parcel> {
        let reply = self.endpoint.call(&parcel(method, body), None)?;
        match error_field(&reply)? {
            Some(code) => Err(Error::Errno(-code)),
            None => Ok(reply),
        }
    }

    /// `Now()`: the current instant and its local-time parameters.
    pub fn now(&self) -> Result<Now> {
        let reply = self.call(wire::METHOD_NOW, Vec::new())?;
        wire::decode_now_reply(&reply.body).map_err(Error::Parcel)
    }

    /// `GetZone()`: the configured zone name.
    pub fn get_zone(&self) -> Result<String> {
        let reply = self.call(wire::METHOD_GETZONE, Vec::new())?;
        Ok(wire::decode_get_zone_reply(&reply.body)
            .map_err(Error::Parcel)?
            .name)
    }

    /// `SetZone(name)`: `EINVAL` for a zone outside the built-in table.
    pub fn set_zone(&self, name: &str) -> Result<()> {
        let body = wire::encode_set_zone_args(&wire::SetZoneArgs {
            name: String::from(name),
        })
        .map_err(Error::Parcel)?;
        self.call(wire::METHOD_SETZONE, body).map(|_| ())
    }

    /// `SetTime(unix_secs)`: `EPERM` unless the caller holds `CAP_SYS_TIME`.
    pub fn set_time(&self, unix_secs: i64) -> Result<()> {
        let body =
            wire::encode_set_time_args(&wire::SetTimeArgs { unix_secs }).map_err(Error::Parcel)?;
        self.call(wire::METHOD_SETTIME, body).map(|_| ())
    }
}
