//! Composing `target/lazyos.img` (docs/filesystem-plan.md F2): the BIOS part
//! from `bootloader` (MBR, stage 2, the FAT `/boot` with the kernel and
//! `lazyos.cfg`) plus an ext2 OS volume, written by `libs/ext2fs`, holding
//! everything else.
//!
//! Embed modules add files through [`Sink`]; [`OsFiles`] collects them into the
//! OS file list. A rebuild *updates* an existing image in place (see
//! [`compose`]) so installed apps, settings and logs survive, and the
//! `/system/.image-manifest` it keeps is the only record of what an update may
//! replace or delete.

use std::collections::BTreeMap;
use std::fs::OpenOptions;
use std::path::{Path, PathBuf};

use ext2fs::{Ext2, Ext2Error, Geometry, Recovery};

use crate::os_disk::{self, FileIo, OS_START_LBA, SECTOR};
use crate::os_layout::{self, DirSpec, MANIFEST_PATH};
pub use crate::os_manifest::{clean_path, Kind, Manifest};

/// Where a file's bytes come from.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Source {
    Path(PathBuf),
    Bytes(Vec<u8>),
}

/// One file of the OS volume: its absolute path, bytes and mode (root-owned).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OsFile {
    pub path: String,
    pub source: Source,
    pub mode: u16,
}

/// Where the embed modules put the files they select.
pub trait Sink {
    /// Add `path` (relative to the volume root, or absolute) with `mode`. A
    /// later entry for the same path replaces the earlier one.
    fn add(&mut self, path: &str, source: Source, mode: u16);

    /// Add the file at `source`, with the mode its name implies.
    fn add_file(&mut self, path: &str, source: PathBuf) {
        self.add(path, Source::Path(source), os_layout::file_mode(path));
    }

    /// Add generated `bytes`, with the mode its name implies.
    fn add_bytes(&mut self, path: &str, bytes: Vec<u8>) {
        self.add(path, Source::Bytes(bytes), os_layout::file_mode(path));
    }
}

/// The OS file list.
#[derive(Default)]
pub struct OsFiles {
    files: BTreeMap<String, OsFile>,
}

impl OsFiles {
    pub fn files(&self) -> Vec<OsFile> {
        self.files.values().cloned().collect()
    }

    pub fn len(&self) -> usize {
        self.files.len()
    }
}

impl Sink for OsFiles {
    fn add(&mut self, path: &str, source: Source, mode: u16) {
        match clean_path(path) {
            Some(path) => {
                let file = OsFile {
                    path: path.clone(),
                    source,
                    mode,
                };
                self.files.insert(path, file);
            }
            None => println!("cargo:warning=skipping {path:?}: not a usable image path"),
        }
    }
}

/// `lazyos.cfg` for the FAT `/boot` volume.
pub fn boot_cfg(uuid: [u8; 16]) -> String {
    format!(
        "# Generated by the image build.\nroot=UUID={}\nhome=LABEL=lazyhome\n",
        format_uuid(uuid)
    )
}

/// The 36-character `8-4-4-4-12` form the kernel parses.
pub fn format_uuid(uuid: [u8; 16]) -> String {
    let hex: String = uuid.iter().map(|byte| format!("{byte:02x}")).collect();
    format!(
        "{}-{}-{}-{}-{}",
        &hex[..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..]
    )
}

/// A random version 4 UUID (std only: the build has no `rand`).
pub fn new_uuid() -> [u8; 16] {
    use std::hash::{BuildHasher, Hasher};
    let mut out = [0u8; 16];
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_nanos());
    for (index, half) in out.chunks_mut(8).enumerate() {
        let mut hasher = std::collections::hash_map::RandomState::new().build_hasher();
        hasher.write_u128(seed);
        hasher.write_u32(std::process::id());
        hasher.write_usize(index);
        half.copy_from_slice(&hasher.finish().to_le_bytes());
    }
    out[6] = out[6] & 0x0F | 0x40;
    out[8] = out[8] & 0x3F | 0x80;
    out
}

/// What [`plan`] decided.
#[derive(Debug, PartialEq, Eq)]
pub enum Action {
    /// Format a new OS volume.
    Create,
    /// Update the existing one, whose build-placed paths are `manifest`.
    Update { manifest: Manifest },
}

/// The decision, the UUID the boot config must carry, and (when a new volume
/// replaces something the user may not expect) why.
#[derive(Debug)]
pub struct Plan {
    pub action: Action,
    pub uuid: [u8; 16],
    pub warning: Option<String>,
}

/// Build settings from the environment.
#[derive(Clone, Copy, Debug)]
pub struct Settings {
    pub os_size: u64,
    pub reset: bool,
}

const RESET_HINT: &str = "set LAZYOS_RESET_OS=1 to recreate the OS volume";

/// Create or update? Create when `image` is missing, `settings.reset` is set,
/// or it fails [`validate`] (with the reason as a warning); otherwise update,
/// keeping its UUID. A size change of a valid image is an error: resizing is
/// not supported.
pub fn plan(image: &Path, settings: &Settings) -> Result<Plan, String> {
    let fresh = |warning: Option<String>| Plan {
        action: Action::Create,
        uuid: new_uuid(),
        warning,
    };
    if settings.reset {
        return Ok(fresh(Some(
            "LAZYOS_RESET_OS=1: creating a new OS volume".into(),
        )));
    }
    if !image.exists() {
        return Ok(fresh(None));
    }
    match validate(image) {
        Ok((uuid, manifest, sectors)) => {
            if sectors != settings.os_size / SECTOR {
                return Err(format!(
                    "{} has an OS volume of {} MiB but LAZYOS_OS_SIZE asks for {} MiB; \
                     resizing is not supported, {RESET_HINT}",
                    image.display(),
                    (sectors * SECTOR) >> 20,
                    settings.os_size >> 20
                ));
            }
            Ok(Plan {
                action: Action::Update { manifest },
                uuid,
                warning: None,
            })
        }
        Err(reason) => Ok(fresh(Some(format!(
            "{} is not a current OS image ({reason}); creating a new one",
            image.display()
        )))),
    }
}

/// Check an existing image: MBR entry 3 is type 0x83 at the fixed start, the
/// volume has the ext2 magic, and `/system/.image-manifest` reads. Returns the
/// UUID, the manifest and the volume's sector count.
pub fn validate(image: &Path) -> Result<([u8; 16], Manifest, u64), String> {
    let mut file = OpenOptions::new()
        .read(true)
        .open(image)
        .map_err(|e| format!("cannot read it: {e}"))?;
    let mut mbr = [0u8; 512];
    std::io::Read::read_exact(&mut file, &mut mbr).map_err(|e| format!("no MBR: {e}"))?;
    if !os_disk::has_signature(&mbr) {
        return Err("no MBR signature".into());
    }
    let (kind, start, sectors) = os_disk::mbr_entry(&mbr, 3).ok_or("no MBR entry 3")?;
    if kind != os_disk::OS_PART_TYPE || start != OS_START_LBA || sectors == 0 {
        return Err("MBR entry 3 is not the OS volume".into());
    }
    let length = file.metadata().map_err(|e| e.to_string())?.len();
    if length != (start + sectors) * SECTOR {
        return Err("the file size does not match MBR entry 3".into());
    }
    let io = FileIo::new(file, start, sectors, false);
    let volume = Ext2::open(Box::new(io), now).map_err(|e| format!("not ext2: {e:?}"))?;
    let text = volume
        .read_file(MANIFEST_PATH)
        .map_err(|e| format!("no readable {MANIFEST_PATH}: {e:?}"))?;
    let text = String::from_utf8(text).map_err(|_| "the manifest is not UTF-8".to_string())?;
    Ok((volume.uuid(), Manifest::parse(&text)?, sectors))
}

/// UTC seconds, the clock the volume stamps inodes with.
pub fn now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_secs() as i64)
}

fn volume_error(what: &str, error: Ext2Error) -> String {
    format!("{what}: {error:?}")
}

/// Write the file list into `volume` and return the manifest it placed.
///
/// With `old` (an update): delete what the old manifest placed and the new one
/// does not (files are unlinked, directories removed only when empty, so
/// anything a user keeps there survives), then write every file of `files`
/// (replace = truncate + write), and finally the manifest, then flush. A path
/// that is in neither manifest is never touched.
pub fn write_volume(
    volume: &Ext2,
    old: Option<&Manifest>,
    dirs: &[DirSpec],
    files: &[OsFile],
    stamp: i64,
) -> Result<Manifest, String> {
    let manifest = Manifest::of(dirs, files)?;
    for (path, kind) in old.map(|old| old.removed_by(&manifest)).unwrap_or_default() {
        let result = match kind {
            Kind::File => volume.unlink(&path),
            Kind::Dir => volume.rmdir(&path),
        };
        match result {
            // Already gone, or a directory a user put things in: leave it.
            Ok(())
            | Err(Ext2Error::NotFound | Ext2Error::NotEmpty | Ext2Error::NotDir)
            | Err(Ext2Error::IsDir) => {}
            Err(error) => return Err(volume_error(&format!("remove {path}"), error)),
        }
    }
    for dir in dirs {
        volume
            .mkdir_p(&dir.path, dir.mode, dir.uid, dir.gid)
            .map_err(|e| volume_error(&format!("mkdir {}", dir.path), e))?;
    }
    for file in files {
        let parent = file.path.rsplit_once('/').map_or("/", |(parent, _)| parent);
        volume
            .mkdir_p(if parent.is_empty() { "/" } else { parent }, 0o755, 0, 0)
            .map_err(|e| volume_error(&format!("mkdir {parent}"), e))?;
        let bytes = match &file.source {
            Source::Bytes(bytes) => bytes.clone(),
            Source::Path(path) => std::fs::read(path)
                .map_err(|e| format!("read {} for {}: {e}", path.display(), file.path))?,
        };
        volume
            .write_file(&file.path, &bytes, file.mode, 0, 0, stamp)
            .map_err(|e| volume_error(&format!("write {}", file.path), e))?;
    }
    volume
        .write_file(
            MANIFEST_PATH,
            manifest.to_text().as_bytes(),
            0o644,
            0,
            0,
            stamp,
        )
        .map_err(|e| volume_error("write the manifest", e))?;
    volume.flush().map_err(|e| volume_error("flush", e))?;
    Ok(manifest)
}

/// Write `bios` (the bootloader's image) and the OS volume to `image`, as
/// `plan` decided: a new file renamed into place, or an update in place.
pub fn compose(
    plan: &Plan,
    image: &Path,
    bios: &[u8],
    settings: &Settings,
    dirs: &[DirSpec],
    files: &[OsFile],
) -> Result<(), String> {
    os_disk::check_boot_fits(bios)?;
    let mut head = bios.to_vec();
    os_disk::add_os_entry(&mut head[..512], settings.os_size);
    let total = OS_START_LBA * SECTOR + settings.os_size;
    let sectors = settings.os_size / SECTOR;
    match &plan.action {
        Action::Create => {
            let temp = image.with_file_name(format!(
                "{}.tmp",
                image
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("lazyos.img")
            ));
            let result = create(&temp, &head, plan.uuid, total, sectors, dirs, files);
            if let Err(error) = result {
                let _ = std::fs::remove_file(&temp);
                return Err(error);
            }
            std::fs::rename(&temp, image).map_err(|e| {
                format!(
                    "cannot replace {} ({e}); is QEMU running on it? Stop it and retry",
                    image.display()
                )
            })
        }
        Action::Update { manifest } => update(image, &head, total, sectors, manifest, dirs, files),
    }
}

fn create(
    temp: &Path,
    head: &[u8],
    uuid: [u8; 16],
    total: u64,
    sectors: u64,
    dirs: &[DirSpec],
    files: &[OsFile],
) -> Result<(), String> {
    let mut file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(true)
        .open(temp)
        .map_err(|e| format!("create {}: {e}", temp.display()))?;
    file.set_len(total).map_err(|e| e.to_string())?;
    write_head(&mut file, head, 0)?;
    let io = FileIo::new(file, OS_START_LBA, sectors, true);
    let geometry = Geometry::for_size(sectors * SECTOR);
    ext2fs::format(&io, geometry, "lazyos", uuid, now()).map_err(|e| volume_error("format", e))?;
    let volume = Ext2::open(Box::new(io), now).map_err(|e| volume_error("open", e))?;
    write_volume(&volume, None, dirs, files, now())?;
    Ok(())
}

fn update(
    image: &Path,
    head: &[u8],
    total: u64,
    sectors: u64,
    old: &Manifest,
    dirs: &[DirSpec],
    files: &[OsFile],
) -> Result<(), String> {
    let mut options = OpenOptions::new();
    options.read(true).write(true);
    #[cfg(windows)]
    std::os::windows::fs::OpenOptionsExt::share_mode(&mut options, 1); // others may only read
    let mut file = options.open(image).map_err(|e| {
        format!(
            "cannot update {} in place ({e}); is QEMU running on it? Stop it and retry",
            image.display()
        )
    })?;
    if let Err(error) = file.try_lock() {
        return Err(format!(
            "{} is locked ({error:?}); stop whatever is using it and retry",
            image.display()
        ));
    }
    if file.metadata().map_err(|e| e.to_string())?.len() != total {
        return Err(format!("{} changed size; {RESET_HINT}", image.display()));
    }
    let old_end = old_fat_end(&mut file)?;
    write_head(&mut file, head, old_end)?;
    let io = FileIo::new(file, OS_START_LBA, sectors, true);
    let mut volume = Ext2::open(Box::new(io), now).map_err(|e| volume_error("open", e))?;
    recover(&mut volume)?;
    write_volume(&volume, Some(old), dirs, files, now())?;
    Ok(())
}

/// Check a volume that stopped uncleanly (a QEMU window closed, a crash) so
/// the update's closing flush can mark it clean again. The kernel never does:
/// it has no fsck, and restores the state it found at every shutdown, so
/// without this one unclean stop would flag the image for good. A volume that
/// fails the check stays flagged, with a warning; nothing is deleted.
fn recover(volume: &mut Ext2) -> Result<(), String> {
    match volume
        .recover(ext2fs::ORPHAN_PREFIX)
        .map_err(|e| volume_error("check", e))?
    {
        Recovery::WasClean => {}
        Recovery::Recovered { reclaimed } => println!(
            "cargo:warning=the OS volume was not cleanly unmounted; checked it, \
             reclaimed {reclaimed} orphaned file(s), and it is clean again"
        ),
        Recovery::StillUnclean(reason) => println!(
            "cargo:warning=the OS volume was not cleanly unmounted and stays flagged: \
             {reason}; {RESET_HINT}"
        ),
    }
    Ok(())
}

/// Byte offset where the image's current FAT volume ends (MBR entry 2).
fn old_fat_end(file: &mut std::fs::File) -> Result<u64, String> {
    use std::io::{Read, Seek, SeekFrom};
    let mut mbr = [0u8; 512];
    file.seek(SeekFrom::Start(0))
        .and_then(|_| file.read_exact(&mut mbr))
        .map_err(|e| format!("read the MBR: {e}"))?;
    Ok(os_disk::mbr_entry(&mbr, 2).map_or(0, |(_, start, sectors)| (start + sectors) * SECTOR))
}

/// Write the BIOS part over LBA 0 and zero up to `zero_to` bytes (the end of
/// the previous FAT volume, never past the OS volume), so a smaller `/boot`
/// leaves no stale bytes behind.
fn write_head(file: &mut std::fs::File, head: &[u8], zero_to: u64) -> Result<(), String> {
    use std::io::{Seek, SeekFrom, Write};
    let limit = (OS_START_LBA * SECTOR) as usize;
    let mut padded = head.to_vec();
    padded.resize(head.len().max((zero_to as usize).min(limit)), 0);
    file.seek(SeekFrom::Start(0)).map_err(|e| e.to_string())?;
    file.write_all(&padded)
        .and_then(|()| file.flush())
        .map_err(|e| format!("write the boot area: {e}"))
}
