//! Composing `target/lazyos.img` (docs/filesystem-plan.md F2): the BIOS part
//! from `bootloader` (MBR, stage 2, the FAT `/boot` with the kernel and
//! `lazyos.cfg`) plus an ext2 OS volume, written by `libs/ext2fs`, holding
//! everything else.
//!
//! Embed modules add files through [`Sink`]; [`OsFiles`] collects them into the
//! OS file list. A rebuild *updates* an existing image in place (see
//! [`compose`]) so installed apps, settings and logs survive, and the
//! `/system/.image-manifest` it keeps is the only record of what an update may
//! replace or delete.

use std::collections::BTreeMap;
use std::fs::OpenOptions;
use std::path::{Path, PathBuf};

use ext2fs::{AttrChange, Ext2, Ext2Error};

use crate::os_disk::{self, FileIo, OS_START_LBA, SECTOR};
use crate::os_layout::{self, DirSpec, MANIFEST_PATH};
pub use crate::os_manifest::{clean_path, Kind, Manifest};

#[path = "display_cfg.rs"]
pub mod display_cfg;
#[path = "limits_cfg.rs"]
pub mod limits_cfg;
#[path = "os_compose.rs"]
mod os_compose;

use os_compose::{create, update};

/// Where a file's bytes come from.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Source {
    Path(PathBuf),
    Bytes(Vec<u8>),
}

/// One file of the OS volume: its absolute path, bytes, mode and owner.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OsFile {
    pub path: String,
    pub source: Source,
    pub mode: u16,
    /// Owner and how the build places it ([`Placement::ROOT`] for nearly
    /// every file).
    pub placement: Placement,
}

/// Who owns a placed file, and whether an update may replace it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Placement {
    pub uid: u32,
    pub gid: u32,
    /// A seed: written only when the path does not exist yet, and never
    /// listed in the manifest, so an update neither replaces nor deletes
    /// it (the account database a running system keeps changing).
    pub seed: bool,
}

impl Placement {
    /// A root-owned file the build owns: replaced by every update.
    pub const ROOT: Placement = Placement {
        uid: 0,
        gid: 0,
        seed: false,
    };

    /// A file owned by `uid`/`gid`, replaced by every update.
    pub const fn owned(uid: u32, gid: u32) -> Placement {
        Placement {
            uid,
            gid,
            seed: false,
        }
    }

    /// A seed owned by `uid`/`gid`: written once, then the system's.
    pub const fn seed(uid: u32, gid: u32) -> Placement {
        Placement {
            uid,
            gid,
            seed: true,
        }
    }
}

/// Where the embed modules put the files they select.
pub trait Sink {
    /// Add `path` (relative to the volume root, or absolute) with `mode`. A
    /// later entry for the same path replaces the earlier one.
    fn add(&mut self, path: &str, source: Source, mode: u16) {
        self.add_placed(path, source, mode, Placement::ROOT);
    }

    /// [`Sink::add`] with an owner other than root, or as a seed.
    fn add_placed(&mut self, path: &str, source: Source, mode: u16, placement: Placement);

    /// Add the file at `source`, with the mode its name implies.
    fn add_file(&mut self, path: &str, source: PathBuf) {
        self.add(path, Source::Path(source), os_layout::file_mode(path));
    }

    /// Add generated `bytes`, with the mode its name implies.
    fn add_bytes(&mut self, path: &str, bytes: Vec<u8>) {
        self.add(path, Source::Bytes(bytes), os_layout::file_mode(path));
    }
}

/// The OS file list.
#[derive(Default)]
pub struct OsFiles {
    files: BTreeMap<String, OsFile>,
}

impl OsFiles {
    pub fn files(&self) -> Vec<OsFile> {
        self.files.values().cloned().collect()
    }

    pub fn len(&self) -> usize {
        self.files.len()
    }
}

impl Sink for OsFiles {
    fn add_placed(&mut self, path: &str, source: Source, mode: u16, placement: Placement) {
        match clean_path(path) {
            Some(path) => {
                let file = OsFile {
                    path: path.clone(),
                    source,
                    mode,
                    placement,
                };
                self.files.insert(path, file);
            }
            None => println!("cargo:warning=skipping {path:?}: not a usable image path"),
        }
    }
}

/// `lazyos.cfg` for the FAT `/boot` volume, with the `limit.*` lines for
/// `limits` (`LAZYOS_LIMIT_*`, [`limits_cfg::from_env`]).
pub fn boot_cfg(uuid: [u8; 16], limits: &[(String, String)]) -> String {
    format!(
        "# Generated by the image build.\nroot=UUID={}\nhome=LABEL=lazyhome\n{}",
        format_uuid(uuid),
        limits_cfg::lines(limits)
    )
}

/// The 36-character `8-4-4-4-12` form the kernel parses.
pub fn format_uuid(uuid: [u8; 16]) -> String {
    let hex: String = uuid.iter().map(|byte| format!("{byte:02x}")).collect();
    format!(
        "{}-{}-{}-{}-{}",
        &hex[..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..]
    )
}

/// A random version 4 UUID (std only: the build has no `rand`).
pub fn new_uuid() -> [u8; 16] {
    use std::hash::{BuildHasher, Hasher};
    let mut out = [0u8; 16];
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_nanos());
    for (index, half) in out.chunks_mut(8).enumerate() {
        let mut hasher = std::collections::hash_map::RandomState::new().build_hasher();
        hasher.write_u128(seed);
        hasher.write_u32(std::process::id());
        hasher.write_usize(index);
        half.copy_from_slice(&hasher.finish().to_le_bytes());
    }
    out[6] = out[6] & 0x0F | 0x40;
    out[8] = out[8] & 0x3F | 0x80;
    out
}

/// What [`plan`] decided.
#[derive(Debug, PartialEq, Eq)]
pub enum Action {
    /// Format a new OS volume.
    Create,
    /// Update the existing one, whose build-placed paths are `manifest`.
    Update { manifest: Manifest },
}

/// The decision, the UUID the boot config must carry, and (when a new volume
/// replaces something the user may not expect) why.
#[derive(Debug)]
pub struct Plan {
    pub action: Action,
    pub uuid: [u8; 16],
    pub warning: Option<String>,
}

/// Build settings from the environment.
#[derive(Clone, Copy, Debug)]
pub struct Settings {
    pub os_size: u64,
    pub reset: bool,
    /// `LAZYOS_UPDATE_DAMAGED_OS=1`: update a volume whose damage `recover`
    /// refused to repair instead of failing the build. Its allocator may then
    /// hand a block a user file still uses to an updated file.
    pub update_damaged: bool,
    /// `LAZYOS_JOURNAL`: give the volume a journal of this many blocks (see
    /// [`journal_blocks`]); `None` leaves the volume as it is.
    pub journal: Option<u32>,
}

pub(crate) const RESET_HINT: &str = "set LAZYOS_RESET_OS=1 to recreate the OS volume";

/// Create or update? Create when `image` is missing, `settings.reset` is set,
/// or it fails [`validate`] (with the reason as a warning); otherwise update,
/// keeping its UUID. A size change of a valid image is an error: resizing is
/// not supported.
pub fn plan(image: &Path, settings: &Settings) -> Result<Plan, String> {
    let fresh = |warning: Option<String>| Plan {
        action: Action::Create,
        uuid: new_uuid(),
        warning,
    };
    if settings.reset {
        return Ok(fresh(Some(
            "LAZYOS_RESET_OS=1: creating a new OS volume".into(),
        )));
    }
    if !image.exists() {
        return Ok(fresh(None));
    }
    match validate(image) {
        Ok((uuid, manifest, sectors)) => {
            if sectors != settings.os_size / SECTOR {
                return Err(format!(
                    "{} has an OS volume of {} MiB but LAZYOS_OS_SIZE asks for {} MiB; \
                     resizing is not supported, {RESET_HINT}",
                    image.display(),
                    (sectors * SECTOR) >> 20,
                    settings.os_size >> 20
                ));
            }
            Ok(Plan {
                action: Action::Update { manifest },
                uuid,
                warning: None,
            })
        }
        Err(reason) => Ok(fresh(Some(format!(
            "{} is not a current OS image ({reason}); creating a new one",
            image.display()
        )))),
    }
}

/// Check an existing image: MBR entry 3 is type 0x83 at the fixed start, the
/// volume has the ext2 magic, and `/system/.image-manifest` reads. Returns the
/// UUID, the manifest and the volume's sector count.
pub fn validate(image: &Path) -> Result<([u8; 16], Manifest, u64), String> {
    let mut file = OpenOptions::new()
        .read(true)
        .open(image)
        .map_err(|e| format!("cannot read it: {e}"))?;
    let mut mbr = [0u8; 512];
    std::io::Read::read_exact(&mut file, &mut mbr).map_err(|e| format!("no MBR: {e}"))?;
    if !os_disk::has_signature(&mbr) {
        return Err("no MBR signature".into());
    }
    let (kind, start, sectors) = os_disk::mbr_entry(&mbr, 3).ok_or("no MBR entry 3")?;
    if kind != os_disk::OS_PART_TYPE || start != OS_START_LBA || sectors == 0 {
        return Err("MBR entry 3 is not the OS volume".into());
    }
    let length = file.metadata().map_err(|e| e.to_string())?.len();
    if length != (start + sectors) * SECTOR {
        return Err("the file size does not match MBR entry 3".into());
    }
    let io = FileIo::new(file, start, sectors, false);
    let volume = Ext2::open(Box::new(io), now).map_err(|e| format!("not ext2: {e:?}"))?;
    let text = volume
        .read_file(MANIFEST_PATH)
        .map_err(|e| format!("no readable {MANIFEST_PATH}: {e:?}"))?;
    let text = String::from_utf8(text).map_err(|_| "the manifest is not UTF-8".to_string())?;
    Ok((volume.uuid(), Manifest::parse(&text)?, sectors))
}

/// UTC seconds, the clock the volume stamps inodes with.
pub fn now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_secs() as i64)
}

pub(crate) fn volume_error(what: &str, error: Ext2Error) -> String {
    format!("{what}: {error:?}")
}

/// Mount the OS volume for writing through a 64 MiB block cache: the build
/// then writes each block once, in large requests, instead of rewriting the
/// bitmaps and counters for every block it allocates.
fn open_cached(io: FileIo) -> Result<Ext2, String> {
    let mut config = ext2fs::CacheConfig::heap(16 * 1024);
    config.max_request = 1 << 20;
    Ext2::open_cached(Box::new(io), now, config).map_err(|e| volume_error("open", e))
}

/// Journal blocks of `LAZYOS_JOURNAL=1`: 16 MiB at the default 4 KiB blocks.
pub const DEFAULT_JOURNAL_BLOCKS: u32 = 4096;

/// What `LAZYOS_JOURNAL` asks for: unset, empty or `0` is no journal, `1` the
/// default size, any larger number that many blocks (at least
/// [`ext2fs::MIN_JOURNAL_BLOCKS`]).
pub fn journal_blocks(text: Option<&str>) -> Result<Option<u32>, String> {
    let text = text.unwrap_or("").trim();
    let blocks: u32 = match text {
        "" | "0" => return Ok(None),
        "1" => DEFAULT_JOURNAL_BLOCKS,
        other => other
            .parse()
            .map_err(|_| format!("LAZYOS_JOURNAL={other:?} is not a block count"))?,
    };
    if blocks < ext2fs::MIN_JOURNAL_BLOCKS {
        return Err(format!(
            "LAZYOS_JOURNAL={blocks}: a journal needs at least {} blocks",
            ext2fs::MIN_JOURNAL_BLOCKS
        ));
    }
    Ok(Some(blocks))
}

/// Give `volume` the journal [`journal_blocks`] asked for, when it has none.
/// A volume that has one keeps it whatever its size: resizing is not supported.
pub fn ensure_journal(volume: &Ext2, blocks: Option<u32>) -> Result<(), String> {
    match blocks {
        Some(blocks) if !volume.has_journal() => volume
            .add_journal(blocks)
            .map_err(|e| volume_error("add the journal", e)),
        _ => Ok(()),
    }
}

/// Write the file list into `volume` and return the manifest it placed.
///
/// With `old` (an update): delete what the old manifest placed and the new one
/// does not (files are unlinked, directories removed only when empty, so
/// anything a user keeps there survives), then write every file of `files`
/// (replace = truncate + write), and finally the manifest, then flush. A path
/// that is in neither manifest is never touched.
pub fn write_volume(
    volume: &Ext2,
    old: Option<&Manifest>,
    dirs: &[DirSpec],
    files: &[OsFile],
    stamp: i64,
) -> Result<Manifest, String> {
    let manifest = Manifest::of(dirs, files)?;
    for (path, kind) in old.map(|old| old.removed_by(&manifest)).unwrap_or_default() {
        let result = match kind {
            Kind::File => volume.unlink(&path),
            Kind::Dir => volume.rmdir(&path),
        };
        match result {
            // Already gone, or a directory a user put things in: leave it.
            Ok(())
            | Err(Ext2Error::NotFound | Ext2Error::NotEmpty | Ext2Error::NotDir)
            | Err(Ext2Error::IsDir) => {}
            Err(error) => return Err(volume_error(&format!("remove {path}"), error)),
        }
    }
    for dir in dirs {
        volume
            .mkdir_p(&dir.path, dir.mode, dir.uid, dir.gid)
            .map_err(|e| volume_error(&format!("mkdir {}", dir.path), e))?;
        // An existing directory keeps the mode an older table gave it unless
        // it is applied again (`/logs` 0755 -> 0750 in F4).
        let change = AttrChange {
            mode: Some(dir.mode),
            uid: Some(dir.uid),
            gid: Some(dir.gid),
            ..AttrChange::default()
        };
        volume
            .setattr(&dir.path, &change)
            .map_err(|e| volume_error(&format!("chmod {}", dir.path), e))?;
    }
    for file in files {
        // A seed the system already has is the system's now.
        if file.placement.seed && volume.lookup(&file.path).is_ok() {
            continue;
        }
        let parent = file.path.rsplit_once('/').map_or("/", |(parent, _)| parent);
        volume
            .mkdir_p(if parent.is_empty() { "/" } else { parent }, 0o755, 0, 0)
            .map_err(|e| volume_error(&format!("mkdir {parent}"), e))?;
        let bytes = match &file.source {
            Source::Bytes(bytes) => bytes.clone(),
            Source::Path(path) => std::fs::read(path)
                .map_err(|e| format!("read {} for {}: {e}", path.display(), file.path))?,
        };
        let Placement { uid, gid, .. } = file.placement;
        volume
            .write_file(&file.path, &bytes, file.mode, uid, gid, stamp)
            .map_err(|e| volume_error(&format!("write {}", file.path), e))?;
    }
    // Everything else is on the disk before the manifest that lists it: the
    // cache would otherwise write them back together.
    volume.flush().map_err(|e| volume_error("flush", e))?;
    volume
        .write_file(
            MANIFEST_PATH,
            manifest.to_text().as_bytes(),
            0o644,
            0,
            0,
            stamp,
        )
        .map_err(|e| volume_error("write the manifest", e))?;
    volume.flush().map_err(|e| volume_error("flush", e))?;
    Ok(manifest)
}

/// Write `bios` (the bootloader's image) and the OS volume to `image`, as
/// `plan` decided: a new file renamed into place, or an update in place.
pub fn compose(
    plan: &Plan,
    image: &Path,
    bios: &[u8],
    settings: &Settings,
    dirs: &[DirSpec],
    files: &[OsFile],
) -> Result<(), String> {
    os_disk::check_boot_fits(bios)?;
    let mut head = bios.to_vec();
    os_disk::add_os_entry(&mut head[..512], settings.os_size);
    match &plan.action {
        Action::Create => {
            let temp = image.with_file_name(format!(
                "{}.tmp",
                image
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("lazyos.img")
            ));
            let result = create(&temp, &head, plan.uuid, settings, dirs, files);
            if let Err(error) = result {
                let _ = std::fs::remove_file(&temp);
                return Err(error);
            }
            std::fs::rename(&temp, image).map_err(|e| {
                format!(
                    "cannot replace {} ({e}); is QEMU running on it? Stop it and retry",
                    image.display()
                )
            })
        }
        Action::Update { manifest } => update(image, &head, manifest, settings, dirs, files),
    }
}
