use std::env;
use std::fs;
use std::path::Path;

/// Pixel size the chrome faces are rasterized at (window titles, taskbar,
/// menus), and the UI scales they are rasterized for: each scale gets its
/// own atlas at `CHROME_PX * scale`, so 2x text is hinted at its real size
/// instead of upscaled (docs/hidpi-plan.md).
const CHROME_PX: f32 = 13.0;
const SCALES: [u32; 2] = [1, 2];

/// Rasterize the bundled proportional faces into `typeface_data.rs`, included
/// by `src/messenger/display/typeface.rs`.
fn generate_typefaces(manifest: &str) {
    let out_dir = env::var("OUT_DIR").expect("out dir");
    let mut src = String::from("// @generated by user/build.rs -- do not edit by hand.\n");
    let faces = [
        ("SANS", "DroidSans.ttf"),
        ("SERIF", "DroidSerif-Regular.ttf"),
    ];
    for ((face, file), scale) in faces
        .into_iter()
        .flat_map(|face| SCALES.map(|scale| (face, scale)))
    {
        let name = format!("{face}_{scale}X");
        let path = Path::new(manifest).join("../assets/fonts").join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {file}: {e}"));
        let atlas = font_atlas::build(&bytes, CHROME_PX * scale as f32);
        let blob = format!("typeface_{}.bin", name.to_lowercase());
        fs::write(Path::new(&out_dir).join(&blob), &atlas.coverage).expect("write coverage");
        src.push_str(&format!(
            "pub static {name}: FaceData = FaceData {{\n    ascender: {},\n    descender: {},\n    line_height: {},\n    glyphs: &[\n",
            atlas.ascender, atlas.descender, atlas.line_height
        ));
        for g in &atlas.glyphs {
            src.push_str(&format!(
                "        Glyph {{ width: {}, height: {}, left: {}, top: {}, offset: {}, advance_x16: {} }},\n",
                g.width, g.height, g.left, g.top, g.offset, g.advance_x16
            ));
        }
        src.push_str(&format!(
            "    ],\n    coverage: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{blob}\")),\n}};\n"
        ));
    }
    fs::write(Path::new(&out_dir).join("typeface_data.rs"), src).expect("write typeface data");
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    // Link the program as a static (non-PIE) ELF64 at a fixed base with our own
    // entry point.
    println!("cargo:rustc-link-arg=-T{manifest}/link.ld");
    println!("cargo:rustc-link-arg=-no-pie");
    println!("cargo:rustc-link-arg=-static");
    println!("cargo:rerun-if-changed=link.ld");
    println!("cargo:rerun-if-changed=build.rs");
    generate_typefaces(&manifest);
    // `inputd` boots into this layout when `confd` holds none (`option_env!`).
    println!("cargo:rerun-if-env-changed=LAZYOS_KBD_LAYOUT");

    // Desktop profile (issue #217): `LAZYOS_DESKTOP=1` marks the image as a
    // user-facing desktop. `init` reads `cfg(lazyos_desktop)` to keep the
    // demo/evidence-only programs (the crash test, the clipboard demo pair, the
    // `top` launch self-test) out of the boot, so the profile's behavior is
    // decided where the programs live, not only in the build scripts.
    println!("cargo:rerun-if-env-changed=LAZYOS_DESKTOP");
    println!("cargo:rustc-check-cfg=cfg(lazyos_desktop)");
    if env::var_os("LAZYOS_DESKTOP").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_desktop");
    }

    // The built-in xui programs that open at boot (issue #509): the desktop
    // apps are packages whose manifest says whether they open at boot, but the
    // Terminal and Devices are built-in programs, so `init` learns them here
    // from the same `LAZYOS_XUI_AUTOSTART` list the image build reads
    // (`build_support/core_packages.rs`): unset or `none` means nothing,
    // otherwise the built-ins it names (`term`/`terminal`, `devices`),
    // as `init` registry ids in `LAZYOS_BUILTIN_AUTOSTART`.
    println!("cargo:rerun-if-env-changed=LAZYOS_XUI_AUTOSTART");
    let list = env::var("LAZYOS_XUI_AUTOSTART").unwrap_or_default();
    let mut builtins: Vec<&str> = Vec::new();
    for item in list.split(',').map(str::trim) {
        let id = match item {
            "term" | "terminal" => "terminal",
            "devices" => "devices",
            _ => continue,
        };
        if !builtins.contains(&id) {
            builtins.push(id);
        }
    }
    println!(
        "cargo:rustc-env=LAZYOS_BUILTIN_AUTOSTART={}",
        builtins.join(",")
    );

    // virtio-sound driver (docs/driver-plan.md D6): `LAZYOS_SOUND=1` adds the
    // `sndd` row to `init`'s manifest (the ELF itself is embedded by the root
    // build script), so a services boot supervises the driver.
    println!("cargo:rerun-if-env-changed=LAZYOS_SOUND");
    // `LAZYOS_SOUND_MODPLAY=1` makes `sndd demo=1` run the `modplay` self-test
    // instead of the `beep` clients (`tools/sound/run.py --modplay`).
    println!("cargo:rerun-if-env-changed=LAZYOS_SOUND_MODPLAY");
    // `LAZYOS_SOUND_MIX=1` makes `audiod demo=1` play two tones at once and a
    // half-volume tone instead (`tools/sound/run.py --mix`).
    println!("cargo:rerun-if-env-changed=LAZYOS_SOUND_MIX");
    println!("cargo:rustc-check-cfg=cfg(lazyos_sound)");
    // The desktop profile ships the sound stack too (`beep` is a shell command).
    if env::var_os("LAZYOS_SOUND").as_deref() == Some(std::ffi::OsStr::new("1"))
        || env::var_os("LAZYOS_DESKTOP").as_deref() == Some(std::ffi::OsStr::new("1"))
    {
        println!("cargo:rustc-cfg=lazyos_sound");
    }

    // USB HID driver (docs/usb-hid-plan.md U2): `LAZYOS_USB=1` adds the `usbd`
    // row to `init`'s manifest (the ELF is embedded by the root build script).
    println!("cargo:rerun-if-env-changed=LAZYOS_USB");
    println!("cargo:rustc-check-cfg=cfg(lazyos_usb)");
    if env::var_os("LAZYOS_USB").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_usb");
    }
    // `LAZYOS_UI_PROBE=1` (issue #538, debug images): `xuid` prints each
    // window's content rectangle as a `UI:RECT` line for session scripts. A
    // compile-time switch: the compositor never touches the file system for it.
    println!("cargo:rerun-if-env-changed=LAZYOS_UI_PROBE");
    println!("cargo:rustc-check-cfg=cfg(lazyos_ui_probe)");
    if env::var_os("LAZYOS_UI_PROBE").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_ui_probe");
    }
    // `LAZYOS_USB_TRACE=1` (test images only, set by `tools/usb/run.py`):
    // `usbd` echoes every report and key edge on serial for the harness's
    // judge. Never on by default: the trace would carry typed passwords.
    println!("cargo:rerun-if-env-changed=LAZYOS_USB_TRACE");
    println!("cargo:rustc-check-cfg=cfg(lazyos_usb_trace)");
    if env::var_os("LAZYOS_USB_TRACE").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_usb_trace");
    }
    // `LAZYOS_USB_CRASH_TEST=1` (U5 restart test, `tools/usb/run.py
    // --restart`): `usbd` exits with status 3 right after publishing its first
    // key press, on its first attempt only, so `init` restarts it and the
    // kernel must have released the held key.
    println!("cargo:rerun-if-env-changed=LAZYOS_USB_CRASH_TEST");
    println!("cargo:rustc-check-cfg=cfg(lazyos_usb_crash_test)");
    if env::var_os("LAZYOS_USB_CRASH_TEST").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_usb_crash_test");
    }

    // virtio-net driver (docs/networking-plan.md N1): `LAZYOS_NET=1` adds the
    // `netdrv` row to `init`'s manifest (the ELFs are embedded by the root
    // build script), so a services boot supervises the driver.
    println!("cargo:rerun-if-env-changed=LAZYOS_NET");
    println!("cargo:rustc-check-cfg=cfg(lazyos_net)");
    // `LAZYOS_NETD=1` adds the `netd` row and implies the driver's.
    println!("cargo:rerun-if-env-changed=LAZYOS_NETD");
    // `LAZYOS_NETD_ARGS` replaces `netd`'s `demo=1` (an interactive boot).
    println!("cargo:rerun-if-env-changed=LAZYOS_NETD_ARGS");
    println!("cargo:rustc-check-cfg=cfg(lazyos_netd)");
    let netd = env::var_os("LAZYOS_NETD").as_deref() == Some(std::ffi::OsStr::new("1"));
    if netd || env::var_os("LAZYOS_NET").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_net");
    }
    if netd {
        println!("cargo:rustc-cfg=lazyos_netd");
    }

    // The device manager (issue #497, docs/driver-plan.md 3.6): whenever the
    // image carries a sound or network driver, `init` starts `devd`, which
    // matches the enumerated devices and asks `init` to start each driver for
    // the device it found. `LAZYOS_DEVD=0` keeps the old static rows (`init`
    // starts `netdrv`/`sndd` unconditionally and each finds its own device).
    println!("cargo:rerun-if-env-changed=LAZYOS_DEVD");
    println!("cargo:rustc-check-cfg=cfg(lazyos_devd)");
    let sound = env::var_os("LAZYOS_SOUND").as_deref() == Some(std::ffi::OsStr::new("1"))
        || env::var_os("LAZYOS_DESKTOP").as_deref() == Some(std::ffi::OsStr::new("1"));
    let net = netd || env::var_os("LAZYOS_NET").as_deref() == Some(std::ffi::OsStr::new("1"));
    let devd_off = env::var_os("LAZYOS_DEVD").as_deref() == Some(std::ffi::OsStr::new("0"));
    if (sound || net) && !devd_off {
        println!("cargo:rustc-cfg=lazyos_devd");
    }
}
