use std::env;
use std::fs;
use std::path::Path;

/// Pixel size the chrome faces are rasterized at (window titles, taskbar,
/// menus). One size per face keeps the atlas small.
const CHROME_PX: f32 = 13.0;

/// Rasterize the bundled proportional faces into `typeface_data.rs`, included
/// by `src/messenger/display/typeface.rs`.
fn generate_typefaces(manifest: &str) {
    let out_dir = env::var("OUT_DIR").expect("out dir");
    let mut src = String::from("// @generated by user/build.rs -- do not edit by hand.\n");
    for (name, file) in [
        ("SANS", "DroidSans.ttf"),
        ("SERIF", "DroidSerif-Regular.ttf"),
    ] {
        let path = Path::new(manifest).join("../assets/fonts").join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {file}: {e}"));
        let atlas = font_atlas::build(&bytes, CHROME_PX);
        let blob = format!("typeface_{}.bin", name.to_lowercase());
        fs::write(Path::new(&out_dir).join(&blob), &atlas.coverage).expect("write coverage");
        src.push_str(&format!(
            "pub static {name}: FaceData = FaceData {{\n    ascender: {},\n    descender: {},\n    line_height: {},\n    glyphs: &[\n",
            atlas.ascender, atlas.descender, atlas.line_height
        ));
        for g in &atlas.glyphs {
            src.push_str(&format!(
                "        Glyph {{ width: {}, height: {}, left: {}, top: {}, offset: {}, advance_x16: {} }},\n",
                g.width, g.height, g.left, g.top, g.offset, g.advance_x16
            ));
        }
        src.push_str(&format!(
            "    ],\n    coverage: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{blob}\")),\n}};\n"
        ));
    }
    fs::write(Path::new(&out_dir).join("typeface_data.rs"), src).expect("write typeface data");
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    // Link the program as a static (non-PIE) ELF64 at a fixed base with our own
    // entry point.
    println!("cargo:rustc-link-arg=-T{manifest}/link.ld");
    println!("cargo:rustc-link-arg=-no-pie");
    println!("cargo:rustc-link-arg=-static");
    println!("cargo:rerun-if-changed=link.ld");
    println!("cargo:rerun-if-changed=build.rs");
    generate_typefaces(&manifest);

    // Desktop profile (issue #217): `LAZYOS_DESKTOP=1` marks the image as a
    // user-facing desktop. `init` reads `cfg(lazyos_desktop)` to keep the
    // demo/evidence-only programs (the crash test, the clipboard demo pair, the
    // `top` launch self-test) out of the boot, so the profile's behavior is
    // decided where the programs live, not only in the build scripts.
    println!("cargo:rerun-if-env-changed=LAZYOS_DESKTOP");
    println!("cargo:rustc-check-cfg=cfg(lazyos_desktop)");
    if env::var_os("LAZYOS_DESKTOP").as_deref() == Some(std::ffi::OsStr::new("1")) {
        println!("cargo:rustc-cfg=lazyos_desktop");
    }
}
