//! Parcel helpers for the clipboard protocol.
//!
//! The wire shapes are the `midlc`-generated `os.lazy.clipboard.v1` stubs
//! ([`super::wire`]); this module frames them in parcels on the right scope
//! interface and converts to the module's plain Rust types. The structured
//! error rides in the standard error field every service shares
//! (`messenger_generated::errors`).

use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

use libmessenger::{Decoder, Encoder, Kind, Parcel};

use super::super::{errno, Error, Result};
use super::{
    parcel, wire, BufferHandle, OfferInfo, OfferRequest, INTERFACE, OWNER_INTERFACE,
    READ_INTERFACE, WRITE_INTERFACE,
};

/// The standard reply error field (`docs/midl.md`, "Errors"), generated by `midlc`.
use messenger_generated::errors::ERROR_FIELD;

/// `Offer(owner, mime_types) -> token` for an eager offer: the payloads
/// ride along and the service keeps one bounded copy.
pub fn offer_request(owner: &str, offers: &[(&str, &[u8])]) -> Result<Parcel> {
    let args = wire::OfferArgs {
        owner: String::from(owner),
        sink: None,
        mimes: offers.iter().map(|(mime, _)| String::from(*mime)).collect(),
        data: offers
            .iter()
            .map(|(mime, bytes)| wire::Payload {
                mime: String::from(*mime),
                bytes: bytes.to_vec(),
            })
            .collect(),
    };
    let body = wire::encode_offer_args(&args).map_err(Error::Parcel)?;
    Ok(parcel(WRITE_INTERFACE, wire::METHOD_OFFER, body))
}

/// `Offer` for a lazy offer: only the MIME list crosses the wire. `sink`
/// names the registry entry where the owner serves [`super::method::SERIALIZE`]
/// when a paste actually happens.
pub fn offer_lazy_request(owner: &str, sink: &str, mimes: &[&str]) -> Result<Parcel> {
    let args = wire::OfferArgs {
        owner: String::from(owner),
        sink: Some(String::from(sink)),
        mimes: mimes.iter().map(|mime| String::from(*mime)).collect(),
        data: Vec::new(),
    };
    let body = wire::encode_offer_args(&args).map_err(Error::Parcel)?;
    Ok(parcel(WRITE_INTERFACE, wire::METHOD_OFFER, body))
}

/// An `Offer` reply carrying the new token.
pub fn token_reply(token: u64) -> Result<Parcel> {
    let body = wire::encode_offer_reply(&wire::OfferReply { token }).map_err(Error::Parcel)?;
    Ok(parcel(WRITE_INTERFACE, wire::METHOD_OFFER, body))
}

/// `Request(token, mime)`; `token == 0` selects the newest offer in the
/// caller's session that lists `mime`.
pub fn request_request(token: u64, mime: &str) -> Result<Parcel> {
    let args = wire::RequestArgs {
        token,
        mime: String::from(mime),
    };
    let body = wire::encode_request_args(&args).map_err(Error::Parcel)?;
    Ok(parcel(READ_INTERFACE, wire::METHOD_REQUEST, body))
}

/// A `Request` reply carrying the payload (the `BufferHandle` shape).
pub fn request_reply(handle: &BufferHandle) -> Result<Parcel> {
    let reply = wire::RequestReply {
        token: handle.token,
        mime: handle.mime.clone(),
        lazy: handle.lazy,
        bytes: handle.bytes.clone(),
    };
    let body = wire::encode_request_reply(&reply).map_err(Error::Parcel)?;
    Ok(parcel(READ_INTERFACE, wire::METHOD_REQUEST, body))
}

/// `Serialize(token, mime)`: the service calls this on a lazy offer's owner
/// endpoint when a paste happens.
pub fn serialize_request(token: u64, mime: &str) -> Result<Parcel> {
    let args = wire::SerializeArgs {
        token,
        mime: String::from(mime),
    };
    let body = wire::encode_serialize_args(&args).map_err(Error::Parcel)?;
    Ok(parcel(OWNER_INTERFACE, wire::METHOD_SERIALIZE, body))
}

/// The owner's `Serialize` answer.
pub fn serialize_reply(bytes: &[u8]) -> Result<Parcel> {
    let reply = wire::SerializeReply {
        bytes: bytes.to_vec(),
    };
    let body = wire::encode_serialize_reply(&reply).map_err(Error::Parcel)?;
    Ok(parcel(OWNER_INTERFACE, wire::METHOD_SERIALIZE, body))
}

/// A `Ping` request.
pub fn ping_request() -> Parcel {
    ok_reply(INTERFACE, wire::METHOD_PING)
}

/// A `Current` request (offer metadata only; never content).
pub fn current_request() -> Parcel {
    ok_reply(INTERFACE, wire::METHOD_CURRENT)
}

/// An empty successful reply on `interface_id`/`method`.
pub fn ok_reply(interface_id: u64, method: u32) -> Parcel {
    parcel(interface_id, method, Vec::new())
}

/// The generated metadata record for `info`.
pub fn to_wire_meta(info: &OfferInfo) -> wire::OfferMeta {
    wire::OfferMeta {
        token: info.token,
        owner: info.owner.clone(),
        session: info.session,
        mimes: info.mimes.clone(),
        lazy: info.lazy,
        tick: info.tick,
    }
}

/// The plain-Rust view of a generated metadata record.
pub fn from_wire_meta(meta: wire::OfferMeta) -> OfferInfo {
    OfferInfo {
        token: meta.token,
        owner: meta.owner,
        session: meta.session,
        mimes: meta.mimes,
        lazy: meta.lazy,
        tick: meta.tick,
    }
}

/// Encode `info` into a `Current` reply; `None` when no offer is live.
pub fn current_reply(info: Option<&OfferInfo>) -> Result<Parcel> {
    let reply = wire::CurrentReply {
        offer: info.map(to_wire_meta),
    };
    let body = wire::encode_current_reply(&reply).map_err(Error::Parcel)?;
    Ok(parcel(INTERFACE, wire::METHOD_CURRENT, body))
}

/// The service's error answer: errno-style code plus friendly text.
pub fn error_reply(interface_id: u64, method: u32, error: Error) -> Parcel {
    let code = error.errno().map(|code| -code).unwrap_or(errno::EINVAL);
    let mut body = Encoder::new();
    // A structured error field cannot overflow a fresh encoder here.
    let _ = body.error(ERROR_FIELD, code as u32, error.message());
    parcel(interface_id, method, body.finish())
}

/// The first structured error field, when the reply is a service failure.
///
/// `pub(super)` so [`super::client`] can check every reply for a service
/// failure without re-decoding the parcel.
pub(super) fn error_field(parcel: &Parcel) -> Result<Option<i64>> {
    let mut decoder = Decoder::new(&parcel.body);
    while let Some(item) = decoder.next().map_err(Error::Parcel)? {
        if item.kind == Kind::Error && item.id == ERROR_FIELD {
            let (code, _message) = item.error_parts().map_err(Error::Parcel)?;
            return Ok(Some(code as i64));
        }
    }
    Ok(None)
}

/// Decode an `Offer` request into its owner, sink, MIME list and payloads.
pub fn decode_offer(parcel: &Parcel) -> Result<OfferRequest> {
    let args = wire::decode_offer_args(&parcel.body).map_err(Error::Parcel)?;
    Ok(OfferRequest {
        owner: args.owner,
        sink: args.sink,
        mimes: args.mimes,
        data: args
            .data
            .into_iter()
            .map(|payload| (payload.mime, payload.bytes))
            .collect(),
    })
}

/// Decode a `Request` into `(token, mime)`.
pub fn decode_request(parcel: &Parcel) -> Result<(u64, String)> {
    let args = wire::decode_request_args(&parcel.body).map_err(Error::Parcel)?;
    Ok((args.token, args.mime))
}

/// Decode a `Serialize` into `(token, mime)`.
pub fn decode_serialize(parcel: &Parcel) -> Result<(u64, String)> {
    let args = wire::decode_serialize_args(&parcel.body).map_err(Error::Parcel)?;
    Ok((args.token, args.mime))
}

/// Decode a `Request` reply's payload bytes.
pub fn decode_bytes(parcel: &Parcel) -> Result<Vec<u8>> {
    let reply = wire::decode_request_reply(&parcel.body).map_err(Error::Parcel)?;
    Ok(reply.bytes)
}

/// Decode a `Serialize` reply's payload bytes.
pub fn decode_serialized(parcel: &Parcel) -> Result<Vec<u8>> {
    let reply = wire::decode_serialize_reply(&parcel.body).map_err(Error::Parcel)?;
    Ok(reply.bytes)
}

/// Decode an `Offer` reply's token.
pub fn decode_token(parcel: &Parcel) -> Result<u64> {
    let reply = wire::decode_offer_reply(&parcel.body).map_err(Error::Parcel)?;
    Ok(reply.token)
}

/// Decode a `Current` reply into the live offer's metadata.
pub fn decode_current(parcel: &Parcel) -> Result<Option<OfferInfo>> {
    let reply = wire::decode_current_reply(&parcel.body).map_err(Error::Parcel)?;
    Ok(reply.offer.map(from_wire_meta))
}

/// Render a decoded `PasteEvent` as the one-line text `logd` records, so a
/// consumer of the typed `system/events/clipboard/paste` topic displays the
/// same fields the hand-encoded payload used to carry.
pub fn paste_event_text(event: &wire::PasteEvent) -> String {
    format!(
        "paste #{} uid={} session={} mime={} app={} bytes={} lazy={}",
        event.seq, event.uid, event.session, event.mime, event.app, event.bytes, event.lazy
    )
}

/// Render a decoded `ClipboardDenial` as the one-line text `logd` records for
/// the `system/events/security/clipboard` topic.
pub fn denial_event_text(event: &wire::ClipboardDenial) -> String {
    format!(
        "deny #{} uid={} session={} mime={} app={} token={}",
        event.seq, event.uid, event.session, event.mime, event.app, event.token
    )
}
